### ISSUE TITLE
Remove qreg use from qubit_qis.h

### ISSUE THREAD

**Issue by schweitzpgi** [NVIDIA/cuda-quantum#1026]
qreg is used in a concept in this header. Can the concept be deleted?

**Comment by kala-ghoda** [comment]
Hi, I'd like to try and help with this issue. Can you please assign it to me?

**Comment by schweitzpgi** [comment]
> Hi, I'd like to try and help with this issue. Can you please assign it to me?

I think it may have been done already. @amccaskey ?
