### ISSUE TITLE
[RFC] qubits with initial states

### ISSUE THREAD

**Issue by schweitzpgi** [NVIDIA/cuda-quantum#1110]
This is a proposal to add the ability to specify an initial state when declaring a qubit.

## C++

We add new constructors to `qubit` and `qvector` to take a `initializer_list` or `vector<complex<double>>` that is $2^N$ `double` values in length and where $N$ is the number of qubit in the `qvector` object. (`qubit` would be restricted to 2 `double` values.

New constructors
```
  qubit::qubit(const vector<complex<double>>&);
  qubit::qubit(const initializer_list<complex<double>>&);
  qvector::qvector(const vector<complex<double>>&);
  qvector::qvector(const initializer_list<complex<double>>&);
```

Some examples in a CUDA Quake kernel might be the following.
```
  cudaq::qubit q = {0., 1.};
  cudaq::qubit q = cudaq::ket::one;
  cudaq::qubit q = {M_SQRT1_2, M_SQRT1_2};
  cudaq::qvector q = {M_SQRT1_2, 0., 0., M_SQRT1_2};
  cudaq::qvector q = complexVectorObject;
```

New builder method
```
  QuakeValue qalloc(vector<complex<double>> &)
```

When using the builder the builder would be called as in the following.
```
  std::vector<cudaq::complex> vec{M_SQRT1_2, 0., 0., M_SQRT1_2};
  auto qubits = kernel.qalloc(vec);
```

## Python

The Python builder would be similar as in the following.
```
  v = [0., 1., 1., 0.]
  qubits = kernel.qalloc(v)
```

See #1090

**Comment by bettinaheim** [comment]
Updated #1086 and closing this as duplicate - RFC will be tracked in https://github.com/NVIDIA/cuda-quantum/issues/1086.
