### ISSUE TITLE
Intermittent CI llvm-lit test failures for `remote-mqpu` 

### ISSUE THREAD

**Issue by 1tnguyen** [NVIDIA/cuda-quantum#1117]
The llvm-lit tests for the `remote-mqpu` target showed some instability on CI. 

Intermittently, there is a runtime error throwed: `bind: port already in use`. It could be due to a race condition when multiple parallel tests try to check and claim a random port number. The heuristic to avoid this collision seems not reliable enough.

**Comment by 1tnguyen** [comment]
Note: this issue could also be related to a hang issue as seen in this [CI run](https://github.com/NVIDIA/cuda-quantum/actions/runs/7748142855/job/21131929904?pr=1077).

**Comment by bmhowe23** [comment]
Resolved by #1190
