### ISSUE TITLE
apply_call is generating an error message

### ISSUE THREAD

**Issue by mmvandieren** [NVIDIA/cuda-quantum#1130]
### Required prerequisites

- [X] Make sure you've read the [documentation](https://nvidia.github.io/cuda-quantum/latest). Your issue may be addressed there.
- [X] Search the [issue tracker](https://github.com/NVIDIA/cuda-quantum/issues) to verify that this hasn't already been reported. +1 or comment there if it has.
- [X] If possible, make a PR with a failing test to give us a starting point to work on!

### Describe the bug

I get the error message below about an invalid type being passed to the kernel, but it is a float which should be ok.

![Screenshot 2024-01-23 at 1 53 20 PM](https://github.com/NVIDIA/cuda-quantum/assets/150082832/1aaebc90-c38a-46b9-9e94-4d483cf54a3b)

### Steps to reproduce the bug

the code below generates the bug

```# Define a kernel function for the a pair of qubits in the problem kernel
qaoaProblem, qubit_0, qubit_1, alpha = cudaq.make_kernel(cudaq.qubit, cudaq.qubit, float)
qaoaProblem.cx(qubit_0, qubit_1)
qaoaProblem.rz(2*alpha,qubit_1)
qaoaProblem.cx(qubit_0, qubit_1)





from typing import List
# Approach 1: Define everything in one kernel

# Variable for the number of layers in the QAOA kernel
layer_count = 1 # This value can be increased, but at the cost of increased circuit depth

# Define a quantum kernel function for a parameterized quantum circuit
qaoaKernel, thetas = cudaq.make_kernel(List[float])

# Let's allocate a few qubits to our quantum circuit
# The number of qubits we'll need is the same as the number of vertices in our graph
qubit_count = 5

# Allocate n qubits to the kernel.
qreg = qaoaKernel.qalloc(qubit_count)

# Apply a Hadamard gate to each qubit
qaoaKernel.h(qreg)

# The QAOA circuit for Max Cut depends on the structure of the graph
# Each node is associated with a qubit. We'll sort the nodes and 
# use the index of a vertex in this sorted list to determine the qubit
# associated with that vertex.
nodes = [2,5,7]
edges = [(2,5), (5,7)]

# Loop over the layers
for i in range(layer_count):
    # Problem unitary
    for edge in edges:
        qubitu = qreg[nodes.index(edge[0])]
        qubitv = qreg[nodes.index(edge[1])]
        # I'm getting an error message with the next line
        qaoaKernel.apply_call(qaoaProblem, qubitu, qubitv, thetas[i])

```

### Expected behavior

the kernel called `qaoaProblem` should be applied to the 2 given qubits with the parameter value.  The parameter value seems to generate and error message.

### Is this a regression? If it is, put the last known working version (or commit) here.

Not a regression

### Environment

- **CUDA Quantum version**: container 40733b768160 
- **Python version**:  3.10.12
- **C++ compiler**:  unknown
- **Operating system**: linux  

### Suggestions

`Type argType = otherFuncCloned.getArgumentTypes()[i];`

should be

`Type argType = otherFuncCloned.getArgumentTypes()[i++];`
the `i` was not being incremented

[https://github.com/NVIDIA/cuda-quantum/blob/main/runtime/cudaq/builder/kernel_builder.cpp#L295](https://github.com/NVIDIA/cuda-quantum/blob/main/runtime/cudaq/builder/kernel_builder.cpp#L295)

**Comment by bmhowe23** [comment]
Fixed via #1131
