### ISSUE TITLE
Target multiple architectures in parallel 

### ISSUE THREAD

**Issue by zohimchandani** [NVIDIA/cuda-quantum#114]
### Required prerequisites

- [X] Search the [issue tracker](https://github.com/NVIDIA/cuda-quantum/issues) to check if your feature has already been mentioned or rejected in other issues.

### Describe the feature

Future workflows will require running on GPUs and QPUs in parallel. 

I envision a workflow suggested below to allow error mitigation: 

```
exp_vals = cudaq.observe_n_async(kernel, h, parameters, backed = 'superconducting_provider')  

approx_exp_vals = cudaq.observe_n_async(kernel_clifford_approximation, h, parameters, backed = 'gpu0') 
```

Both lines should be able to run in parallel via a futures request.

**Comment by bettinaheim** [comment]
This can be handled via multiple lines of code. At some point, we will need to generalize the platform definition to allow defining platforms with different processors. Until then, we will leave it as is.
