### ISSUE TITLE
Issue with loading both `mgpu` and `mpi4py` plugin dynamical libraries

### ISSUE THREAD

**Issue by 1tnguyen** [NVIDIA/cuda-quantum#1144]
In Python wheels, after `libnvqir-nvidia-mgpu.so` is loaded during `import cudaq`, the dynamically loading of the `mpi4py`-based plugin is not successful. Specifically, the `dlopen()` check is failing

https://github.com/NVIDIA/cuda-quantum/blob/ab96c9c054cae7991d797de472f7456efcf7ba9e/runtime/cudaq/distributed/mpi_plugin.cpp#L28-L29 

It is working **without** `libnvqir-nvidia-mgpu.so` loaded.

**Comment by bettinaheim** [comment]
I think switching to link the necessary cuda libraries statically for this backend should resolve the issue. This seems to work locally, and I am building a new set of packages now to fully confirm this.

**Comment by bettinaheim** [comment]
Closing this as we decided that we need to go with a manual plugin activation for Python as well.
