### ISSUE TITLE
[experimental/python] Improvements, gaps and fixes: Part#1

### ISSUE THREAD

**Issue by khalatepradnya** [NVIDIA/cuda-quantum#1157]
Gaps in features and enhancement:

Must have:
- [x] Build Python wheel on arm64 platform
- [x] Enable remote simulator target (and corresponding tests)
- [x] Enhance tests for remote backend with new Python APIs
- [x] Port `vqe` module
- [x] Port `parallel` module
- [x] Port `chemistry` module
- [x] Fix `State`, `get_state_async`, `AsyncStateResult`
- [x] Enable `OptimizationResult`
- [x] Enable `broadcast` in `mpi` 
- [x] Implement `observe_async` in eager mode
- [x] Bug in AST compilation where `register_name='name'` is ignored
- [x] bug with ordering of kernel definitions and kernel composition
- [x] bug with transitive kernel dependencies
- [x] sample_async eager mode
- [x] check control self.popValue() calls (bug with too many calls to popValue fixed for one scenario, could be others)
- [x] vqe for eager / mlir mode kernels
- [x] drop `qlist`
-  Implement `from_state`: Will be addressed separately 
- [x] `range(q, p, -1), p == 0`
- [x]  Add Python binding for `NvcfSimulatorQPU` similar to `PyRemoteSimulatorQPU`

Nice to have:
- Enable building and usage of old Python bindings and new MLIR bindings side-by-side (fix for LLVM static initialization issue)

**Comment by khalatepradnya** [comment]
Issues related with `State` will be addressed by https://github.com/NVIDIA/cuda-quantum/pull/1123

**Comment by khalatepradnya** [comment]
- `parallel` fixed in commit [d5459b2](https://github.com/NVIDIA/cuda-quantum/pull/1077/commits/d5459b227ca941fe0584d66dfeb1a1e81a43f41d) on PR #1077
- `vqe` fixed in commit [4bf7a4a](https://github.com/NVIDIA/cuda-quantum/pull/1077/commits/4bf7a4a7b65c6425201b3dca4292330cfd836d86) on PR #1077

**Comment by khalatepradnya** [comment]
- `chemistry` fixed in commit [c635d9f](https://github.com/NVIDIA/cuda-quantum/pull/1077/commits/c635d9f2a75f6a4605870a21a6ad75e567bd089c) on PR https://github.com/NVIDIA/cuda-quantum/pull/1077

**Comment by khalatepradnya** [comment]
- Remote simulator target and existing tests enabled by commits [fbc07dd](https://github.com/NVIDIA/cuda-quantum/pull/1077/commits/fbc07dd24d5b41261d049394931e465eea4c428e) and [2439890](https://github.com/NVIDIA/cuda-quantum/pull/1077/commits/2439890b62391b3e95249357cb0d385d34526983) on PR https://github.com/NVIDIA/cuda-quantum/pull/1077

**Comment by amccaskey** [comment]
note here - need to disallow empty list initializer `l = []` since we don't allow default empty `std::vector<T>` construction (no dynamic memory allocation). Might need a new type with size argument for list initialization (beyond constant initialization l = `[1,2,3...]`, something like `l = cudaq.list_init(10)`

**Comment by khalatepradnya** [comment]
> I think the changes to JITExecutionCache.cpp (as originally done in [a610481](https://github.com/NVIDIA/cuda-quantum/commit/a610481b528bc78c02b53b757b4dc89f13a66d90) but later backed out) are likely still needed for thread safety reasons. Is that being tracked somewhere?

Yes, I have it in a new PR. But, good to note here as well for tracking.

**Comment by amccaskey** [comment]
Note - Need to fix issue with kernel composition requiring kernel argument being defined before kernel taking kernel as input.

**Comment by amccaskey** [comment]
Fix bug in AST mode where `register_name` is ignored for measurements

**Comment by khalatepradnya** [comment]
Remote simulator target tests enabled - PR https://github.com/NVIDIA/cuda-quantum/pull/1187

**Comment by khalatepradnya** [comment]
arm64 wheel fix - PR https://github.com/NVIDIA/cuda-quantum/pull/1216

**Comment by schweitzpgi** [comment]
> note here - need to disallow empty list initializer l = [] since we don't allow default empty std::vector<T> construction (no dynamic memory allocation). Might need a new type with size argument for list initialization (beyond constant initialization l = [1,2,3...], something like l = cudaq.list_init(10)

Pedantically speaking, we could allow it. But it wouldn't be terribly interesting. Fast though. Processing a vector with 0 elements should zoom-zoom.

**Comment by 1tnguyen** [comment]
- [ ] Add Python binding for `NvcfSimulatorQPU` similar to `PyRemoteSimulatorQPU`

In `main`, we've added `NvcfSimulatorQPU` as a derived class of `RemoteSimulatorQPU`. This inheritance needs to be mirrored in the new Python bindings.

**Comment by khalatepradnya** [comment]
Error handling and messaging captured in https://github.com/NVIDIA/cuda-quantum/issues/1251

**Comment by khalatepradnya** [comment]
https://github.com/NVIDIA/cuda-quantum/pull/1300
