### ISSUE TITLE
[experimental/python] Improvements, gaps and fixes: Part#2

### ISSUE THREAD

**Issue by khalatepradnya** [NVIDIA/cuda-quantum#1251]
## Feature scope
- [x] Remove `jit=False`
- [x] All tests run and work with `jit=True`
- [x] Fix Pylance errors on quantum operations

## Bugs
- [x] Fix list element access
 https://gist.github.com/schweitzpgi/587e23fd9348202b8013d564bfde1493
- [x] Cannot perform logical operations on measurement results https://gist.github.com/bmhowe23/537a319f410ca2db2179addd8967b25b

## Gaps
- [x] Support previous control operations with same signature `cx` --> `x.ctrl`
- Import processing - retain previous behavior, for e.g. not require `import uccsd` separately: Won't fix now
Discrepancy between how the compiler processes imports and how python processes imports. Details see the draft here: https://github.com/NVIDIA/cuda-quantum/pull/1249
- [x] Spec enforcement
       Issues:
      - `sample` accepts `expectation()`
      - `observe` accepts measurements and executes

## Error handling and messaging
- [x] Better wording for type errors 
(Currently, when there is a type error, tool gives a "printing generic form" followed by a dump of the MLIR representation)
- [x] A simple typo like `x[qubits[0]]` (square brackets) produces quite a long error message (stack trace)
- [x] Misleading error if you pass an `np.ndarray` with an unsupported subtype as a kernel argument 
https://gist.github.com/anthony-santana/a060471777196ece1d93b1839fd16c6b
- [x] Show a comprehensive error message instead of the raw MLIR error when error occurs due to different scoping rules than Python

**Comment by bettinaheim** [comment]
Re error handling: I would say never show the generated MLIR in an error message by default. Any print of MLIR should require setting an flag or environment variable explicitly.

**Comment by zohimchandani** [comment]
Unable to run `sample_async`, code runs fine with `sample`: 

```
import cudaq
from cudaq import spin 
import numpy as np 
```

```

cudaq.set_target('nvidia-mqpu')
```

```
@cudaq.kernel(jit=True)
def kernel(num_qubits: int, params: np.ndarray):
    
    qubits = cudaq.qvector(num_qubits)
    
    param_counter = 0 
    for i in range(0, num_qubits): 
        
        if i+1 == num_qubits: 
            break
        else: 
            
            x.ctrl(qubits[i], qubits[i+1]) 
            
            ry(params[param_counter], qubits[i])
            param_counter += 1
            
            ry(params[param_counter], qubits[i+1])
            param_counter += 1

            
    mz(qubits)


```

```
num_qubits = 4

params = np.random.rand(num_qubits*2 - 2)

result = cudaq.sample_async(kernel, num_qubits, params, qpu_id = 0 )

print(result)

```

```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Cell In[4], line 5
      1 num_qubits = 4
      3 params = np.random.rand(num_qubits*2 - 2)
----> 5 result = cudaq.sample_async(kernel, num_qubits, params)
      7 print(result)

RuntimeError: Could not pack argument: (4, array([0.39220953, 0.50040217, 0.59976919, 0.16836241, 0.10798458,
       0.57332278]))
```

Thanks a lot team.

**Comment by amccaskey** [comment]
how 

> Unable to run `sample_async`, code runs fine with `sample`:
> 
> ```
> import cudaq
> from cudaq import spin 
> import numpy as np 
> ```
> 
> ```
> 
> cudaq.set_target('nvidia-mqpu')
> ```
> 
> ```
> @cudaq.kernel(jit=True)
> def kernel(num_qubits: int, params: np.ndarray):
>     
>     qubits = cudaq.qvector(num_qubits)
>     
>     param_counter = 0 
>     for i in range(0, num_qubits): 
>         
>         if i+1 == num_qubits: 
>             break
>         else: 
>             
>             x.ctrl(qubits[i], qubits[i+1]) 
>             
>             ry(params[param_counter], qubits[i])
>             param_counter += 1
>             
>             ry(params[param_counter], qubits[i+1])
>             param_counter += 1
> 
>             
>     mz(qubits)
> ```
> 
> ```
> num_qubits = 4
> 
> params = np.random.rand(num_qubits*2 - 2)
> 
> result = cudaq.sample_async(kernel, num_qubits, params, qpu_id = 0 )
> 
> print(result)
> ```
> 
> ```
> ---------------------------------------------------------------------------
> RuntimeError                              Traceback (most recent call last)
> Cell In[4], line 5
>       1 num_qubits = 4
>       3 params = np.random.rand(num_qubits*2 - 2)
> ----> 5 result = cudaq.sample_async(kernel, num_qubits, params)
>       7 print(result)
> 
> RuntimeError: Could not pack argument: (4, array([0.39220953, 0.50040217, 0.59976919, 0.16836241, 0.10798458,
>        0.57332278]))
> ```
> 
> Thanks a lot team.

https://github.com/NVIDIA/cuda-quantum/pull/1293

**Comment by khalatepradnya** [comment]
Verified element access is fixed, following doesn't throw error -
```
import cudaq
from typing import List, Tuple

@cudaq.kernel
def qernel(thetas: List[float]):
  if thetas[0] == 0.0:
      pass
```

**Comment by khalatepradnya** [comment]
Pylance: https://github.com/NVIDIA/cuda-quantum/pull/1317
