### ISSUE TITLE
Raise warning when user executes observe_async() with mpirun.

### ISSUE THREAD

**Issue by mawolf2023** [NVIDIA/cuda-quantum#1338]
### Required prerequisites

- [X] Search the [issue tracker](https://github.com/NVIDIA/cuda-quantum/issues) to check if your feature has already been mentioned or rejected in other issues.

### Describe the feature

For MGPU, users execute their code with `mpirun -np N`.  In the case of MQPU, using observe_async or sample_async with mpirun will not produce the desired speedup and will actually slow the code, but will still produce the correct answer with no indication of what happened.  If one of the async methods is present, a warning should tell users not to use mpirun.

**Comment by bettinaheim** [comment]
@mawolf2023 We have made code changes that should ensure that there is no downside to using the async functions also with MPI. Can you give the concrete repro where you encountered the slow down?

**Comment by bettinaheim** [comment]
Closing as this should be resolved. If this is still an issue, please reopen with the concrete code example that runs into this.
