### ISSUE TITLE
`QuakeSynthesizer` cannot handle `std::vector<char>` argument type

### ISSUE THREAD

**Issue by 1tnguyen** [NVIDIA/cuda-quantum#1384]
### Required prerequisites

- [X] Consult the [security policy](https://github.com/NVIDIA/cuda-quantum/security/policy). If reporting a security vulnerability, do not report the bug using this form. Use the process described in the policy to report the issue.
- [X] Make sure you've read the [documentation](https://nvidia.github.io/cuda-quantum/latest). Your issue may be addressed there.
- [X] Search the [issue tracker](https://github.com/NVIDIA/cuda-quantum/issues) to verify that this hasn't already been reported. +1 or comment there if it has.
- [ ] If possible, make a PR with a failing test to give us a starting point to work on!

### Describe the bug

When there is a kernel argument of type `std::vector<char>`, `QuakeSynthesizer` couldn't perform the synthesis. This affects the hardware backends and remote backends (`nvqc`).

### Steps to reproduce the bug

```
#include <cudaq.h>
void f(const std::vector<char>& k) __qpu__ {
  cudaq::qubit q;
  for (int i = 0; i < k.size(); ++i)
    rx(1.0*k[i], q);
}

int main() {
  std::vector<char> x { 1, 2};  
  auto counts = cudaq::sample(f, x);
  counts.dump();
  return 0;
}
```

Run with:
```
nvq++ --target quantinuum --emulate test.cpp
./a.out
```

Error:

```
loc("test.cpp":2:1): error: 'func.func' op synthesis failed for vector<integral-type>.
loc("test.cpp":2:1): error: argument(s) still in use after synthesis.
terminate called after throwing an instance of 'std::runtime_error'
  what():  Could not successfully apply quake-synth.
Aborted (core dumped)
```

### Expected behavior

Successful synthesis.

### Is this a regression? If it is, put the last known working version (or commit) here.

Not a regression

### Environment

- **CUDA Quantum version**: main
- **Python version**: 3.10
- **C++ compiler**: gcc-12
- **Operating system**: Ubuntu22.04

**Comment by schweitzpgi** [comment]
FWIW, this isn't really a valid kernel signature. The vector must be pass by value according to the spec.
```c++
void f(const std::vector<char>& k) __qpu__ { // error
```
