### ISSUE TITLE
Circuit drawer retains qubits from previously printed kernel(s)

### ISSUE THREAD

**Issue by khalatepradnya** [NVIDIA/cuda-quantum#1400]
### Required prerequisites

- [X] Consult the [security policy](https://github.com/NVIDIA/cuda-quantum/security/policy). If reporting a security vulnerability, do not report the bug using this form. Use the process described in the policy to report the issue.
- [X] Make sure you've read the [documentation](https://nvidia.github.io/cuda-quantum/latest). Your issue may be addressed there.
- [X] Search the [issue tracker](https://github.com/NVIDIA/cuda-quantum/issues) to verify that this hasn't already been reported. +1 or comment there if it has.
- [ ] If possible, make a PR with a failing test to give us a starting point to work on!

### Describe the bug

When using `cudaq.draw` API to print kernels, the qubits from previously drawn kernel are retained.
Redrawing the same kernel repeatedly also keeps concatenating to the qubit count.

### Steps to reproduce the bug

```
import cudaq

@cudaq.kernel
def bell_pair():
    q = cudaq.qvector(2)
    h(q[0])
    cx(q[0], q[1])
    mz(q)


@cudaq.kernel
def kernel(angle:float):
    q = cudaq.qubit()
    h(q)
    ry(angle, q)

   
print(cudaq.draw(kernel, 0.59))
print(cudaq.draw(kernel, 0.59))
print(cudaq.draw(bell_pair))
```

Output:
```
root@b601c80e7f07:/workspaces/cuda-quantum/build# python3 test_draw.py 
     ╭───╮╭──────────╮
q0 : ┤ h ├┤ ry(0.59) ├
     ╰───╯╰──────────╯

                      
q0 : ─────────────────
     ╭───╮╭──────────╮
q1 : ┤ h ├┤ ry(0.59) ├
     ╰───╯╰──────────╯

               
q0 : ──────────
               
q1 : ──────────
     ╭───╮     
q2 : ┤ h ├──●──
     ╰───╯╭─┴─╮
q3 : ─────┤ x ├
          ╰───╯
```

### Expected behavior

Expected output:
```
root@b601c80e7f07:/workspaces/cuda-quantum/build# python3 test_draw.py 
     ╭───╮╭──────────╮
q0 : ┤ h ├┤ ry(0.59) ├
     ╰───╯╰──────────╯
          
     ╭───╮╭──────────╮
q0 : ┤ h ├┤ ry(0.59) ├
     ╰───╯╰──────────╯

     ╭───╮     
q0 : ┤ h ├──●──
     ╰───╯╭─┴─╮
q1 : ─────┤ x ├
          ╰───╯

```

### Is this a regression? If it is, put the last known working version (or commit) here.

Not a regression

### Environment

- **CUDA Quantum version**: `main` as of commit 30e1d3b1ae8514584d448398905833fc4ce73fb4
- **Python version**: 3.10.12
- **C++ compiler**: 
- **Operating system**: Ubuntu 22.04

**Comment by khalatepradnya** [comment]
Reference C++ sample
```
#include <cudaq.h>
#include <cudaq/algorithms/draw.h>

#include <iostream>

auto bell_pair = []() __qpu__ {
  cudaq::qvector q(2);
  h(q[0]);
  x<cudaq::ctrl>(q[0], q[1]);
  mz(q);
};

auto kernel = [](float angle) __qpu__ {
  cudaq::qvector q(1);
  h(q[0]);
  ry(angle, q[0]);
};

int main() {
  std::cout << cudaq::draw(kernel, 0.59);
  std::cout << cudaq::draw(bell_pair);
  std::cout << cudaq::draw(kernel, 0.59);
  return 0;
}
```

Output:
```root@b601c80e7f07:/workspaces/cuda-quantum/build# nvq++ test_draw.cpp -o test_draw.x && ./test_draw.x
     ╭───╮╭──────────╮
q0 : ┤ h ├┤ ry(0.59) ├
     ╰───╯╰──────────╯
     ╭───╮     
q0 : ┤ h ├──●──
     ╰───╯╭─┴─╮
q1 : ─────┤ x ├
          ╰───╯
     ╭───╮╭──────────╮
q0 : ┤ h ├┤ ry(0.59) ├
     ╰───╯╰──────────╯
```

**Comment by bmhowe23** [comment]
I believe that this issue (or something similar to this issue) may also be preventing us from adding tests to the end of `python/tests/kernel/test_kernel_features.py`, so any fix to this issue should probably try to add tests like `test_no_valueerror_np_array` to the end of that file.

**Comment by mmvandieren** [comment]
I've experienced this again using version 0.8.0.

**Comment by mmvandieren** [comment]
This time the incorrect circuits are slightly different than the example above.

```import cudaq

@cudaq.kernel
def bell_pair():
    q = cudaq.qvector(2)
    h(q[0])
    cx(q[0], q[1])
    mz(q)


@cudaq.kernel
def kernel(angle:float):
    q = cudaq.qubit()
    h(q)
    ry(angle, q)

   
print(cudaq.draw(kernel, 0.59))
print(cudaq.draw(kernel, 0.59))
print(cudaq.draw(bell_pair))```

incorrect output:


![Image](https://github.com/user-attachments/assets/2726f8d0-125a-4165-81b5-4fe4fb032321)

**Comment by mmvandieren** [comment]
restarting the Python kernel, eliminated the error above.  But then it generated this one which strongly is ok for the 1st 2 kernels, but the 3rd adds an extra qubit.



![Image](https://github.com/user-attachments/assets/3f045523-7d1b-4834-93ed-ccc4daaf1db3)



```# Allocating qubits and calling the subroutines defined above
@cudaq.kernel
def minimal_example_program(num_qubits: int): 
    
    # Allocate num_qubits qubits indexed from 0 to num_qubits-1
    qvector = cudaq.qvector(num_qubits) # By default these qubits are the zero state
    
    # Initialize qubit indexed with 1 as the minus state 
    # by calling the minus kernel acting on the qubit
    y(qvector[1])
    
    # Manipulate the quantum states by applying the bit flip gate (the `x` gate) to each qubit
    # by calling the xgate kernel applied to a list of qubits
    x(qvector) 



num_qubits = 2 # num_qubits should be an integer > 1
for i in range(3):
    num_qubits = num_qubits+i
    print(cudaq.draw(nested_quantum_program,num_qubits))

**Comment by mmvandieren** [comment]
restarting the python kernel seems to eliminate the error.
