### ISSUE TITLE
AttributeError: module 'cudaq' has no attribute 'kernel'. Did you mean: 'Kernel'?

### ISSUE THREAD

**Issue by sirgeorgesawcon** [NVIDIA/cuda-quantum#1433]
### Required prerequisites

- [X] Consult the [security policy](https://github.com/NVIDIA/cuda-quantum/security/policy). If reporting a security vulnerability, do not report the bug using this form. Use the process described in the policy to report the issue.
- [X] Make sure you've read the [documentation](https://nvidia.github.io/cuda-quantum/latest). Your issue may be addressed there.
- [X] Search the [issue tracker](https://github.com/NVIDIA/cuda-quantum/issues) to verify that this hasn't already been reported. +1 or comment there if it has.
- [ ] If possible, make a PR with a failing test to give us a starting point to work on!

### Describe the bug

AttributeError: module 'cudaq' has no attribute 'kernel'. Did you mean: 'Kernel'?

### Steps to reproduce the bug

```python
import sys
import cudaq

print(f"Running on target {cudaq.get_target().name}")
qubit_count = int(sys.argv[1]) if 1 < len(sys.argv) else 2


@cudaq.kernel
def kernel():
    qubits = cudaq.qvector(qubit_count)
    h(qubits[0])
    for i in range(1, qubit_count):
        x.ctrl(qubits[0], qubits[i])
    mz(qubits)


result = cudaq.sample(kernel)
print(result)  # Example: { 11:500 00:500 }
```

### Expected behavior

{ 11:500 00:500 }

### Is this a regression? If it is, put the last known working version (or commit) here.

Not a regression

### Environment

- **CUDA Quantum version**:  0.5.0
- **Python version**:  3.11.5
- **Operating system**:  Ubuntu 22.04

**Comment by khalatepradnya** [comment]
Thanks for reporting this... Want to confirm the CUDA-Q version, you mentioned 0.5.0...
This feature of expressing kernels in Python with `cudaq.kernel` decorator was introduced in version 0.7.0... Can you try with the latest version and check if works?

**Comment by sirgeorgesawcon** [comment]
Hi, thanks, Updating it to the latest cuda-quantum version fixed the issue.
