### ISSUE TITLE
Support numpy arcsin in python mlir

### ISSUE THREAD

**Issue by anthony-santana** [NVIDIA/cuda-quantum#1453]
### Required prerequisites

- [X] Search the [issue tracker](https://github.com/NVIDIA/cuda-quantum/issues) to check if your feature has already been mentioned or rejected in other issues.

### Describe the feature

Support the following numpy operation:

```
import cudaq
import numpy as np

@cudaq.kernel
def kernel():
   value = np.arcsin(0.0)
```

**Comment by bettinaheim** [comment]
See also: https://github.com/NVIDIA/cuda-quantum/issues/1455
Let's track that in one place. Closing this to track this in 1455.
