### ISSUE TITLE
MGPU backend 

### ISSUE THREAD

**Issue by zohimchandani** [NVIDIA/cuda-quantum#148]
### Required prerequisites

- [X] Make sure you've read the [documentation](https://nvidia.github.io/cuda-quantum). Your issue may be addressed there.
- [X] Search the [issue tracker](https://github.com/NVIDIA/cuda-quantum/issues) to verify that this hasn't already been reported. +1 or comment there if it has.
- [X] If possible, make a PR with a failing test to give us a starting point to work on!

### Describe the bug

I am running on a 4 GPU system (gorby). 

The `mgpu` backend should offload to an additional GPU once the memory threshold for the first GPU is reached. However this is not what I observe. See code snippet below and the error raised. 

```
import cudaq
from cudaq import spin
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt 

cudaq.set_qpu('cuquantum_mgpu')

n_qubits = 31
n_samples = 50
h = spin.z(0) 

n_parameters = n_qubits*3
parameters = np.random.default_rng(13).uniform(low=0, high=1, size = (n_samples,n_parameters))
np.random.seed(1)

kernel, params = cudaq.make_kernel(list)

qubits = kernel.qalloc(n_qubits)
qubits_list = list(range(n_qubits))

for i in range(n_qubits):
    kernel.rx(params[i], qubits[i])

for i in range(n_qubits):
    kernel.ry(params[i + n_qubits], qubits[i])

for i in range(n_qubits):
    kernel.rz(params[i + n_qubits*2], qubits[i])

for q1, q2 in zip(qubits_list[0::2], qubits_list[1::2]):
    kernel.cz(qubits[q1], qubits[q2])

exp_vals = [cudaq.observe(kernel, h, parameters[i]).expectation_z() for i in range(parameters.shape[0])]

```

```

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Cell In[8], line 1
----> 1 exp_vals = [cudaq.observe(kernel, h, parameters[i]).expectation_z() for i in range(parameters.shape[0])]

Cell In[8], line 1, in <listcomp>(.0)
----> 1 exp_vals = [cudaq.observe(kernel, h, parameters[i]).expectation_z() for i in range(parameters.shape[0])]

RuntimeError: [custatevec] %internal error in applyGate (line 399)
```

`n_qubits = 30` works fine on a single gpu but  `n_qubits = 31` throws up the error above. 

 

### Steps to reproduce the bug

NA

### Expected behavior

NA

### Is this a regression? If it is, put the last known working version (or commit) here.

Not a regression

### Environment

- **CUDA Quantum version**: 0.3.0
- **Python version**: 3.10.6
- **C++ compiler**: NA
- **Operating system**: Linux 

### Suggestions

NA

**Comment by bettinaheim** [comment]
I believe this has been fixed.

**Comment by bmhowe23** [comment]
I tested this on Gorby (after changing `cudaq.set_qpu('cuquantum_mgpu')` to `cudaq.set_target('nvidia-mgpu')` due to changes since this issue was originally written), and it successfully ran to completion, so I'm closing the issue.
