### ISSUE TITLE
Ability to perform state overlaps across GPU memory 

### ISSUE THREAD

**Issue by zohimchandani** [NVIDIA/cuda-quantum#1491]
### Required prerequisites

- [X] Search the [issue tracker](https://github.com/NVIDIA/cuda-quantum/issues) to check if your feature has already been mentioned or rejected in other issues.

### Describe the feature

@amccaskey has kindly worked on the ability to perform state overlaps that lie on single GPU memory. Can we please extend this so that the overlap function is able to extract states that lie across GPUs and nodes. 

This will be crucial for QSVM workflows moving forward. 

Thanks.

**Comment by bettinaheim** [comment]
Close as done with the revision to the state handling in 0.8
