### ISSUE TITLE
cudaq.draw drops the last few qubits if no operations on them

### ISSUE THREAD

**Issue by poojarao8** [NVIDIA/cuda-quantum#1501]
### Required prerequisites

- [X] Consult the [security policy](https://github.com/NVIDIA/cuda-quantum/security/policy). If reporting a security vulnerability, do not report the bug using this form. Use the process described in the policy to report the issue.
- [X] Make sure you've read the [documentation](https://nvidia.github.io/cuda-quantum/latest). Your issue may be addressed there.
- [X] Search the [issue tracker](https://github.com/NVIDIA/cuda-quantum/issues) to verify that this hasn't already been reported. +1 or comment there if it has.
- [ ] If possible, make a PR with a failing test to give us a starting point to work on!

### Describe the bug

If there are  5 qubits, and there are no operations done on q3 and q4, then the output it produces only includes q0, q1 and q2 drawings.

### Steps to reproduce the bug

```
import cudaq

@cudaq.kernel
def kernel(N: int):
    q = cudaq.qvector(N)
    h(q[0])
    ry(1.47, q[2])
    x.ctrl(q[1], q[0])
    mz(q)

print(cudaq.draw(kernel, 5))
```

### Expected behavior

Draw a straight line if there are no operations on a qubit.

### Is this a regression? If it is, put the last known working version (or commit) here.

Not a regression

### Environment

- **CUDA Quantum version**: 
- **Python version**: 
- **C++ compiler**: 
- **Operating system**:

**Comment by poojarao8** [comment]
Screenshot of the ouput:
<img width="316" alt="Screenshot 2024-04-11 at 9 51 42 PM" src="https://github.com/NVIDIA/cuda-quantum/assets/8114890/0fb5d3af-e627-4d1e-aad3-030ceda99e3c">

**Comment by bettinaheim** [comment]
I am inclined to close this as by design. Generally, I think the compiler should be free to run optimizations. If that is undesirable, then we'll add configuration options to disable optimization. Unused qubits, however, I think are generally fair to drop.
