### ISSUE TITLE
Add cudaq.draw() to documentation

### ISSUE THREAD

**Issue by efratshabtai** [NVIDIA/cuda-quantum#1545]
### Required prerequisites

- [X] Search the [issue tracker](https://github.com/NVIDIA/cuda-quantum/issues) to check if your feature has already been mentioned or rejected in other issues.

### Describe the feature

It will be nice to add cudaq.draw() to the basics section when people write their first program: https://nvidia.github.io/cuda-quantum/latest/using/basics/build_kernel.html and maybe some of the examples too.

**Comment by schweitzpgi** [comment]
@efratshabtai This is tagged for release 0.7.1 which is now in the rearview mirror. Was it completed? Please close or update the issue. Thanks in advance.

**Comment by efratshabtai** [comment]
I see that in the docs, will close.

**Comment by efratshabtai** [comment]
Was added to docs as part of 0.7.1
