### ISSUE TITLE
Support using complex numbers and lists in kernel functions

### ISSUE THREAD

**Issue by annagrin** [NVIDIA/cuda-quantum#1549]
### Required prerequisites

- [X] Search the [issue tracker](https://github.com/NVIDIA/cuda-quantum/issues) to check if your feature has already been mentioned or rejected in other issues.

### Describe the feature

This is a parent issue for supporting using complex numbers and lists in kernel functions.

The work is split up into the following parts:

- [x] Support complex numbers and lists of complex numbers defined inside, passed as parameters, or captured by kernel functions
  - https://github.com/NVIDIA/cuda-quantum/issues/1548
  - https://github.com/NVIDIA/cuda-quantum/pull/1550

- [ ] Support `np.complex` arrays defined inside, passed as parameters, or captured by kernel
  - https://github.com/NVIDIA/cuda-quantum/issues/1523

- [ ] Consider supporting half or quad precision complex and float numbers
  - TODO

- [x] Return complex numbers from kernel functions
  - https://github.com/NVIDIA/cuda-quantum/issues/1608
  - https://github.com/NVIDIA/cuda-quantum/pull/1610

**Comment by schweitzpgi** [comment]
@annagrin This one may be complete now too. Please close if warranted.

**Comment by bettinaheim** [comment]
Closing this as done, since np arrays are tracked separately.
