### ISSUE TITLE
Add qvector, qarray, and qview to the ASTBridge

### ISSUE THREAD

**Issue by amccaskey** [NVIDIA/cuda-quantum#162]
After #152 gets merged.

**Comment by amccaskey** [comment]
As a added task for this one, once these types are added to the bridge, please add a deprecated tag to qreg and qspan.

**Comment by schweitzpgi** [comment]
I believe this should be qvector, qarray, and qview. For the next release make sure the compiler generates an error message; we will not support these quite yet.

**Comment by schweitzpgi** [comment]
Error messages are produced for `qvector<>`, `qarray<c>`, and `qview<>`. (Setting the level value to `> 2` also causes error diagnostics, but a lot more of them.

**Comment by schweitzpgi** [comment]
Target release X for an implementation of these.
