### ISSUE TITLE
Organize Documentation Examples 

### ISSUE THREAD

**Issue by efratshabtai** [NVIDIA/cuda-quantum#1624]
### Required prerequisites

- [X] Search the [issue tracker](https://github.com/NVIDIA/cuda-quantum/issues) to check if your feature has already been mentioned or rejected in other issues.

### Describe the feature

Some of the pages under the CUDA-Q [Applications](https://nvidia.github.io/cuda-quantum/latest/using/tutorials.html) folder need to be organized and move to new locations:
1. The [Quantum Bits](https://nvidia.github.io/cuda-quantum/latest/examples/python/tutorials/quantum_bits.html) and [Multiple Qubits](https://nvidia.github.io/cuda-quantum/latest/examples/python/tutorials/multiple_qubits.html) pages need to be merged to one page starting with the content of the former and ending in the latter. The new page will be called 'Quantum Operations' and needs to be moved under [Examples](https://nvidia.github.io/cuda-quantum/latest/using/examples/examples.html), right after the [Introduction](https://nvidia.github.io/cuda-quantum/latest/using/examples/introduction.html) page.
2. The [Multi-GPU Workflows](https://nvidia.github.io/cuda-quantum/latest/examples/python/tutorials/multi_gpu_workflows.html) page Needs to move under [Examples](https://nvidia.github.io/cuda-quantum/latest/using/examples/examples.html) folder, right after [Multi-Control Synthesis](https://nvidia.github.io/cuda-quantum/latest/using/examples/multi_control.html).
3. [Executing Quantum Circuits](https://nvidia.github.io/cuda-quantum/latest/examples/python/tutorials/executing_circuits.html) should be merged with the 'Sample' and 'Observe' content in [Running your first CUDA-Q Program page](https://nvidia.github.io/cuda-quantum/latest/using/basics/run_kernel.html#) under Basics. 

Please note:

- The pages under the Applications folder were created from Jupyter notebooks while pages under Examples and Basics are generated from another format. Therefore, moving pages between these folders will require a format change of the original content. Specifically, a new .rst file needs to be created [here](https://github.com/NVIDIA/cuda-quantum/tree/main/docs/sphinx/using/examples), and the code cells need to be moved into separate Python/C++ files either under [snippets](https://github.com/NVIDIA/cuda-quantum/tree/main/docs/sphinx/snippets) (for small code blocks) or under [examples](https://github.com/NVIDIA/cuda-quantum/tree/main/docs/sphinx/examples) (for larger, more interesting code examples). To see how these code blocks are included in the rst file, take a look e.g. at [introduction.rst](https://raw.githubusercontent.com/NVIDIA/cuda-quantum/main/docs/sphinx/using/examples/introduction.rst).

- The content needs to be clear and helpful to all CUDA-Q users, so feel free to bring your own point of view.

**Comment by WingCode** [comment]
Commenting on the issue.

**Comment by bettinaheim** [comment]
> Commenting on the issue.

That worked. Thanks.
