### ISSUE TITLE
Readout Error Mitigation

### ISSUE THREAD

**Issue by justinlietz** [NVIDIA/cuda-quantum#1642]
### Required prerequisites

- [X] Search the [issue tracker](https://github.com/NVIDIA/cuda-quantum/issues) to check if your feature has already been mentioned or rejected in other issues.

### Describe the feature

# Background
Readout errors are caused by imperfect qubit measurement, and are a common source of error in quantum computing. Properly modeling these errors in simulation can give the user tools to better understand how these errors and how to mitigate them when running on actual quantum devices. 

There is a large body of work studying readout error, particularly in the context of how to mitigate it [[1](https://mitiq.readthedocs.io/en/stable/guide/rem-5-theory.html)], [[2](https://mitiq.readthedocs.io/en/stable/guide/rem-3-options.html)].

# Description
Develop a CUDA-Q application and apply readout error to the measurement results of a sampled CUDA-Q kernel. Next, perform readout error mitigation (REM) on those results. This application can be written in either C++ or Python.

The implementation should include two versions of both the measurement error and the subsequent measurement error mitigation: independent qubit measurement error model and full confusion matrix inversion.

# References
[1] https://mitiq.readthedocs.io/en/stable/guide/rem-5-theory.html
[2] https://mitiq.readthedocs.io/en/stable/guide/rem-3-options.html

**Comment by saanaz379** [comment]
Hello! I have started working on this for Unitary Hack, though I'd be down to collaborate if anyone else is also interested in working on this issue.

**Comment by Gopal-Dahale** [comment]
@justinlietz should this be added as a notebook in the [tutorials](https://github.com/NVIDIA/cuda-quantum/tree/main/docs/sphinx/examples/python/tutorials) directory?

**Comment by justinlietz** [comment]
> @justinlietz should this be added as a notebook in the [tutorials](https://github.com/NVIDIA/cuda-quantum/tree/main/docs/sphinx/examples/python/tutorials) directory?

Hi @Gopal-Dahale, that would be a perfectly acceptable form of submission. A script in [examples/python](https://github.com/NVIDIA/cuda-quantum/tree/main/docs/sphinx/examples/python) would also work if you prefer.
