### ISSUE TITLE
draw() : Python and C++ not doing the same for Euler's number

### ISSUE THREAD

**Issue by freifrauvonbleifrei** [NVIDIA/cuda-quantum#1734]
### Required prerequisites

- [X] Consult the [security policy](https://github.com/NVIDIA/cuda-quantum/security/policy). If reporting a security vulnerability, do not report the bug using this form. Use the process described in the policy to report the issue.
- [X] Make sure you've read the [documentation](https://nvidia.github.io/cuda-quantum/latest). Your issue may be addressed there.
- [X] Search the [issue tracker](https://github.com/NVIDIA/cuda-quantum/issues) to verify that this hasn't already been reported. +1 or comment there if it has.
- [ ] If possible, make a PR with a failing test to give us a starting point to work on!

### Describe the bug

As part of working on #1723, I wanted to mirror the `draw()` integration test in `draw_tester.cpp`:
https://github.com/NVIDIA/cuda-quantum/blob/1edc8a858e6f2edd754afb61b3439f733f52b251/unittests/integration/draw_tester.cpp#L21-L94

But I am having two problems here: 
  * First, I cannot find how to call the adjoint function to `rz`, used in kernel `bar`. The line `cudaq.adjoint(rz, np.pi, qvec[2])` throws a jit compilation error. Is this intended? There appears to be no `rzdg` function, and of course one can write a wrapper, but that would be a lot uglier than in C++ . So I hope there already is a good solution?
  * In the test code, if you comment the offending line (for adjoint `rz`, see above), then the `rx` gates on qubit 0 are not printed at all in the string output. They are displayed if I replace `np.e` by `np.pi`.

### Steps to reproduce the bug

https://github.com/freifrauvonbleifrei/cuda-quantum/blob/96d573106fee3edcaf7edfb6f7187cdf86181b7d/python/tests/display/test_draw.py#L15-L84

### Expected behavior

Python test should produce the same string representation of the kernel as the C++ test.

But! here is the failing assertion 
```
E       AssertionError: assert '     ╭───╮  ...           \n' == '     ╭───╮  ...           \n'
E         
E         Skipping 802 identical leading characters in diff, use -v to show
E           
E         - ╭───────╮             ╭─────╮              
E         - ┤>      ├─────────────┤ sdg ├──────────────
E         + ╭───────╮╭───────────╮    ╭─────╮   ╭────────────╮
E         + ┤>      ├┤ rx(2.718) ├────┤ sdg ├───┤ rx(-2.718) ├...
E         
E         ...Full output truncated (19 lines hidden), use '-vv' to show
```

### Is this a regression? If it is, put the last known working version (or commit) here.

Not a regression

### Environment

- **CUDA Quantum version**: 1c1d8de
- **Python version**: from dev container
- **C++ compiler**: from dev container
- **Operating system**: Ubuntu 22

### Suggestions

If I can get a hint on how to get the adjoint of `rz`, I'm going to open a PR for the test code as suggested.

**Comment by annagrin** [comment]
@freifrauvonbleifrei 
- `If I can get a hint on how to get the adjoint of rz,`

I think you are looking for `rz.adj(pi_f, q[2])`

- `They are displayed if I replace np.e by np.pi.`

Looks like `np.e` is not supported in kernel mode yet. If you would like to submit a PR, here is the place we support `np.pi`, should be very similar: https://github.com/NVIDIA/cuda-quantum/blob/2da801bc343a9cd5b62003e03cb24beb817b98c5/python/cudaq/kernel/ast_bridge.py#L1040

**Comment by schweitzpgi** [comment]
The `cudaq::adjoint(kernel, qubit)` operation will autocompute the adjoint of `kernel`. If `kernel` itself has adjoint operations, they'll be turned into the adjoint of the adjoint (the original).

That said, this kernel compiles for me:
```c++
#include <cudaq.h>

__qpu__ void k(void) {
        cudaq::qubit q;
        rz<cudaq::adj>(23.0, q);
}
e
```
with
```console
% nvq++ -c --enable-mlir test.cpp
```

**Comment by freifrauvonbleifrei** [comment]
Ah sorry, I believe I did not make this clear: I wanted to have an exact *Python* version of the test. I was able to fix this aspect through @annagrin's comment, and have submitted the PR #1756 to fix the constants resolution.
