### ISSUE TITLE
Link that points to info on cudaq images not working

### ISSUE THREAD

**Issue by poojarao8** [NVIDIA/cuda-quantum#1737]
### Required prerequisites

- [X] Consult the [security policy](https://github.com/NVIDIA/cuda-quantum/security/policy). If reporting a security vulnerability, do not report the bug using this form. Use the process described in the policy to report the issue.
- [X] Make sure you've read the [documentation](https://nvidia.github.io/cuda-quantum/latest). Your issue may be addressed there.
- [X] Search the [issue tracker](https://github.com/NVIDIA/cuda-quantum/issues) to verify that this hasn't already been reported. +1 or comment there if it has.
- [ ] If possible, make a PR with a failing test to give us a starting point to work on!

### Describe the bug

The quick start guide directs you to the following webpage for using theCUDA-Q docker image https://catalog.ngc.nvidia.com/orgs/nvidia/teams/quantum/containers/cuda-quantum. On this page, to get more information for pulling and running the container image, you are further directed to the documentation via a link. But that link points to https://www.nvidia.com/en-us/.

Other issues:
1. Usage of "CUDA Quantum" instead of CUDA-Q on the ngc webpage.
2. The CUDA-Q installation via the Docker image should have it's own heading in the quick install guide, otherwise even though it links to the ngc webpage, it is easy to miss. 

### Steps to reproduce the bug

Go to https://nvidia.github.io/cuda-quantum/latest/using/quick_start.html, click on "Docker image" ---> https://catalog.ngc.nvidia.com/orgs/nvidia/teams/quantum/containers/cuda-quantum.
 Under "Running CUDA Quantum", click on the link in "More detailed instructions for working with our container image, including alternative ways of pulling and running the container image, can be found in the [CUDA Quantum documentation](https://nvidia.github.io/cuda-quantum/latest/install.html)"

### Expected behavior

Fix the link to CUDA-Q documentation.

### Is this a regression? If it is, put the last known working version (or commit) here.

Not a regression

### Environment

CUDA-Q 0.8

**Comment by bettinaheim** [comment]
I updated the link.
