### ISSUE TITLE
Fix bugs in lowering to base profile [was: Counted loops from the ASTBridge]

### ISSUE THREAD

**Issue by amccaskey** [NVIDIA/cuda-quantum#179]
If I have the following 
```cpp
template <std::size_t N>
struct ghz {
  auto operator()() __qpu__ {.
    cudaq::qreg<N> q;
    h(q[0]);
    for (int i = 0; i < N - 1; i++) 
      x<cudaq::ctrl>(q[i], q[i + 1]);
    mz(q);
  }
};
```
the loop is technically a "counted" loop, but we don't tag it as such. This means that future loop unrolling can't happen. 

We need to update the ASTBridge to tag these types of expressions as "counted", or add a pass that will find them and update them.

**Comment by schweitzpgi** [comment]
Part of #98 was to add a mem2reg pass. Mem2reg on classical scalar values will simplify the loop analysis required. Once that is done, the loop unrolling pass won't need to rely on the annotation approach we're using as a stop gap at the moment.

**Comment by schweitzpgi** [comment]
I think this one is done. Do we need to add another test or anything?

**Comment by amccaskey** [comment]
We should ensure that https://github.com/NVIDIA/cuda-quantum/blob/main/docs/sphinx/examples/cpp/basics/static_kernel.cpp can lower to the base profile with the right pass flags.

**Comment by schweitzpgi** [comment]
> We should ensure that https://github.com/NVIDIA/cuda-quantum/blob/main/docs/sphinx/examples/cpp/basics/static_kernel.cpp can lower to the base profile with the right pass flags.

Well, it's close.
```console
[quake-translate] Dumping Module after error.
[quake-translate] Reported Error: see current operation: %34 = "llvm.call"(%33) {callee = @__quantum__qis__mz, fastmathFlags = #llvm.fastmath<none>} : (!llvm.ptr<struct<"Qubit", opaque>>) -> !llvm.ptr<struct<"Result", opaque>>
loc("static_kernel.qke.IG9gyU":33:11): error: could not trace offset value
cudaq-translate: /opt/clang-latest/include/llvm/Support/Casting.h:651: decltype(auto) llvm::dyn_cast(const From &) [To = mlir::IntegerAttr, From = mlir::Attribute]: Assertion `detail::isPresent(Val) && "dyn_cast on a non-existent value"' failed.
Aborted (core dumped)
```
Should we update the title of this? The issue isn't about loops here.

**Comment by schweitzpgi** [comment]
Revisit and drive to closure.

**Comment by bmhowe23** [comment]
I checked this in both `main` (796ba6c1) and `0.4.1`, and it is working correctly as far as I can tell. I think this issue can probably be closed.
