### ISSUE TITLE
sample result visualization as a histogram

### ISSUE THREAD

**Issue by mmvandieren** [NVIDIA/cuda-quantum#1858]
### Required prerequisites

- [X] Search the [issue tracker](https://github.com/NVIDIA/cuda-quantum/issues) to check if your feature has already been mentioned or rejected in other issues.

### Describe the feature

an option to plot a histogram of the sample results using matplotlib, for instance

**Comment by bettinaheim** [comment]
Closing since it is unclear what the ask is here. Matplotlib can be used to plot a histogram for sample results. Please reopen with more specifics if needed.
