### ISSUE TITLE
Run large qubits >34 simulation with multiple gpus

### ISSUE THREAD

**Issue by gzquse** [NVIDIA/cuda-quantum#1884]
### Required prerequisites

- [X] Consult the [security policy](https://github.com/NVIDIA/cuda-quantum/security/policy). If reporting a security vulnerability, do not report the bug using this form. Use the process described in the policy to report the issue.
- [X] Make sure you've read the [documentation](https://nvidia.github.io/cuda-quantum/latest). Your issue may be addressed there.
- [X] Search the [issue tracker](https://github.com/NVIDIA/cuda-quantum/issues) to verify that this hasn't already been reported. +1 or comment there if it has.
- [X] If possible, make a PR with a failing test to give us a starting point to work on!

### Describe the bug

If we run the circuit with over 33 qubits, it should be distributed to multiple gpus. 

Error:
```
# all GPUs parallel
terminate called after throwing an instance of 'std::runtime_error'
  what():  [custatevec] %out of memory in addQubitsToState (line 210)
terminate called after throwing an instance of 'std::runtime_error'
  what():  [custatevec] %out of memory in addQubitsToState (line 210)
terminate called after throwing an instance of 'std::runtime_error'
  what():  [custatevec] %out of memory in addQubitsToState (line 210)
terminate called after throwing an instance of 'std::runtime_error'
  what():  [custatevec] %out of memory in addQubitsToState (line 210)
  ```
  
  GPU memory:
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA A100-SXM...  Off  | 00000000:03:00.0 Off |                    0 |
| N/A   28C    P0    66W / 500W |      0MiB / 81920MiB |      0%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
|   1  NVIDIA A100-SXM...  Off  | 00000000:41:00.0 Off |                    0 |
| N/A   27C    P0    65W / 500W |      0MiB / 81920MiB |      0%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
|   2  NVIDIA A100-SXM...  Off  | 00000000:82:00.0 Off |                    0 |
| N/A   29C    P0    89W / 500W |      0MiB / 81920MiB |      0%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
|   3  NVIDIA A100-SXM...  Off  | 00000000:C1:00.0 Off |                    0 |
| N/A   27C    P0    69W / 500W |      0MiB / 81920MiB |      0%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
  ```

### Steps to reproduce the bug

run a circuit exceeding 33 qubits

### Expected behavior

See multiple gpus running 

### Is this a regression? If it is, put the last known working version (or commit) here.

Not a regression

### Environment

- **Operating system**: 
```
FROM ubuntu:22.04
ARG arch=x86_64

RUN apt-get update && apt-get install -y --no-install-recommends wget ca-certificates libstdc++-12-dev
RUN DISTRIBUTION=${DISTRIBUTION:-ubuntu2204} && \
  CUDA_ARCH_FOLDER=$([ "$(uname -m)" == "aarch64" ] && echo sbsa || echo x86_64) && \
  CUDA_DOWNLOAD_URL=https://developer.download.nvidia.com/compute/cuda/repos && \
  wget "${CUDA_DOWNLOAD_URL}/${DISTRIBUTION}/${CUDA_ARCH_FOLDER}/cuda-keyring_1.1-1_all.deb" && \
  dpkg -i cuda-keyring_1.1-1_all.deb && version_suffix=11-8 && \
  apt-get update && apt-get install -y --no-install-recommends \
    cuda-nvtx-${version_suffix} cuda-cudart-${version_suffix} \
    libcusolver-${version_suffix} libcublas-${version_suffix}

RUN apt-get install -y --no-install-recommends libmpich-dev
ENV MPI_PATH=/usr/lib/${arch}-linux-gnu/mpich

RUN apt-get install -y --no-install-recommends python3 python3-pip && \
  python3 -m pip install cuda-quantum
RUN cudaq_version=`python3 -c "import cudaq; print(cudaq.__version__)" | grep -o '[0-9]\+\(\.[0-9]\+\)\+'` && \
  wget https://github.com/NVIDIA/cuda-quantum/releases/download/${cudaq_version}/install_cuda_quantum.$(uname -m) && \
  chmod +x install_cuda_quantum.$(uname -m) && bash install_cuda_quantum.$(uname -m) --accept && \
  mkdir -p ~/cuda_quantum/tutorials && cd ~/cuda_quantum && tmpdir="$(mktemp -d)" && \
  wget https://github.com/nvidia/cuda-quantum/archive/refs/tags/${cudaq_version}.tar.gz && \
  tar xf ${cudaq_version}.tar.gz --strip-components 1 -C "${tmpdir}" && cp -Lr "${tmpdir}/examples" ~/cuda_quantum && \
  mv ~/cuda_quantum/examples/python/tutorials ~/cuda_quantum/tutorials && \
  rm -rf ${cudaq_version}.tar.gz "${tmpdir}" /install_cuda_quantum.$(uname -m)
RUN py_cudaq_dir="$(python3 -m pip show cuda-quantum | grep -e 'Location: .*$' | cut -d ' ' -f2)" && \
  CXX=/opt/nvidia/cudaq/bin/nvq++ bash "$py_cudaq_dir/distributed_interfaces/activate_custom_mpi.sh"

# Additional tools for development
RUN apt-get install -y --no-install-recommends vim jq libpython3-dev
RUN python3 -m pip install numpy matplotlib
RUN OMPI_CC="/opt/nvidia/cudaq/bin/clang" OMPI_CXX="/opt/nvidia/cudaq/bin/clang++" \
  python3 -m pip install mpi4py
```

### Suggestions

_No response_

**Comment by 1tnguyen** [comment]
Hi @gzquse 

To use the multi-GPU distributed state vector simulator, we need to set the target to `nvidia-mgpu`, e.g., via `cudaq.set_target` in Python.

Also, I saw that you installed `libmpich-dev` from `apt-get`. Please make sure that it has CUDA-aware MPI support as documented in the CUDA-Q Python package's [readme page](https://pypi.org/project/cuda-quantum/).

**Comment by gzquse** [comment]
Hi @1tnguyen ,

Thanks for the mention. I understand the setup needs cuda-aware MPI. 
May I ask if we have Python packages set up cause I only see the Conda Forge version which is suitable for Ubuntu 22.04 container? 

I will also double-check our HPC module to make sure.

Kind regards

**Comment by 1tnguyen** [comment]
> May I ask if we have Python packages set up cause I only see the Conda Forge version which is suitable for Ubuntu 22.04 container?

The instruction to install MPI from Conda Forge in the Python README is the most convenient way to install a CUDA-aware MPI. You could certainly install MPI in other ways as well, such as building from source like the [OpenMPI installation](https://github.com/NVIDIA/cuda-quantum/blob/main/docker/build/devdeps.ompi.Dockerfile) in the CUDA-Q Docker image.

Lastly, you could also use the CUDA-Q Docker image directly with Singularity, Podman, Shifter, etc., as described in the [docs](https://nvidia.github.io/cuda-quantum/latest/using/install/local_installation.html#singularity).

**Comment by gzquse** [comment]
Thanks so much! This is exactly what I am looking for:)
