### ISSUE TITLE
Sporadic CI failures on python tests

### ISSUE THREAD

**Issue by boschmitt** [NVIDIA/cuda-quantum#191]
The python tests seems to be failing every now and then. The following are examples of workflows that failed once and passed on a rerun without any code change:

- (failed `clang16`) https://github.com/NVIDIA/cuda-quantum/actions/runs/5068639533/jobs/9101246654?pr=190
- (failed `llvm`) https://github.com/NVIDIA/cuda-quantum/actions/runs/5069653639/jobs/9103651939

Note that those filed with different, but both llvm, toolchains. Also, the tests they are failing are different.

**Comment by amccaskey** [comment]
Just diagnosed this. It is a poorly designed test on my part. The random angle range is too broad, and can lead to angles close to zero, so the state does not rotate much leading to a high probability that the sample result is close to 00 or 11. 

@anthony-santana @schweitzpgi  for viz

**Comment by amccaskey** [comment]
Could not reproduce the bug in https://github.com/NVIDIA/cuda-quantum/actions/runs/5069653639/jobs/9103651939. 

Let's wait and see if it pops up again.
