### ISSUE TITLE
Install to Mac M1

### ISSUE THREAD

**Issue by ksk0629** [NVIDIA/cuda-quantum#2065]
### Required prerequisites

- [X] Consult the [security policy](https://github.com/NVIDIA/cuda-quantum/security/policy). If reporting a security vulnerability, do not report the bug using this form. Use the process described in the policy to report the issue.
- [X] Make sure you've read the [documentation](https://nvidia.github.io/cuda-quantum/latest). Your issue may be addressed there.
- [X] Search the [issue tracker](https://github.com/NVIDIA/cuda-quantum/issues) to verify that this hasn't already been reported. +1 or comment there if it has.
- [ ] If possible, make a PR with a failing test to give us a starting point to work on!

### Describe the bug

I have faced the following error by running the command `conda install -y -n cuda-quantum -c "nvidia/label/cuda-11.8.0" cuda`.

```
% conda install -y -n cuda-quantum -c "nvidia/label/cuda-11.8.0" cuda
Channels:
 - nvidia/label/cuda-11.8.0
 - conda-forge
Platform: osx-arm64
Collecting package metadata (repodata.json): done
Solving environment: failed

LibMambaUnsatisfiableError: Encountered problems while solving:
  - nothing provides __win needed by cuda-12.0.0-h7428d3b_0

Could not solve for environment specs
The following packages are incompatible
└─ cuda is not installable because there are no viable options
   ├─ cuda [12.0.0|12.1.1|...|12.6.0] would require
   │  └─ __win, which is missing on the system;
   └─ cuda [12.0.0|12.1.1|...|12.6.0] would require
      └─ __linux, which is missing on the system.
```

I obviously just followed Quick Start. 

### Steps to reproduce the bug

Run the following commands.

1. conda create -y -n cuda-quantum python=3.10 pip
2. conda install -y -n cuda-quantum -c "nvidia/label/cuda-11.8.0" cuda

### Expected behavior

Successfully installed.

### Is this a regression? If it is, put the last known working version (or commit) here.

Not a regression

### Environment

- **CUDA Quantum version**: N/A
- **Python version**: 3.10
- **Operating system**: Mac M1

**Comment by 1tnguyen** [comment]
Hi @ksk0629,

Currently, [local installation](https://nvidia.github.io/cuda-quantum/latest/using/install/local_installation.html#id10) of CUDA-Q Python wheels is only supported for Linux operation systems.  

For Mac, you could use CUDA-Q [Docker images](https://nvidia.github.io/cuda-quantum/latest/using/install/local_installation.html#docker).

**Comment by ksk0629** [comment]
Hi @1tnguyen ,
Thank you for the response. I got it. I will use the docker image.

**Comment by natestemen** [comment]
We (@bdg221, @ACE07-Sev and myself) are running in to the same issue as in #3307 (installing cudaq in a fresh environment on mac). Is it still expected that you need to use a docker image? I don't see that recommendation on the [install docs](https://nvidia.github.io/cuda-quantum/latest/using/quick_start.html#install-cuda-q).

If this is unexpected, happy to open a new issue.

**Comment by bmhowe23** [comment]
Hi @natestemen. If you are trying to use the wheels, the supported platforms are documented on the [PyPI page](https://pypi.org/project/cuda-quantum-cu12/). E.g.

> Note: CUDA-Q is currently only supported on Linux operating systems using x86_64 or aarch64/arm64 processors.

If you are trying to use something else, let us know, but Docker (or Singularity) is the main path for Mac. The other generally supported path other than Docker is building from source (documented [here](https://nvidia.github.io/cuda-quantum/latest/using/install/data_center_install.html)), but that one says that Linux is the only supported path (or Windows+WSL):

> The following pre-requisites need to be satisfied both on the build system and on the host system, that is the system where the built CUDA-Q binaries will be installed and used.
> * Linux operating system. The instructions in this guide have been validated with the [AlmaLinux 8 image](https://hub.docker.com/u/almalinux) that serves as the base image for the [manylinux_2_28 image](https://github.com/pypa/manylinux), and should work for the operating systems CentOS 8, Debian 11 and 12, Fedora 41, OpenSUSE/SLED/SLES 15.5 and 15.6, RHEL 8 and 9, Rocky 8 and 9, Ubuntu 24.04 and 22.04. Other operating systems may work, but have not been tested.

Please feel free to open a new feature request issue to request it in on Mac, but that would probably be a non-trivial thing to add.
