### ISSUE TITLE
typos in State documentation (missing parentheses in the Python code)

### ISSUE THREAD

**Issue by mmvandieren** [NVIDIA/cuda-quantum#2104]
### Required prerequisites

- [X] Consult the [security policy](https://github.com/NVIDIA/cuda-quantum/security/policy). If reporting a security vulnerability, do not report the bug using this form. Use the process described in the policy to report the issue.
- [X] Make sure you've read the [documentation](https://nvidia.github.io/cuda-quantum/latest). Your issue may be addressed there.
- [X] Search the [issue tracker](https://github.com/NVIDIA/cuda-quantum/issues) to verify that this hasn't already been reported. +1 or comment there if it has.
- [ ] If possible, make a PR with a failing test to give us a starting point to work on!

### Describe the bug

The `State` [documentation example code blocks](https://nvidia.github.io/cuda-quantum/latest/api/languages/python_api.html#cudaq.State), do not have closing parentheses in the last line of each of the 4 code blocks.  I couldn't find the folder in GitHub for these files to fix.

The state amplitudes example seems to also be missing a closing square bracket

![Screenshot 2024-08-19 at 4 04 32 PM](https://github.com/user-attachments/assets/cc7a7e73-3997-44d8-9c77-46b92b97820f)

### Steps to reproduce the bug

check site https://nvidia.github.io/cuda-quantum/latest/api/languages/python_api.html#cudaq.State

### Expected behavior

expected to see closing parentheses

### Is this a regression? If it is, put the last known working version (or commit) here.

Not a regression

### Environment

- **CUDA Quantum version**: 0.8
- **Python version**: 
- **C++ compiler**: 
- **Operating system**:

**Comment by 1tnguyen** [comment]
@mmvandieren Thanks for spotting this.

>  I couldn't find the folder in GitHub for these files to fix.

This API doc is generated by the code in this [py_state.cpp file](https://github.com/NVIDIA/cuda-quantum/blob/main/python/runtime/cudaq/algorithms/py_state.cpp) 

e.g., https://github.com/NVIDIA/cuda-quantum/blob/37474b2765e27ba055baa367bc331f2fc585eecc/python/runtime/cudaq/algorithms/py_state.cpp#L437-L445

Please let me know if you're interested in fixing them :)

**Comment by 1tnguyen** [comment]
> @1tnguyen I took a look, but I don't know how to fix them because I'm not sure how that #" is working in the documentation generation

The `#(` and `)#` are like special quotation marks in this case. Hence, we just need to add one more `)` before the end, I believe.
We have the CI pipeline to generate the docs for checking as well.

**Comment by mmvandieren** [comment]
OK I'll try to fix it then.

**Comment by 1tnguyen** [comment]
Fixed in https://github.com/NVIDIA/cuda-quantum/pull/2108
