### ISSUE TITLE
Ctest fails on Vscode builds

### ISSUE THREAD

**Issue by chichieinstein** [NVIDIA/cuda-quantum#2116]
### Required prerequisites

- [X] Consult the [security policy](https://github.com/NVIDIA/cuda-quantum/security/policy). If reporting a security vulnerability, do not report the bug using this form. Use the process described in the policy to report the issue.
- [X] Make sure you've read the [documentation](https://nvidia.github.io/cuda-quantum/latest). Your issue may be addressed there.
- [X] Search the [issue tracker](https://github.com/NVIDIA/cuda-quantum/issues) to verify that this hasn't already been reported. +1 or comment there if it has.
- [ ] If possible, make a PR with a failing test to give us a starting point to work on!

### Describe the bug

Hello everyone! First time posting here as I just started playing around with CUDA-Q. I opened the codebase in VSCode, and let it build itself. Then, on running ctest in the build folder, a number of the tests fail. Examination of the log shows that the following errors (among others) were faced during the test:

- the `build/bin/cudaq-target-conf` folder is missing.
- Unable to find executable: test_runtime_qpp_NOT_BUILT
- Unable to find executable : test_runtime_custatevec-fp32_NOT_BUILT

Did I miss any steps in the build process?

### Steps to reproduce the bug

These are the steps I took, [following the instructions here](https://github.com/NVIDIA/cuda-quantum/blob/main/Dev_Setup.md)
- Clone the repo
- Open the repo in VSCode
- Use VSCode docker extension to build and open the repo inside a running container
- Go to build folder and run the command `ctest`.

### Expected behavior

All tests should pass

### Is this a regression? If it is, put the last known working version (or commit) here.

Not a regression

### Environment

- **CUDA Quantum version**: 0.8.0
- **Python version**: 3.10.12
- **C++ compiler**: g++ version 11.4
- **Operating system**: Ubuntu 22.04

The development container was built using VSCode.

**Comment by chichieinstein** [comment]
Hey @sacpis actually I did try to build and install from source following the link instructions. I was getting compiler errors, which is why I decided to switch to the VSCode based development container.

**Comment by chichieinstein** [comment]
To summarize, 

- if I use the `devcontainer.json` and let VSCode build the project using the VSCode docker extension, I am able to build and install cudaq locally. However, `ctest` fails in the build folder.

- if I use the startup script approach, as [summarized here](https://nvidia.github.io/cuda-quantum/latest/using/install/data_center_install.html), I am unable to build and install locally. I get the following compiler error
```
FAILED: lib/libcudaq-common.so 
: && /usr/local/llvm/bin/clang++ -fPIC -fPIC -fno-semantic-interposition -fvisibility-inlines-hidden -Werror=date-time -Werror=unguarded-availability-new -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-field-initializers -Wimplicit-fallthrough -Wcovered-switch-default -Wno-noexcept-type -Wnon-virtual-dtor -Wdelete-non-virtual-dtor -Wsuggest-override -Wno-comment -Wstring-conversion -Wmisleading-indentation -Wctad-maybe-unsupported -fdiagnostics-color -ffunction-sections -fdata-sections -O3 -DNDEBUG  -static-libstdc++ -static-libgcc -Wl,-z,defs -Wl,-z,nodelete -Wl,--color-diagnostics -shared -Wl,-soname,libcudaq-common.so -o lib/libcudaq-common.so runtime/common/CMakeFiles/cudaq-common.dir/Environment.cpp.o runtime/common/CMakeFiles/cudaq-common.dir/Executor.cpp.o runtime/common/CMakeFiles/cudaq-common.dir/Future.cpp.o runtime/common/CMakeFiles/cudaq-common.dir/Logger.cpp.o runtime/common/CMakeFiles/cudaq-common.dir/MeasureCounts.cpp.o runtime/common/CMakeFiles/cudaq-common.dir/NoiseModel.cpp.o runtime/common/CMakeFiles/cudaq-common.dir/Resources.cpp.o runtime/common/CMakeFiles/cudaq-common.dir/ServerHelper.cpp.o runtime/common/CMakeFiles/cudaq-common.dir/Trace.cpp.o  -Wl,-rpath,"\$ORIGIN:\$ORIGIN/lib:\$ORIGIN/lib/plugins:\$ORIGIN/../lib:\$ORIGIN/../lib/plugins"  lib/libcudaq-spin.so  tpls/spdlog/libspdlog.a  tpls/fmt/libfmt.a && :
ld.lld: error: undefined symbol: cudaq::RestClient::post(std::__1::basic_string_view<char, std::__1::char_traits<char>>, std::__1::basic_string_view<char, std::__1::char_traits<char>>, nlohmann::json_v3_11_1::basic_json<std::__1::map, std::__1::vector, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, bool, long, unsigned long, double, std::__1::allocator, nlohmann::json_v3_11_1::adl_serializer, std::__1::vector<unsigned char, std::__1::allocator<unsigned char>>>&, std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>>>&, bool, bool)
>>> referenced by Executor.cpp
>>>               runtime/common/CMakeFiles/cudaq-common.dir/Executor.cpp.o:(cudaq::Executor::execute(std::__1::vector<cudaq::KernelExecution, std::__1::allocator<cudaq::KernelExecution>>&))
clang-16: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by bmhowe23** [comment]
> I opened the codebase in VSCode, and let it build itself.

Hi @chichieinstein - VS Code will build a container for you, but it will not build the CUDA-Q binaries, so what precise commands are you using to build CUDA-Q once the container is created? I think the ones that @sacpis provided (`bash scripts/build_cuda.sh -v`) should work. The "Installation from Source" instructions are not intended to be used inside the development container.

**Comment by chichieinstein** [comment]
Hi @bmhowe23 

- I see. When VSCode builds the container, I see it creating a build folder and writing files to this folder, with CMake outputs written to the console and therefore assumed that it was also building CUDA-Q in addition to building the container. Let me try firing up the startup script in VSCode.

- I do follow the build from source instructions outside the VSCode development container.
