### ISSUE TITLE
FromAsCasing error in docker files

### ISSUE THREAD

**Issue by sacpis** [NVIDIA/cuda-quantum#2118]
### Required prerequisites

- [X] Consult the [security policy](https://github.com/NVIDIA/cuda-quantum/security/policy). If reporting a security vulnerability, do not report the bug using this form. Use the process described in the policy to report the issue.
- [X] Make sure you've read the [documentation](https://nvidia.github.io/cuda-quantum/latest). Your issue may be addressed there.
- [X] Search the [issue tracker](https://github.com/NVIDIA/cuda-quantum/issues) to verify that this hasn't already been reported. +1 or comment there if it has.
- [X] If possible, make a PR with a failing test to give us a starting point to work on!

### Describe the bug

FromAsCasing error in docker files
https://github.com/NVIDIA/cuda-quantum/actions/runs/10482216088/job/29034429465?pr=1844

### Steps to reproduce the bug

Kicked off a build for a PR and got this error

 1 warning found (use docker --debug to expand):
 - FromAsCasing: 'as' and 'FROM' keywords' casing do not match (line 13)
linux.Dockerfile:13

### Expected behavior

Build should succeed

### Is this a regression? If it is, put the last known working version (or commit) here.

Not a regression

### Environment

- **CUDA Quantum version**: 
- **Python version**: 
- **C++ compiler**: 
- **Operating system**:

**Comment by bmhowe23** [comment]
This is just a warning, right? I don't think it prevents it from building, does it? As far as I can tell, the true error in the linked run was this: `ERROR: failed to solve: ghcr.io/nvidia/amd64/almalinux:8: failed to resolve source metadata for ghcr.io/nvidia/amd64/almalinux:8: failed to copy: httpReadSeeker: failed open: content at `...

(I'm still ok with making a change to eliminate the warning; I just wanted to double check that I understood the situation.)
