### ISSUE TITLE
Output from `sample` should be ordered

### ISSUE THREAD

**Issue by zohimchandani** [NVIDIA/cuda-quantum#2158]
### Required prerequisites

- [x] Search the [issue tracker](https://github.com/NVIDIA/cuda-quantum/issues) to check if your feature has already been mentioned or rejected in other issues.

### Describe the feature

```
@cudaq.kernel 
def psi(): 
    qubits = cudaq.qvector(3)
    
    h(qubits[0])
    h(qubits[1])
    h(qubits[2])
    

counts = cudaq.sample(psi)
print(counts)
```

```
{ 110:144 101:121 100:131 011:103 001:132 111:118 010:129 000:122 }

```

Can the output be ordered according to binary notation of quantum states ie: 

0 = 000 = 2**2 * 0 + 2**1 * 0 + 2**0 * 0 = 0 
1 = 001 
2 = 010 
3 = 011

etc

**Comment by ikkoham** [comment]
Sorting of exponential sized data is costly and is not recommended to be sorted all the time.
It may be optional, but can be easily implemented as follows

```python
import cudaq

@cudaq.kernel 
def psi(): 
    qubits = cudaq.qvector(3)
    
    h(qubits[0])
    h(qubits[1])
    h(qubits[2])

counts = cudaq.sample(psi)
sorted_counts = sorted(counts.items(), key=lambda x:x[0])
print(sorted_counts)
```
`[('000', 131), ('001', 129), ('010', 105), ('011', 139), ('100', 139), ('101', 107), ('110', 131), ('111', 119)]`

or

```python
import cudaq

@cudaq.kernel 
def psi(): 
    qubits = cudaq.qvector(3)
    
    h(qubits[0])
    h(qubits[1])
    h(qubits[2])

counts = cudaq.sample(psi)
sorted_counts = sorted(counts.items(), key=lambda x:x[0][::-1])
print(sorted_counts)
```
`[('000', 140), ('100', 123), ('010', 114), ('110', 119), ('001', 135), ('101', 137), ('011', 117), ('111', 115)]`

**Comment by bmhowe23** [comment]
While sorting can be expensive, I suspect the actual conversion to strings and dumping to consoles and/or files will dominate the runtime. I think the sorting can be done a little bit cheaper than the above recommendation in Python; #2275 includes a fix that does the sort by iterators, so no additional copies are needed.
