### ISSUE TITLE
Translation to openqasm2 is missing a few optimizations

### ISSUE THREAD

**Issue by annagrin** [NVIDIA/cuda-quantum#2176]
### Required prerequisites

- [x] Consult the [security policy](https://github.com/NVIDIA/cuda-quantum/security/policy). If reporting a security vulnerability, do not report the bug using this form. Use the process described in the policy to report the issue.
- [x] Make sure you've read the [documentation](https://nvidia.github.io/cuda-quantum/latest). Your issue may be addressed there.
- [x] Search the [issue tracker](https://github.com/NVIDIA/cuda-quantum/issues) to verify that this hasn't already been reported. +1 or comment there if it has.
- [ ] If possible, make a PR with a failing test to give us a starting point to work on!

### Describe the bug

See example and answer in: https://github.com/NVIDIA/cuda-quantum/discussions/2005

Optimizations to add:
```
cudaq-quake iqm_simple.cpp | cudaq-opt --pass-pipeline="builtin.module(func.func(memtoreg{quantum=0}),cc-loop-unroll)" | cudaq-translate --convert-to=openqasm2
```

### Steps to reproduce the bug

```cpp
#include <cudaq.h>
#include <fstream>

struct adonis_kernel {
  void operator()() __qpu__ {
    cudaq::qvector q(5);
    x(q[0]);

    for (int i = 0; i < 4; i++) {
      x<cudaq::ctrl>(q[i], q[i + 1]);
    }
    x<cudaq::ctrl>(q[0], q[2], q[1]);
    auto result = mz(q);
  }
};

int main() {
  // auto counts = cudaq::sample(adonis_kernel{});
  // counts.dump();
}
```

### Expected behavior

The following command fails:

```
cudaq-quake iqm_simple.cpp  | cudaq-translate --convert-to=openqasm2
```

### Is this a regression? If it is, put the last known working version (or commit) here.

Not a regression

### Environment

- **CUDA Quantum version**: 
- **Python version**: 
- **C++ compiler**: 
- **Operating system**: 

### Suggestions

Add `mem-to-reg` and `loop-unroll` optimizations to `addPipelineTranslateToOpenQASM`

**Comment by schweitzpgi** [comment]
You'll want to run loop normalization before loop unrolling.
