### ISSUE TITLE
FuseWithConstantArray on ExtractValueOp always returns success()

### ISSUE THREAD

**Issue by amccaskey** [NVIDIA/cuda-quantum#2196]
`FuseWithConstantArray::matchAndRewrite` is returning success even if no canonicalization is applied. I'm not 100% sure, but I think that final return statement should be a `return failure();`. I noticed this when I tried to add more canonicalization patterns for `ExtractValueOp` and they would not run, and my guess was that it was because the first pass, `FuseWithConstantArray` was always returning success.

**Comment by schweitzpgi** [comment]
Closing. Should be fixed.
