### ISSUE TITLE
Noise modelling 

### ISSUE THREAD

**Issue by zohimchandani** [NVIDIA/cuda-quantum#223]
### Required prerequisites

- [X] Search the [issue tracker](https://github.com/NVIDIA/cuda-quantum/issues) to check if your feature has already been mentioned or rejected in other issues.

### Describe the feature

The code snippet below is what we support now and is a little tedious: 

```
cudaq.set_qpu('dm')

circuit = cudaq.make_kernel()
q = circuit.qalloc(2)
circuit.x(q[0])
circuit.x(q[1])

depol = cudaq.DepolarizationChannel(0.5)
noise = cudaq.NoiseModel()
noise.add_channel("x", [0], depol)
noise.add_channel("x", [1], depol)

counts = cudaq.sample(circuit, noise_model=noise, shots_count=100)
```

Instead of 

```
noise.add_channel("x", [0], depol)
noise.add_channel("x", [1], depol)
```

can we please support 

```
noise.add_channel("x", [0,1], depol)
```

Thanks

**Comment by amccaskey** [comment]
I don't think this will be possible - the latter is ambiguous for the CUDA Quantum programming model. Because we primarily consider single qubit operations that are then modified to synthesize controlled operations, your suggested syntax cannot be disambiguated from a single op x on qubits 0 and 1, or the operation x controlled on 0 targeting 1.

**Comment by snsunx** [comment]
Is noisy simulation not yet supported with the cuStateVec backend? I noticed that the `CuStateVecCircuitSimulator` class in `runtime/nvqir/custatevec/CuStateVecCircuitSimulator.cu` does not have `applyNoiseChannel` implemented.

**Comment by bettinaheim** [comment]
> Is noisy simulation not yet supported with the cuStateVec backend? I noticed that the `CuStateVecCircuitSimulator` class in `runtime/nvqir/custatevec/CuStateVecCircuitSimulator.cu` does not have `applyNoiseChannel` implemented.

Not yet, but we are looking into options. I'll close this as that work will be tracked separately.
