### ISSUE TITLE
CUDA-Q kernels can NOT serve as input to other quantum kernels and invoked by kernel function

### ISSUE THREAD

**Issue by ikkoham** [NVIDIA/cuda-quantum#2282]
### Required prerequisites

- [x] Consult the [security policy](https://github.com/NVIDIA/cuda-quantum/security/policy). If reporting a security vulnerability, do not report the bug using this form. Use the process described in the policy to report the issue.
- [x] Make sure you've read the [documentation](https://nvidia.github.io/cuda-quantum/latest). Your issue may be addressed there.
- [x] Search the [issue tracker](https://github.com/NVIDIA/cuda-quantum/issues) to verify that this hasn't already been reported. +1 or comment there if it has.
- [x] If possible, make a PR with a failing test to give us a starting point to work on!

### Describe the bug

The example code in https://nvidia.github.io/cuda-quantum/latest/specification/cudaq/kernels.html does not work.

[10] CUDA-Q kernels can serve as input to other quantum kernels and invoked by kernel function body code. To support CUDA-Q kernel parameterization on callable quantum kernel code, programmers can leverage standard C++ template definitions or dynamic typing in language bindings such as Python:

```python
@cudaq.kernel()
def MyStatePrep(qubits : cudaq.qview):
    ... apply state prep operations on qubits ...

@cudaq.kernel()
def MyGenericAlgorithm(statePrep : typing.Callable[[cudaq.qview], None]):
    q = cudaq.qvector(10)
    statePrep(q)
    ...

MyGenericAlgorithm(MyStatePrep)
```

### Steps to reproduce the bug

It raises `AttributeError: 'Attribute' object has no attribute 'id'`

### Expected behavior

Work

### Is this a regression? If it is, put the last known working version (or commit) here.

Not sure

### Environment

- **CUDA Quantum version**: 0.8.0
- **Python version**: Python 3.10.12 (in CUDA-Q docker container)
- **C++ compiler**: 
- **Operating system**:

**Comment by amccaskey** [comment]
This is a simple bug in parsing the `typing.Callable` string in the argument type annotation. If you instead import as 
```python
from typing import Callable
```
and then remove `typing.`
```python 
def MyGenericAlgorithm(statePrep : Callable[[cudaq.qview], None]):
```
it should work. Still you should be able to keep the `typing.` and it should work. We'll have to get a fix in for that.

**Comment by ikkoham** [comment]
Thank you for quick response. I confirmed that your suggestion works well!

**Comment by schweitzpgi** [comment]
Is there anything else to do here? Re-open if so.
