### ISSUE TITLE
Unexpected behavior with list[bool] for argument of kernel

### ISSUE THREAD

**Issue by ikkoham** [NVIDIA/cuda-quantum#2330]
### Required prerequisites

- [x] Consult the [security policy](https://github.com/NVIDIA/cuda-quantum/security/policy). If reporting a security vulnerability, do not report the bug using this form. Use the process described in the policy to report the issue.
- [x] Make sure you've read the [documentation](https://nvidia.github.io/cuda-quantum/latest). Your issue may be addressed there.
- [x] Search the [issue tracker](https://github.com/NVIDIA/cuda-quantum/issues) to verify that this hasn't already been reported. +1 or comment there if it has.
- [x] If possible, make a PR with a failing test to give us a starting point to work on!

### Describe the bug

Unexpected behavior when using enumerate to create kernel.
Detail is below.

### Steps to reproduce the bug

```python
import cudaq
import itertools

@cudaq.kernel
def test(num_qubits: int, mask: list[bool]):
    q = cudaq.qvector(num_qubits)
    for i, m in enumerate(mask):
        if m:
            x(q[i])
    mz(q)
    
num_qubits = 3
for mask in itertools.product((True, False), repeat=num_qubits):
    print(mask)
    print(cudaq.sample(test, num_qubits, list(mask)))
```
outputs
```
(True, True, True)
{ 000:1000 }

(True, True, False)
{ 000:1000 }

(True, False, True)
{ 000:1000 }

(True, False, False)
{ 100:1000 }

(False, True, True)
{ 000:1000 }

(False, True, False)
{ 000:1000 }

(False, False, True)
{ 000:1000 }

(False, False, False)
{ 000:1000 }
```

Only the case (True, False, False) is correct.

### Expected behavior

Should return the correct bit string

### Is this a regression? If it is, put the last known working version (or commit) here.

Not a regression

### Environment

- **CUDA Quantum version**: 0.8.0
- **Python version**: 
- **C++ compiler**: 
- **Operating system**:

**Comment by ikkoham** [comment]
hmm, this may not be the problem of `enumerate`.

```python
import cudaq
import itertools

@cudaq.kernel
def test(num_qubits: int, mask: list[bool]):
    q = cudaq.qvector(num_qubits)
    for i in range(num_qubits):
        if mask[i]:
            x(q[i])
    mz(q)
    
num_qubits = 3
for mask in itertools.product((True, False), repeat=num_qubits):
    print(list(mask))
    print(cudaq.sample(test, num_qubits, list(mask)))
```
outputs the same

**Comment by ikkoham** [comment]
This is the bug of `list[bool]`.

```python
import cudaq
import itertools

@cudaq.kernel
def test(num_qubits: int, mask: list[int]):
    q = cudaq.qvector(num_qubits)
    for i in range(num_qubits):
        if mask[i]:
            x(q[i])
    mz(q)
    
num_qubits = 4
for mask in itertools.product((1, 0), repeat=num_qubits):
    print(list(mask))
    print(cudaq.sample(test, num_qubits, list(mask)))
```
works as expected.

**Comment by ikkoham** [comment]
```python
import cudaq
import itertools

@cudaq.kernel
def test(num_qubits: int, mask: list[int]):
    q = cudaq.qvector(num_qubits)
    for i, m in enumerate(mask):
        if m:
            x(q[i])
    mz(q)
    
num_qubits = 4
for mask in itertools.product((1, 0), repeat=num_qubits):
    print(list(mask))
    print(cudaq.sample(test, num_qubits, list(mask)))
```
is ok

**Comment by bebora** [comment]
This is likely the same problem as the one reported in #2262.

**Comment by schweitzpgi** [comment]
#2338 fixes a number of bugs with arguments, etc.

**Comment by schweitzpgi** [comment]
Fixed.
