### ISSUE TITLE
VQE run keeps going despite ctrl^c 

### ISSUE THREAD

**Issue by poojarao8** [NVIDIA/cuda-quantum#244]
### Required prerequisites

- [X] Make sure you've read the [documentation](https://nvidia.github.io/cuda-quantum/latest). Your issue may be addressed there.
- [X] Search the [issue tracker](https://github.com/NVIDIA/cuda-quantum/issues) to verify that this hasn't already been reported. +1 or comment there if it has.
- [X] If possible, make a PR with a failing test to give us a starting point to work on!

### Describe the bug

For the vqe runs (both cpp and python), the program keeps going even after hitting ctrl^c. It keeps printing the optimal values and moving along. Usually, I have to cancel the process explicitly to get around this issue. 

The runs I have done are 8 qubits and higher, not sure how it behaves for smaller #qubits (H2 is 4 qubits and simpler and that seems fine). I have been noticing this for a while, so it's not due to any recent changes.

### Steps to reproduce the bug

#include "cudaq/algorithm.h"
#include "cudaq/domains/chemistry.h"
#include "cudaq/optimizers.h"

int main() {

    cudaq::molecular_geometry geometry{
        {"Li", {0.0, 0.0, 0.0}},
        {"H", {0.0, 0.0, 0.9}}
    };

    auto molecule = cudaq::create_molecule(geometry, "sto-3g", 1, 0);

    auto ansatz = [&](std::vector<double> thetas) __qpu__ {
      cudaq::qreg q(2 * molecule.n_orbitals);
      cudaq::uccsd(q, thetas, molecule.n_electrons);
    };

    cudaq::optimizers::cobyla optimizer;
    auto res = cudaq::vqe(ansatz, molecule.hamiltonian, optimizer,
                          cudaq::uccsd_num_parameters(molecule.n_electrons,
                                                      2 * molecule.n_orbitals));

}

### Expected behavior

The program should quit running after hitting ctrl^c

### Is this a regression? If it is, put the last known working version (or commit) here.

Not a regression

### Environment

- **CUDA Quantum version**: 
Tested with commit 7303ca2b6e4e3360fcb3acc8225eaca96fcf398b

### Suggestions

Here is a possible solution I found: https://stackoverflow.com/questions/14707049/allowing-ctrl-c-to-interrupt-a-python-c-extension.

**Comment by 1tnguyen** [comment]
@amccaskey Did https://github.com/NVIDIA/cuda-quantum/pull/495 fix this issue?

> Implement global SIGINT handler to catch CTRL-C better and quit the program.

**Comment by bettinaheim** [comment]
I quickly double checked and it looks like this is indeed fixed.
