### ISSUE TITLE
Driver wrongly reporting argument as ignored

### ISSUE THREAD

**Issue by boschmitt** [NVIDIA/cuda-quantum#258]
### Required prerequisites

- [X] Make sure you've read the [documentation](https://nvidia.github.io/cuda-quantum/latest). Your issue may be addressed there.
- [X] Search the [issue tracker](https://github.com/NVIDIA/cuda-quantum/issues) to verify that this hasn't already been reported. +1 or comment there if it has.
- [ ] If possible, make a PR with a failing test to give us a starting point to work on!

### Describe the bug

The nvq++ driver wrongly reports arguments as ignored. The problem is that this argument is not handle by the driver script, `nvq++`, but by the scripts which configure the target, `<install_dir>/targets/quantinuum.config`. 

### Steps to reproduce the bug

```console
# bin/nvq++ qubit.cpp -o qubit.x --target quantinuum --quantinuum-url http://localhost:62454
argument --quantinuum-url is ignored
argument http://error:62454 is ignored
```

### Expected behavior

Do not report the argument as being ignored.

### Is this a regression? If it is, put the last known working version (or commit) here.

Not a regression

### Environment

- **CUDA Quantum version**: main
- **C++ compiler**: gcc-12
- **Operating system**: Ubuntu (AArch64)

**Comment by schweitzpgi** [comment]
The mechanism for handling target command line options is very odd, IMHO. Why are all the options forwarded? Why does the secondary script need them? Why should it sift through all the chaff?

**Comment by amccaskey** [comment]
We just need to be able to have target backends expose a extra command line options. If there's a better way to do, let us know and we'll implement it that way.

**Comment by bettinaheim** [comment]
Assigning to @boschmitt for a temporary fix for the next release. After that, we should consider how to proceed with the drive holistically, and possibly make the config files actual configs (e.g. yml) following a specified format.

**Comment by schweitzpgi** [comment]
Let's put this on the discussion docket...

**Comment by schweitzpgi** [comment]
Fixed. Unrecognized options are handed off to clang++ now.
