### ISSUE TITLE
running container with Podman fails unless the user specifies -u 0:0

### ISSUE THREAD

**Issue by scothalverson** [NVIDIA/cuda-quantum#266]
### Required prerequisites

- [X] Make sure you've read the [documentation](https://nvidia.github.io/cuda-quantum/latest). Your issue may be addressed there.
- [X] Search the [issue tracker](https://github.com/NVIDIA/cuda-quantum/issues) to verify that this hasn't already been reported. +1 or comment there if it has.
- [ ] If possible, make a PR with a failing test to give us a starting point to work on!

### Describe the bug

On Perlmutter, NERSC's newest supercomputer, running the cuda-quantum container found here (https://catalog.ngc.nvidia.com/orgs/nvidia/containers/cuda-quantum) fails unless the user specifies `-u 0:0`

### Steps to reproduce the bug

Run https://catalog.ngc.nvidia.com/orgs/nvidia/containers/cuda-quantum with Podman (or Podman-hpc: https://github.com/NERSC/podman-hpc) like so:

`podman-hpc run --gpu --rm -it cuda-quantum:0.3.0`

this will fail to run, exiting immediately.

running the following:
`podman-hpc run --gpu -u 0:0 --rm -it cuda-quantum:0.3.0`

will work.

### Expected behavior

Without specifying `-u 0:0`, the container should run as user `cudaq`.  This works in Docker, but not in Podman.  Podman supplies this flag to run a rootless container.  As a workaround, this works, except the user in the container is `root` instead of `cudaq`

### Is this a regression? If it is, put the last known working version (or commit) here.

Not a regression

### Environment

- **CUDA Quantum version**: 0.3.0 cuda-quantum container from NGC
- **Python version**:  
- **C++ compiler**: 
- **Operating system**:

**Comment by schweitzpgi** [comment]
Tien, can you triage this one? Thanks.

**Comment by 1tnguyen** [comment]
This is no longer an issue. I'm not sure what the problem was but 0.3.0 is quite old and we've changed our docker images substantially since then.

**Steps I did to verify:**

On Perlmutter:

```
perlmutter:login24:~> podman-hpc run --gpu --rm -it ghcr.io/nvidia/cuda-quantum:latest
```

This was successful. Inside the container, I can run some simple tests, like:
```
cudaq@ac9d5eb249b1:~$ nvq++ examples/cpp/basics/static_kernel.cpp --target nvidia
cudaq@ac9d5eb249b1:~$ ./a.out
{ 0000000000:517 1111111111:483 }
Observed: 0000000000, 517
Observed: 1111111111, 483
```
