### ISSUE TITLE
RuntimeError for MGMN backend

### ISSUE THREAD

**Issue by zohimchandani** [NVIDIA/cuda-quantum#27]
The multi gpu multi node backend from the docs [here](https://nvidia.github.io/cuda-quantum/using/simulators.html#:~:text=cudaq.set_qpu(%27cuquantum_mgmn%27)) gives the following error 

```
cudaq.set_qpu('cuquantum_mgmn')

RuntimeError: Invalid qpu name: cuquantum_mgmn

```

**Comment by bettinaheim** [comment]
@zohimchandani This is an error in the documentation. The correct target name is cuquantum-mgpu. You can also query the available targets using the[ list_gpus](https://nvidia.github.io/cuda-quantum/api/languages/python_api.html#cudaq.list_qpus) function.

**Comment by zohimchandani** [comment]
The correct name is `cuquantum_mgpu` 

`list_gpus` function is helpful, thanks.
