### ISSUE TITLE
[pass]  LoopUnrolling: raise an error if it cannot unroll a loop

### ISSUE THREAD

**Issue by boschmitt** [NVIDIA/cuda-quantum#277]
### Required prerequisites

- [X] Search the [issue tracker](https://github.com/NVIDIA/cuda-quantum/issues) to check if your feature has already been mentioned or rejected in other issues.

### Describe the feature

The loop unrolling pass is best-effort, i.e., it will try to unroll all loops but won't complain if that is not possible. Normally this is the desired behavior, however, when JIT compiling kernel to a backend it would be best if the pass fails when a loop can't be unrolled. This new behavior would allows better error reporting to the user, since the alternative would be a failure when trying to lower generic CFG to QIR---at point at which we might not be able to easily identify the unrolling as being the culprit.

**Comment by schweitzpgi** [comment]
I would change the title from "forcing loop unrolling" to "have the pass raise an error if it cannot unroll a loop." I think that reflects what the description says.

(There will be situations were a loop simply cannot be unrolled fully. "Forcing" the unrolling just would not be possible.)
