### ISSUE TITLE
Incorrect list of QPUs returned from query of runtime

### ISSUE THREAD

**Issue by zohimchandani** [NVIDIA/cuda-quantum#28]
`cudaq.list_qpus()` returns: `['tensornet', 'custatevec', 'dm', 'qpp', 'cuquantum_mgpu', 'custatevec_f32']` where `custatevec` should instead be `cuquantum`

**Comment by amccaskey** [comment]
Thanks for finding this! Easy fix. Will have one shortly. Also, for now, tensornet should not be in the list since it is only available in C++.
