### ISSUE TITLE
pytest ends with SIGSEGV

### ISSUE THREAD

**Issue by schweitzpgi** [NVIDIA/cuda-quantum#303]
### Required prerequisites

- [X] Make sure you've read the [documentation](https://nvidia.github.io/cuda-quantum/latest). Your issue may be addressed there.
- [X] Search the [issue tracker](https://github.com/NVIDIA/cuda-quantum/issues) to verify that this hasn't already been reported. +1 or comment there if it has.
- [ ] If possible, make a PR with a failing test to give us a starting point to work on!

### Describe the bug

On a ubuntu 22.04 machine which python-3 and pytest-3 apt-get installed...

Build cuda quantum with PYTHON support enabled.

### Steps to reproduce the bug

From the installation directory, I noticed the following:
```console
> PYTHONPATH=. pytest-3 -rP ../cudaq/python/tests/compiler/no_input.py | cat
> PYTHONPATH=. pytest-3 -rP ../cudaq/python/tests/compiler/no_input.py
...
Segmentation fault
>
```

### Expected behavior

Do not expect a SIGSEGV.

### Is this a regression? If it is, put the last known working version (or commit) here.

Not a regression

### Environment

- **CUDA Quantum version**: tip
- **Python version**: 3.10.6
- **C++ compiler**: 
- **Operating system**: Ubuntu

**Comment by amccaskey** [comment]
shouldnt you set PYTHONPATH=$PWD/python?

**Comment by schweitzpgi** [comment]
> shouldnt you set PYTHONPATH=$PWD/python?

I seemed to pick up the python code. I don't know if it fixed the mystery segfault. The segfault appears to some `munmap` call with a bad pointer when the process is exiting?

Anthony is seeing a similar segfault issue during process teardown. May be the same/similar bug tickled a different way. 🤷

**Comment by amccaskey** [comment]
Reproducer: 

* build in release mode with -DCUDAQ_ENABLE_PYTHON=TRUE
* comment out the pytest.skip(...) part of python/tests/backends/test_IonQ.py
* then from the build directory, run
```bash
PYTHONPATH=$PWD/python:/workspaces/cuda-quantum/ gdb --args python3-dbg -m pytest -s ../../python/tests/backends/test_IonQ.py
```
