### ISSUE TITLE
Include is ignored by nvq++

### ISSUE THREAD

**Issue by bettinaheim** [NVIDIA/cuda-quantum#319]
### Required prerequisites

- [X] Make sure you've read the [documentation](https://nvidia.github.io/cuda-quantum/latest). Your issue may be addressed there.
- [X] Search the [issue tracker](https://github.com/NVIDIA/cuda-quantum/issues) to verify that this hasn't already been reported. +1 or comment there if it has.
- [ ] If possible, make a PR with a failing test to give us a starting point to work on!

### Describe the bug

Bug report received via email:

Using nvq++ with its own cmake configuration provided by CUDA Quantum website, whenever I include additional directories to my project,
They are passed to the compiler without the `-I` flag, making them to be ignored during compilation.
 
```cmake
set(CUDAQ_DIR $ENV{CUDA_QUANTUM_PATH}/lib/cmake/cudaq)
set(CMAKE_FIND_PACKAGE_PREFER_CONFIG TRUE)
find_package(CUDAQ REQUIRED)
 
add_library(tgt)
set_target_properties(tgt PROPERTIES LANGUAGE CXX)
 
target_sources(tgt
PRIVATE
 
# Sources
${CMAKE_CURRENT_SOURCE_DIR}/src/tgt_source.cpp
PUBLIC
 
# Headers
${CMAKE_CURRENT_SOURCE_DIR}/include/tgt/tgt_header.hpp
)
 
target_include_directories(tgt PUBLIC
$<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/include/>
$<INSTALL_INTERFACE:${CMAKE_INSTALL_INCLUDEDIR}>)
 
target_link_libraries(tgt nvqir-custatevec)
```
 
The output from cmake during build has these messages

```
[build] argument /project/cudaq/include is ignored
[build] argument /usr/include is ignored
```

### Steps to reproduce the bug

See above.

### Expected behavior

Include should be processed.

### Is this a regression? If it is, put the last known working version (or commit) here.

Not a regression

### Environment

- **CUDA Quantum version**:  current main
- **Python version**:  N/A
- **C++ compiler**:  N/A
- **Operating system**: N/A

**Comment by schweitzpgi** [comment]
The `-I` flag is required. Is this a request for some sort of extension?

**Comment by 1tnguyen** [comment]
I'm not sure if this is related: when integrating CUDAQ's `nvq++` into a CMake project (via `find_package(CUDAQ)`), I've added `set(CMAKE_INCLUDE_FLAG_CUDAQ "-I")` to get it to work.

**Comment by orclassiq** [comment]
Note that the same applies for libraries that are linked by path.
For example, when calling `nvq++  /usr/lib/x86_64-linux-gnu/libssl.a  main.cpp.o -o test_app` the output is:
```
argument /usr/lib/x86_64-linux-gnu/libssl.a is ignored
ld.lld: error: undefined symbol: OPENSSL_init_ssl
>>> referenced by main.cpp
>>>               CMakeFiles/test_app.dir/main.cpp.o:(main)
>>> referenced by main.cpp
>>>               CMakeFiles/test_app.dir/main.cpp.o:(main)
clang-16: error: linker command failed with exit code 1 (use -v to see invocation)
```

While the issue can be solved by using `-lssl` instead, this solution doesn't apply for other cases.
The main case is C++ package managers (such as vcpkg or conan) that link libraries by path to support using multiple builds of the same package on one machine.

**Comment by mdepasca** [comment]
Adding `set(CMAKE_INCLUDE_FLAG_CUDAQ "-I")` fixed the problem thanks a lot.

IMHO setting this variable should be taken care by CUDAQ cmake config files.

**Comment by mdepasca** [comment]
I may have spot additional problems with cmake integration. Do you prefer I open a separate issues?

**Comment by mdepasca** [comment]
I opened issue #545

**Comment by schweitzpgi** [comment]
I believe this is fixed. Please reopen (or better open a new issue) if there are other option handling issues with the tools.
