### ISSUE TITLE
Failure to create `qreg` using kernel argument as size

### ISSUE THREAD

**Issue by boschmitt** [NVIDIA/cuda-quantum#339]
### Required prerequisites

- [X] Make sure you've read the [documentation](https://nvidia.github.io/cuda-quantum/latest). Your issue may be addressed there.
- [X] Search the [issue tracker](https://github.com/NVIDIA/cuda-quantum/issues) to verify that this hasn't already been reported. +1 or comment there if it has.
- [X] If possible, make a PR with a failing test to give us a starting point to work on!

### Describe the bug

We seem to be getting a failure when trying to allocate a `qreg` that has a size defined by an argument:

`test-5.cpp` in #323
```cpp
#include <cudaq.h>
#include <iostream>

__qpu__ void variable_qreg(unsigned value) {
  cudaq::qreg qubits(value);
  mz(qubits);
}

int main() {
  for (auto i = 1; i < 5; ++i) {
    auto result = cudaq::sample(1000, variable_qreg, i);
    std::cout << result.most_probable() << '\n';
  }
  return 0;
}
```

### Steps to reproduce the bug

Trying to run the above program outputs:
```
loc("test-5.cpp":15:15): error: 'quake.alloca' op size operand required
terminate called after throwing an instance of 'std::runtime_error'
  what():  Remote rest platform Quake lowering failed.
Aborted (core dumped)
```

### Expected behavior

The QuakeSynth pass should have made the argument a constant inside the kernel, and thus this kernel should JIT compile correctly.

### Is this a regression? If it is, put the last known working version (or commit) here.

Not a regression

### Environment

- **CUDA Quantum version**: main
- **C++ compiler**: gcc-12
- **Operating system**: Ubuntu 22.04 (x86-64, docker)

**Comment by amccaskey** [comment]
I think that this is due to the same bug in #337 .

**Comment by bettinaheim** [comment]
@schweitzpgi After 337 is fixed, can you confirm if this also fixes this issue? If not, we'll assign it at that time.

**Comment by schweitzpgi** [comment]
test-5 passes.
