### ISSUE TITLE
Linker error when trying to build kernel with `std::acos`

### ISSUE THREAD

**Issue by boschmitt** [NVIDIA/cuda-quantum#341]
### Required prerequisites

- [X] Make sure you've read the [documentation](https://nvidia.github.io/cuda-quantum/latest). Your issue may be addressed there.
- [X] Search the [issue tracker](https://github.com/NVIDIA/cuda-quantum/issues) to verify that this hasn't already been reported. +1 or comment there if it has.
- [X] If possible, make a PR with a failing test to give us a starting point to work on!

### Describe the bug

When trying to build a kernels that uses `std::acos`:
`test-3.cpp` in #323
```cpp
#include <cudaq.h>
#include <iostream>

__qpu__ void init_state() {
  double theta = 2. * std::acos(1. / std::sqrt(3));
  cudaq::qreg qubits(2);
  ry(theta, qubits[0]);
  h<cudaq::ctrl>(qubits[0], qubits[1]);
  x(qubits[1]);
};

int main() {
  auto result = cudaq::sample(1000, init_state);
  for (auto &&[bits, counts] : result) {
    std::cout << bits << '\n';
  }
  return 0;
}
```

We get an linker error:
```
usr/bin/ld: test-3.o: in function `__nvqpp__mlirgen__function_init_state._Z10init_statev':
(.text+0x24): undefined reference to `acos'
/usr/bin/ld: test-3.o: in function `function_init_state._Z10init_statev.thunk':
(.text+0xc4): undefined reference to `acos'
clang-16: error: linker command failed with exit code 1 (use -v to see invocation)
```

### Steps to reproduce the bug

Try to compile the above program using 

`bin/nvq++ -v ../test/NVQPP/test-3.cpp  -o test-3 --target quantinuum --emulate`

### Expected behavior

If we can't handle this function, we should return an error.

### Is this a regression? If it is, put the last known working version (or commit) here.

Not a regression

### Environment

- **CUDA Quantum version**: main
- **C++ compiler**: gcc-12
- **Operating system**: Ubuntu 22.04 (x86-64, docker)

**Comment by schweitzpgi** [comment]
Have to add `-lm` to the command-line, eh?

**Comment by boschmitt** [comment]
> Have to add `-lm` to the command-line, eh?

I actually tried that:
```bin/nvq++ -v ../test/NVQPP/test-3.cpp  -o test-3 --target quantinuum --emulate -lm```

But if seems that the `-lm` do not get added to the linking step that we need(?):

```
/home/tpls/llvm/build/install/bin/clang++ -DNVQPP_TARGET_BACKEND_CONFIG="quantinuum;emulate;true" -o nvqppGenTargetBackend.Qmyhu2.o -c -x c++ /home/build/targets/backendConfig.cpp
/home/build/bin/cudaq-quake -I /home/tpls/fmt/include --emit-llvm-file ../test/NVQPP/test-3.cpp -o test-3.qke
/home/build/bin/cudaq-opt --pass-pipeline=builtin.module(canonicalize,lambda-lifting,func.func(memtoreg{quantum=0}),canonicalize,apply-op-specialization,kernel-execution,inline{default-pipeline=func.func(indirect-to-direct-calls)},func.func(quake-add-metadata),device-code-loader{use-quake=1},func.func(unwind-lowering),expand-measurements,func.func(lower-to-cfg),canonicalize,cse) test-3.qke -o test-3.qke.q53TEO
/home/build/bin/cudaq-translate --convert-to=qir test-3.qke.q53TEO -o test-3.ll.47VMXL
/home/build/bin/fixup-linkage.pl test-3.qke test-3.ll
/home/tpls/llvm/build/install/bin/llc --relocation-model=pic --filetype=obj -O2 test-3.ll.47VMXL -o test-3.qke.o
/home/tpls/llvm/build/install/bin/llc --relocation-model=pic --filetype=obj -O2 test-3.ll -o test-3.classic.o
/home/tpls/llvm/build/install/bin/clang++ -L/home/build/lib -L/home/build/lib/plugins -L/usr/lib/gcc/x86_64-linux-gnu/12 -L/usr/lib/x86_64-linux-gnu -L/usr/lib -L/lib/x86_64-linux-gnu -L/lib -r test-3.qke.o test-3.classic.o nvqppGenTargetBackend.Qmyhu2.o -o test-3.o
/home/tpls/llvm/build/install/bin/clang++ -Wl,-rpath,/home/build/lib -Wl,-rpath,/home/build/lib/plugins -Wl,-rpath,/home/build -L/home/build/lib -L/home/build/lib/plugins -L/usr/lib/gcc/x86_64-linux-gnu/12 -L/usr/lib/x86_64-linux-gnu -L/usr/lib -L/lib/x86_64-linux-gnu -L/lib test-3.o -lcudaq -lcudaq-common -lcudaq-mlir-runtime -lcudaq-builder -lcudaq-ensmallen -lcudaq-nlopt -lcudaq-spin -lcudaq-pyscf -lm -lcudaq-rest-qpu -lcudaq-em-qir -lcudaq-platform-default -lnvqir -lnvqir-qpp -o test-3
```

We call `clang++` twice. It seems like the `-lm` flag only affects the second call.

**Comment by bettinaheim** [comment]
The issue is also that any use of std runtime functions inside a kernel will currently not get compiled away properly before the compiled kernel is set to quantum backends. As a first step that is critical, we need to give a nice, comprehensive error so that people evaluate these functions outside of kernels for now. As a follow up item that won't be part of the next release, we should look into supporting a standard set of functions within kernels.

**Comment by schweitzpgi** [comment]
> > Have to add `-lm` to the command-line, eh?
> 
> I actually tried that: `bin/nvq++ -v ../test/NVQPP/test-3.cpp -o test-3 --target quantinuum --emulate -lm`
> 
> But if seems that the `-lm` do not get added to the linking step that we need(?):
> 
> ```
> /home/tpls/llvm/build/install/bin/clang++ -DNVQPP_TARGET_BACKEND_CONFIG="quantinuum;emulate;true" -o nvqppGenTargetBackend.Qmyhu2.o -c -x c++ /home/build/targets/backendConfig.cpp
> /home/build/bin/cudaq-quake -I /home/tpls/fmt/include --emit-llvm-file ../test/NVQPP/test-3.cpp -o test-3.qke
> /home/build/bin/cudaq-opt --pass-pipeline=builtin.module(canonicalize,lambda-lifting,func.func(memtoreg{quantum=0}),canonicalize,apply-op-specialization,kernel-execution,inline{default-pipeline=func.func(indirect-to-direct-calls)},func.func(quake-add-metadata),device-code-loader{use-quake=1},func.func(unwind-lowering),expand-measurements,func.func(lower-to-cfg),canonicalize,cse) test-3.qke -o test-3.qke.q53TEO
> /home/build/bin/cudaq-translate --convert-to=qir test-3.qke.q53TEO -o test-3.ll.47VMXL
> /home/build/bin/fixup-linkage.pl test-3.qke test-3.ll
> /home/tpls/llvm/build/install/bin/llc --relocation-model=pic --filetype=obj -O2 test-3.ll.47VMXL -o test-3.qke.o
> /home/tpls/llvm/build/install/bin/llc --relocation-model=pic --filetype=obj -O2 test-3.ll -o test-3.classic.o
> /home/tpls/llvm/build/install/bin/clang++ -L/home/build/lib -L/home/build/lib/plugins -L/usr/lib/gcc/x86_64-linux-gnu/12 -L/usr/lib/x86_64-linux-gnu -L/usr/lib -L/lib/x86_64-linux-gnu -L/lib -r test-3.qke.o test-3.classic.o nvqppGenTargetBackend.Qmyhu2.o -o test-3.o
> /home/tpls/llvm/build/install/bin/clang++ -Wl,-rpath,/home/build/lib -Wl,-rpath,/home/build/lib/plugins -Wl,-rpath,/home/build -L/home/build/lib -L/home/build/lib/plugins -L/usr/lib/gcc/x86_64-linux-gnu/12 -L/usr/lib/x86_64-linux-gnu -L/usr/lib -L/lib/x86_64-linux-gnu -L/lib test-3.o -lcudaq -lcudaq-common -lcudaq-mlir-runtime -lcudaq-builder -lcudaq-ensmallen -lcudaq-nlopt -lcudaq-spin -lcudaq-pyscf -lm -lcudaq-rest-qpu -lcudaq-em-qir -lcudaq-platform-default -lnvqir -lnvqir-qpp -o test-3
> ```
> 
> We call `clang++` twice. It seems like the `-lm` flag only affects the second call.

OK. Looking more closely, the problem is using mangled function names vs. C library names.

**Comment by schweitzpgi** [comment]
Linker issue resolved.
