### ISSUE TITLE
Error when trying to simulate `qspan`

### ISSUE THREAD

**Issue by boschmitt** [NVIDIA/cuda-quantum#345]
### Required prerequisites

- [X] Make sure you've read the [documentation](https://nvidia.github.io/cuda-quantum/latest). Your issue may be addressed there.
- [X] Search the [issue tracker](https://github.com/NVIDIA/cuda-quantum/issues) to verify that this hasn't already been reported. +1 or comment there if it has.
- [X] If possible, make a PR with a failing test to give us a starting point to work on!

### Describe the bug

I haven't done much of a preliminary analysis on this bug and thus it is hard to say if this is a compiler bug or a runtime bug.  The issue is that the following code won't simulate:

```cpp
#include <cudaq.h>
#include <iostream>

__qpu__ void bar(cudaq::qspan<> qubits) {
  auto controls = qubits.front(qubits.size() - 1);
  auto &target = qubits.back();
  x<cudaq::ctrl>(controls, target);
}

__qpu__ void foo() {
  cudaq::qreg qubits(4);
  x(qubits);
  bar(qubits);
  mz(qubits);
}

int main() {
  auto result = cudaq::sample(1000, foo);
  std::cout << result.size() << '\n';
  for (auto &&[bits, counts] : result) {
    std::cout << bits << '\n';
  }
  return 0;
}
```

Because we get the following error:
```
terminate called after throwing an instance of 'qpp::exception::SubsysMismatchDims'
  what():  qpp::applyCTRL(): Subsystems mismatch dimensions! [dims/ctrl/target]
FileCheck error: '<stdin>' is empty.
FileCheck command line:  /opt/llvm/bin/FileCheck /workspaces/cuda-quantum/test/NVQPP/test-4.cpp
```

### Steps to reproduce the bug

Try to emulate the above program for the quantinuum target.

### Expected behavior

The program should execute correctly.

### Is this a regression? If it is, put the last known working version (or commit) here.

Not a regression

### Environment

- **CUDA Quantum version**: main
- **C++ compiler**: gcc 12
- **Operating system**: Ubuntu 22.04 (x86-64, docker)

**Comment by amccaskey** [comment]
Double check the multi-control decomposition. I'm seeing this in the output 
```bash
[2023-07-03 20:06:23.739] [info] [CircuitSimulator.h:837] (apply) ctrl-x(0, 0)
```

**Comment by boschmitt** [comment]
> Double check the multi-control decomposition. I'm seeing this in the output
> 
> ```shell
> [2023-07-03 20:06:23.739] [info] [CircuitSimulator.h:837] (apply) ctrl-x(0, 0)
> ```

The multi-control decomposition looks fine. The culprit seems to be the related to how `quake.subvec` is handled. The following is the analysis of the generated quake:


```mlir
    %0 = quake.alloca !quake.ref // This will be qubit 0
    %c2_i64 = arith.constant 2 : i64
    %c0_i64 = arith.constant 0 : i64
    %1 = quake.alloca !quake.veq<4> // These qubits [1, 2, 3, 4]

    // In the following we have (all good):
    // [2023-07-04 15:54:54.787] [info] [CircuitSimulator.h:837] (apply) x(1)
    // [2023-07-04 15:54:54.788] [info] [CircuitSimulator.h:837] (apply) x(2)
    // [2023-07-04 15:54:54.788] [info] [CircuitSimulator.h:837] (apply) x(3)
    // [2023-07-04 15:54:54.788] [info] [CircuitSimulator.h:837] (apply) x(4)
    %2 = quake.extract_ref %1[0] : (!quake.veq<4>) -> !quake.ref
    quake.x %2 : (!quake.ref) -> ()
    %3 = quake.extract_ref %1[1] : (!quake.veq<4>) -> !quake.ref
    quake.x %3 : (!quake.ref) -> ()
    %4 = quake.extract_ref %1[2] : (!quake.veq<4>) -> !quake.ref
    quake.x %4 : (!quake.ref) -> ()
    %5 = quake.extract_ref %1[3] : (!quake.veq<4>) -> !quake.ref
    quake.x %5 : (!quake.ref) -> ()

    // We extract a subvec: [1, 2, 3]
    %6 = quake.subvec %1, %c0_i64, %c2_i64 : (!quake.veq<4>, i64, i64) -> !quake.veq<3>

    // Extract the last qubit from the veq
    %7 = quake.extract_ref %1[3] : (!quake.veq<4>) -> !quake.ref // qubit 4

    // We extract the qubits from the subvec
    %8 = quake.extract_ref %6[0] : (!quake.veq<3>) -> !quake.ref // qubit 1
    %9 = quake.extract_ref %6[1] : (!quake.veq<3>) -> !quake.ref // qubit 2
    %10 = quake.extract_ref %6[2] : (!quake.veq<3>) -> !quake.ref // qubit 3

    // Now we use the qubits from before:
    // [2023-07-04 15:54:54.788] [info] [CircuitSimulator.h:837] (apply) h(0) --- OK
    quake.h %0 : (!quake.ref) -> ()
    // [2023-07-04 15:54:54.788] [info] [CircuitSimulator.h:837] (apply) ctrl-x(1, 0) --- NOT OK! %9 should be qubit 2
    quake.x [%9] %0 : (!quake.ref, !quake.ref) -> ()
    // [2023-07-04 15:54:54.788] [info] [CircuitSimulator.h:837] (apply) tdg(0) -- OK
    quake.t<adj> %0 : (!quake.ref) -> ()
    // [2023-07-04 15:54:54.788] [info] [CircuitSimulator.h:837] (apply) ctrl-x(0, 0) -- NOT OK! %8 should be qubit 1
    quake.x [%8] %0 : (!quake.ref, !quake.ref) -> ()
    ...
```

**Comment by amccaskey** [comment]
What do you mean by compiling away? The `qspan` maps to a `quake.veq`, isn't that what we want?

**Comment by boschmitt** [comment]
> What do you mean by compiling away? The `qspan` maps to a `quake.veq`, isn't that what we want?

We need to JIT to the QIR's base profile. Right now we are compiling to our flavor of QIR (NVQIR) that, for example, uses things like `__quantum__rt__array_slice` which is not (or won't be?) supported by backends.
