### ISSUE TITLE
Typo in docs 

### ISSUE THREAD

**Issue by zohimchandani** [NVIDIA/cuda-quantum#346]
### Required prerequisites

- [X] Search the [issue tracker](https://github.com/NVIDIA/cuda-quantum/issues) to check if your feature has already been mentioned or rejected in other issues.

### Describe the feature

Can we make [this](https://nvidia.github.io/cuda-quantum/latest/api/languages/python_api.html#cudaq.observe:~:text=accept%20any%20arguments.-,shots_count%20(Optional%5Bint%5D)%20%E2%80%93%20The%20number%20of%20shots%20to%20use%20for%20QPU%20execution.%20Defaults%20to%201%20shot.%20Key%2Dword%20only.,-noise_model%20(Optional%5B) more clear please?

The default should be -1 which means that the state vector is built once and the exact expectation value is calculated, i.e. <psi|H|psi>. Can we clarify this a bit more for users in the documentation?

Thanks

**Comment by schweitzpgi** [comment]
It looks like the `-1` default value is documented to me. Is there something else to be done or should we close this issue?
