### ISSUE TITLE
Add install instructions for using singularity on docs 

### ISSUE THREAD

**Issue by zohimchandani** [NVIDIA/cuda-quantum#353]
### Required prerequisites

- [X] Search the [issue tracker](https://github.com/NVIDIA/cuda-quantum/issues) to check if your feature has already been mentioned or rejected in other issues.

### Describe the feature

Lots of HPC systems don't allow docker. Can we get singularity instructions on the documentation page please?

**Comment by schweitzpgi** [comment]
"singularity"? Do you mean a standalone binary release? Or build instructions to build outside of a container?

**Comment by zohimchandani** [comment]
I believe this is what I mean: https://docs.sylabs.io/guides/2.6/user-guide/introduction.html
