### ISSUE TITLE
Rename tests in test/NVQPP directory

### ISSUE THREAD

**Issue by schweitzpgi** [NVIDIA/cuda-quantum#357]
The tests `test-[0-6].cpp` give no indication what the tests are testing. Rename these tests to something more descriptive.

One possibility: names like `issue_89.cpp` while not descriptive in their own right would at least provide a cross reference to the GitHub issue.

**Comment by ZyphrFlaw** [comment]
I want to work on this, please assign it to me

**Comment by schweitzpgi** [comment]
> I want to work on this, please assign it to me. Certain test file point to same issue.

Thanks for volunteering.
