### ISSUE TITLE
Do not require a server helper for emulation

### ISSUE THREAD

**Issue by boschmitt** [NVIDIA/cuda-quantum#369]
### Required prerequisites

- [X] Search the [issue tracker](https://github.com/NVIDIA/cuda-quantum/issues) to check if your feature has already been mentioned or rejected in other issues.

### Describe the feature

It seems that the `--emulate` flag require a specific server helper to be implemented, e.g., to emulate quantinuum we need a the quantinuum server helper. As we are emulating the kernels, this feels unnecessary.

**Comment by bettinaheim** [comment]
I believe this is no longer required. I remember enabling emulation tests also when the server helpers were not compiled. @amccaskey  for confirmation.
