### ISSUE TITLE
Kernels created by `cudaq::kernel_builder` can't be translated to OpenQASM

### ISSUE THREAD

**Issue by orclassiq** [NVIDIA/cuda-quantum#378]
### Required prerequisites

- [X] Make sure you've read the [documentation](https://nvidia.github.io/cuda-quantum/latest). Your issue may be addressed there.
- [X] Search the [issue tracker](https://github.com/NVIDIA/cuda-quantum/issues) to verify that this hasn't already been reported. +1 or comment there if it has.
- [ ] If possible, make a PR with a failing test to give us a starting point to work on!

### Describe the bug

Kernels created by the `cudaq::kernel_builder` class can't be translated to OpenQASM by `cudaq-translate`. This is because they don't contain any function with the `cudaq-entrypoint` attribute.

### Steps to reproduce the bug

Compile the following code using `nvq++ kernel.cpp`:
```c++
#include <cudaq.h>

#include <iostream>

int main() {
        auto kernel = cudaq::make_kernel();
        auto qubit = kernel.qalloc(1);
        kernel.x(qubit[0]);
        kernel.mz(qubit[0]);
        std::cout << kernel.to_quake() << std::endl;
        return 0;
}
```

The result is the following MLIR code:
```
module {
  func.func @__nvqpp__mlirgen____nvqppBuilderKernel_367535629127() {
    %0 = quake.alloca !quake.veq<1>
    %1 = quake.extract_ref %0[0] : (!quake.veq<1>) -> !quake.ref
    quake.x %1 : (!quake.ref) -> ()
    %2 = quake.mz %1 : (!quake.ref) -> i1 {registerName = ""}
    return
  }
}
```

When the file is translated using `cudaq-translate --convert-to=openqasm kernel.qke`, the output is
```
// Code generated by NVIDIA's nvq++ compiler
OPENQASM 2.0;

include "qelib1.inc";

[quake-translate] Dumping Module after error.
[quake-translate] Reported Error: see current operation:
"func.func"() ({
  %0 = "quake.alloca"() : () -> !quake.veq<1>
  %1 = "quake.extract_ref"(%0) {rawIndex = 0 : i64} : (!quake.veq<1>) -> !quake.ref
  "quake.x"(%1) {operand_segment_sizes = array<i32: 0, 0, 1>} : (!quake.ref) -> ()
  %2 = "quake.mz"(%1) {registerName = ""} : (!quake.ref) -> i1
  "func.return"() : () -> ()
}) {function_type = () -> (), sym_name = "__nvqpp__mlirgen____nvqppBuilderKernel_367535629127"} : () -> ()
loc("kernel.qke":2:3): error: cannot translated classical functions
[quake-translate] Dumping Module after error.
loc("kernel.qke":1:1): error: translation failed
LLVM ERROR: fatal error, aborting.
Aborted
```

### Expected behavior

The output of the C++ program should be:
```
module {
  func.func @__nvqpp__mlirgen____nvqppBuilderKernel_367535629127() attributes {"cudaq-entrypoint"} {
    %0 = quake.alloca !quake.veq<1>
    %1 = quake.extract_ref %0[0] : (!quake.veq<1>) -> !quake.ref
    quake.x %1 : (!quake.ref) -> ()
    %2 = quake.mz %1 : (!quake.ref) -> i1 {registerName = ""}
    return
  }
}
```

Which will then be translated to:
```
// Code generated by NVIDIA's nvq++ compiler
OPENQASM 2.0;

include "qelib1.inc";

qreg var0[1];
x var0[0];
creg var2[1];
measure var0[0] -> var2[0];
```

### Is this a regression? If it is, put the last known working version (or commit) here.

Not a regression

### Environment

- **`cuda-quantum` docker image version**: `sha256:337d6e846edfd6c41cde2e89d60ea223aaf2ecdc7d6d2f86797ecfa04497483d`. Download using `docker pull ghcr.io/nvidia/cuda-quantum@sha256:337d6e846edfd6c41cde2e89d60ea223aaf2ecdc7d6d2f86797ecfa04497483d`

### Suggestions

I think this can be fixed by using the code from the `jitCode()` method in the `to_quake()` method.

https://github.com/NVIDIA/cuda-quantum/blob/571bbe9f78d084044d7d54f69bc7f619dafdff0e/runtime/cudaq/builder/kernel_builder.cpp#L684-L693

**Comment by amccaskey** [comment]
The above suggestion should work. Would you like to issue a PR?
