### ISSUE TITLE
Kernel calls can't be translated into OpenQASM

### ISSUE THREAD

**Issue by orclassiq** [NVIDIA/cuda-quantum#380]
### Required prerequisites

- [X] Make sure you've read the [documentation](https://nvidia.github.io/cuda-quantum/latest). Your issue may be addressed there.
- [X] Search the [issue tracker](https://github.com/NVIDIA/cuda-quantum/issues) to verify that this hasn't already been reported. +1 or comment there if it has.
- [ ] If possible, make a PR with a failing test to give us a starting point to work on!

### Describe the bug

Quake code in which a kernel is called by another kernel can't be translated to OpenQASM.
This is due to two reasons:
- The CallOp instruction isn't supported by the translator.
- The resulting gate definition's name starts with an underscore (`_`), which isn't allowed in OpenQASM.

### Steps to reproduce the bug

Compile the following code using `nvq++ kernel.ccp`:
```c++
#include <cudaq.h>

#include <numbers>
#include <iostream>

int main() {
        auto [kernel1, qubit1] = cudaq::make_kernel<cudaq::qubit>();
        kernel1.x(qubit1);

        auto kernel2 = cudaq::make_kernel();
        auto qubit = kernel2.qalloc();
        kernel2.call(kernel1, qubit);
        kernel2.mz(qubit);

        std::cout << kernel2.to_quake() << std::endl;
        return 0;
}
```

The result is the following MLIR code:
```
module {
  func.func @__nvqpp__mlirgen____nvqppBuilderKernel_093606261879() {
    %0 = quake.alloca !quake.ref
    call @__nvqpp__mlirgen____nvqppBuilderKernel_367535629127(%0) : (!quake.ref) -> ()
    %1 = quake.mz %0 : (!quake.ref) -> i1 {registerName = ""}
    return
  }
  func.func @__nvqpp__mlirgen____nvqppBuilderKernel_367535629127(%arg0: !quake.ref) {
    quake.x %arg0 : (!quake.ref) -> ()
    return
  }
}
```

When the file is translated using `cudaq-translate --convert-to=openqasm kernel.qke`, the output is:
```
// Code generated by NVIDIA's nvq++ compiler
OPENQASM 2.0;

include "qelib1.inc";

// Code generated by NVIDIA's nvq++ compiler
OPENQASM 2.0;

include "qelib1.inc";

gate __nvqpp__mlirgen____nvqppBuilderKernel_367535629127 q0 {
  x q0;
}

qreg var0[1];
[quake-translate] Dumping Module after error.
[quake-translate] Reported Error: see current operation: "func.call"(%0) {callee = @__nvqpp__mlirgen____nvqppBuilderKernel_367535629127} : (!quake.ref) -> ()
loc("kernel.qke":4:5): error: 'func.call' op unable to translate op to OpenQASM 2.0
[quake-translate] Dumping Module after error.
loc("kernel.qke":0:0): error: translation failed
LLVM ERROR: fatal error, aborting.
Aborted
```

### Expected behavior

The MLIR code should be successfully translated to:
```
// Code generated by NVIDIA's nvq++ compiler
OPENQASM 2.0;

include "qelib1.inc";
gate x__nvqpp__mlirgen____nvqppBuilderKernel_367535629127 q0 {
  x q0;
}

qreg var0[1];
x__nvqpp__mlirgen____nvqppBuilderKernel_367535629127 var0[0];
creg var1[1];
measure var0[0] -> var1[0];
```

Or to an equivalent OpenQASM code.

### Is this a regression? If it is, put the last known working version (or commit) here.

Not a regression

### Environment

- **`cuda-quantum` docker image version**: `sha256:337d6e846edfd6c41cde2e89d60ea223aaf2ecdc7d6d2f86797ecfa04497483d`. Download using `docker pull ghcr.io/nvidia/cuda-quantum@sha256:337d6e846edfd6c41cde2e89d60ea223aaf2ecdc7d6d2f86797ecfa04497483d`

**Comment by amccaskey** [comment]
@orclassiq Do you care if the function is inlined?

**Comment by orclassiq** [comment]
> @orclassiq Do you care if the function is inlined?
> 
> ```shell
> ./a.out | bin/cudaq-opt --canonicalize --inline | bin/cudaq-translate --convert-to=openqasm
> ```
> 
> ```
> // Code generated by NVIDIA's nvq++ compiler
> OPENQASM 2.0;
> 
> include "qelib1.inc";
> 
> gate __nvqpp__mlirgen____nvqppBuilderKernel_367535629127 q0 {
>   x q0;
> }
> 
> qreg var0[1];
> x var0[0];
> creg var1[1];
> measure var0[0] -> var1[0];
> ```

I think it would be more beneficial if the function isn't inlined. Converting function calls preserves higher-level constructs within the algorithm and the intent of the algorithm designer.
