### ISSUE TITLE
Kernels created by cudaq-quake can't be serialized into OpenQASM

### ISSUE THREAD

**Issue by orclassiq** [NVIDIA/cuda-quantum#381]
### Required prerequisites

- [X] Make sure you've read the [documentation](https://nvidia.github.io/cuda-quantum/latest). Your issue may be addressed there.
- [X] Search the [issue tracker](https://github.com/NVIDIA/cuda-quantum/issues) to verify that this hasn't already been reported. +1 or comment there if it has.
- [ ] If possible, make a PR with a failing test to give us a starting point to work on!

### Describe the bug

When kernels are serialized into MLIR using `cudaq-quake`, the resulting MLIR code also contains a function that can't be translated into OpenQASM using `cudaq-translate`.

The function follows this pattern:
```
func.func private @<MANGLED_NAME>(!cc.ptr<i8>)
```

### Steps to reproduce the bug

Extract the MLIR code from the following CUDA Quantum code using `cudaq-quake kernel.cpp`:
```c++
#include <cudaq.h>

struct ghz {
  void operator()() __qpu__ {
    cudaq::qubit q;
    x(q);
    mz(q);
  }
};

int main() {
}
```

The resulting MLIR code is:
```
module attributes {quake.mangled_name_map = {__nvqpp__mlirgen__ghz = "_ZN3ghzclEv"}} {
  func.func @__nvqpp__mlirgen__ghz() attributes {"cudaq-entrypoint", "cudaq-kernel"} {
    %0 = quake.alloca !quake.ref loc(#loc2)
    quake.x %0 : (!quake.ref) -> () loc(#loc3)
    %1 = quake.mz %0 : (!quake.ref) -> i1 loc(#loc4)
    return loc(#loc5)
  } loc(#loc1)
  func.func private @_ZN3ghzclEv(!cc.ptr<i8>) loc(#loc1)
} loc(#loc)
#loc = loc(unknown)
#loc1 = loc("kernel.cpp":4:3)
#loc2 = loc("kernel.cpp":5:18)
#loc3 = loc("kernel.cpp":6:5)
#loc4 = loc("kernel.cpp":7:5)
#loc5 = loc("kernel.cpp":4:29)
```

When the file is translated using `cudaq-translate --convert-to=openqasm kernel.qke`, the output is:
```
// Code generated by NVIDIA's nvq++ compiler
OPENQASM 2.0;

include "qelib1.inc";

[quake-translate] Dumping Module after error.
[quake-translate] Reported Error: see current operation:
"func.func"() ({
}) {function_type = (!cc.ptr<i8>) -> (), sym_name = "_ZN3ghzclEv", sym_visibility = "private"} : () -> ()
loc("kernel.cpp":4:3): error: cannot translated classical functions
[quake-translate] Dumping Module after error.
error: translation failed
LLVM ERROR: fatal error, aborting.
Aborted
```

### Expected behavior

The resulting OpenQASM code should be:
```
// Code generated by NVIDIA's nvq++ compiler
OPENQASM 2.0;

include "qelib1.inc";

qreg var0[1];
x var0[0];
creg var1[1];
measure var0[0] -> var1[0];
```

### Is this a regression? If it is, put the last known working version (or commit) here.

Not a regression

### Environment

- **`cuda-quantum` docker image version**: sha256:337d6e846edfd6c41cde2e89d60ea223aaf2ecdc7d6d2f86797ecfa04497483d. Download using docker pull ghcr.io/nvidia/cuda-quantum@sha256:337d6e846edfd6c41cde2e89d60ea223aaf2ecdc7d6d2f86797ecfa04497483d

### Suggestions

I think the issue can be solved by skipping functions whose name doesn't start with the `__nvqpp__mlirgen__` prefix, unless they are called by another function that whose name does start with the aforementioned prefix.

**Comment by schweitzpgi** [comment]
Is it sufficient to just look for the `"cudaq-kernel"` attribute? i.e., don't we want to include pure device kernels? (Filtering out the launchpad CPU code is a good idea. 👍  )

**Comment by amccaskey** [comment]
#407
