### ISSUE TITLE
exp val syntax

### ISSUE THREAD

**Issue by zohimchandani** [NVIDIA/cuda-quantum#384]
### Required prerequisites

- [X] Search the [issue tracker](https://github.com/NVIDIA/cuda-quantum/issues) to check if your feature has already been mentioned or rejected in other issues.

### Describe the feature

```
n_qubits = 10
n_terms = 100

hamiltonian = cudaq.SpinOperator.random(n_qubits, n_terms)   

exp_val = cudaq.observe(kernel, hamiltonian)

```
To get the value of `exp_val` we need to do `exp_val.expectation_z()` which makes it sound like we are extracting the z expectation value when infact we are extracting `<psi|H|psi>` and not `<psi|Z|psi>`

**Comment by anthony-santana** [comment]
To summarize our conclusions on this after the weekly meeting:
* We will rename the python `expectation_z` member function for both `sample` and `observe` results to just "expectation" ("expectation_z" will become deprecated)
* This better indicates what the function is actually doing -- i.e., it's not always calculating < Z>

Outstanding questions:
* Which of the following renames for C++ ? `exp_val_z` -> `exp_val` or also to `expectation` ? I prefer the latter but also understand the first case fits a bit better with C++ style

**Comment by amccaskey** [comment]
I vote that we change the C++ to `.expectation()`. This will be great in that the C++ and Python will mirror each other now.
