### ISSUE TITLE
Base Profile specification compliance. 

### ISSUE THREAD

**Issue by amccaskey** [NVIDIA/cuda-quantum#385]
* requiredQubits should be required_num_qubits
* requiredResults should be required_num_results
* EntryPoint should be entry_point
* the entry point should return an i64 (which is 0 to indicate successful execution)
* to be fully spec compliant, we would also need to break this into an entry, body, measurements, and output block
* to be fully spec compliant, we would also need to mark the measurement function as irreversible (by an attribute) and use writeonly attributes for results
* an entry point attribute "qir_profiles"="base_profile" is missing
* __quantum__qis__read_result__body is not base profile compliant - you don't need it and can simply drop it here
* __quantum__rt__array_start_record_output should now be __quantum__rt__array_record_output(i64, i8*), and * __quantum__rt__array_end_record_output no longer exists (the first integer in the new function is the nr of elements)
* Same for output recording of tuples (albeit not used in your example)
* you are missing the llvm module flags that indicate qir major, minor, and data types used - it should look like
```llvm
!llvm.module.flags = !{!0, !1, !2, !3}

!0 = !{i32 1, !"qir_major_version", i32 1}
!1 = !{i32 7, !"qir_minor_version", i32 0}
!2 = !{i32 1, !"dynamic_qubit_management", i1 false}
!3 = !{i32 1, !"dynamic_result_management", i1 false}
```

Now with all that said, some of these things don't seem to work on a remote system like Quantinuum's (like `required_num_qubits`, `requiredQubits` still works). 

Just posting this to get the list saved somewhere.

**Comment by schweitzpgi** [comment]
This is great. Thanks for the list, Alex. Do any of these things need to be done for the release?

**Comment by amccaskey** [comment]
Bettina wrote it 😄

**Comment by amccaskey** [comment]
I'd say we don't need these for this release, but I would have to defer to @bettinaheim officially. I am able to run jobs on Quantinuum as is. I have not yet tried IonQ.

**Comment by bmhowe23** [comment]
I think that Issue #556 can serve as a replacement for this issue, so I'd recommend closing this one. Any objections? For what it's worth, PR #546 resolved the following that were mentioned above (pasted as they existed above):
- EntryPoint should be entry_point
- to be fully spec compliant, we would also need to mark the measurement function as irreversible (by an attribute) and use writeonly attributes for results
- an entry point attribute "qir_profiles"="base_profile" is missing
- __quantum__qis__read_result__body is not base profile compliant - you don't need it and can simply drop it here
- you are missing the llvm module flags that indicate qir major, minor, and data types used

The rest are covered in the spreadsheet attached to #556.

**Comment by bettinaheim** [comment]
Closing this as superseded by #556
