### ISSUE TITLE
Default inclusion of plugins by nvq++ leads to missing library at runtime

### ISSUE THREAD

**Issue by otbrown** [NVIDIA/cuda-quantum#386]
### Required prerequisites

- [X] Make sure you've read the [documentation](https://nvidia.github.io/cuda-quantum/latest). Your issue may be addressed there.
- [X] Search the [issue tracker](https://github.com/NVIDIA/cuda-quantum/issues) to verify that this hasn't already been reported. +1 or comment there if it has.
- [ ] If possible, make a PR with a failing test to give us a starting point to work on!

### Describe the bug

Building code with nvq++ currently results in the inclusion of all plugin libraries which are present in the install (see [nvq++.in:197](https://github.com/NVIDIA/cuda-quantum/blob/2dbdbdd77c649748f71459f00eee639e09131cc1/tools/nvqpp/nvq%2B%2B.in#L197C4-L197C4)). Currently if building with python support, this includes `libcudaq-pyscf.so`. This plugin depends on `libcudaq-chemistry.so`, which is _not_ linked by default, resulting in a runtime error: `error while loading shared libraries: libcudaq-chemistry.so: cannot open shared object file: No such file or directory`.

This can be fixed by manually adding `-lcudaq-chemistry` to the compile command.

### Steps to reproduce the bug

Build CUDA Quantum with `CUDAQ_ENABLE_PYTHON` set to `True`.

Compile the bellow hello world program with the command `nvq++ -o hello ./hello.cpp`. Then attempt to run the binary `./hello`, or use `ldd hello` to view the linkage.

```C++
#include <iostream>

int main (void)
{
  printf("Hello world!\n");
  return 0;
}
```

### Expected behavior

Programs compiled with nq++ but not using cudaq-pyscf or cudaq-chemistry to not try to link either (or to successfully link both).

### Is this a regression? If it is, put the last known working version (or commit) here.

Not a regression

### Environment

- **CUDA Quantum version**: 0.4.0
- **Python version**: 3.10.6
- **C++ compiler**:  clang version 16.0.6
- **Operating system**: Ubuntu 22.04.2 LTS

### Suggestions

Modify `nvq++.in` to only link `libcudaq-pyscf.so` when the chemistry package is loaded. Alternatively, my unsophisticated local solution was to append `-lcudaq-chemistry` to the list of always loaded libraries.

**Comment by schweitzpgi** [comment]
Following the bug report I cannot reproduce this.
```console
$ ldd hello | grep plugin
        libcudaq-pyscf.so => /home/cudaq-build/lib/plugins/libcudaq-pyscf.so (0x00007f20f3d74000)
        libcudaq-chemistry.so => /home/cudaq-build/lib/plugins/../libcudaq-chemistry.so (0x00007f20f34a4000)
        libcudaq-py-utils.so => /home/cudaq-build/lib/plugins/../libcudaq-py-utils.so (0x00007f20f33ee000)
```
So the plugins ought to be linking against the files in both `lib/plugins` and `lib` by default.

**Comment by otbrown** [comment]
Apologies for the delayed response -- if it can't be reproduced I'm happy to assume it was either an issue with the specific version I was using or (more likely) a local configuration error. I'll close!
