### ISSUE TITLE
GPU Simulation Target Names

### ISSUE THREAD

**Issue by amccaskey** [NVIDIA/cuda-quantum#404]
For clarity, we should update the nvidia target names to indicate the type of simulator. Proposal is: 

`nvidia` -> `nvidia-sv`
`nvidia-fp64` -> `nvidia-sv-fp64`
`tensornet` -> `nvidia-tn`
`cuquantum_mgpu` -> `nvidia-sv-mgpu`
future mps -> `nvidia-tn-mps`

**Comment by bettinaheim** [comment]
Putting this on the backburner for now. I notice a lot of nvidia- prefixes...

**Comment by bettinaheim** [comment]
closing as won't change for now. we'll take inventory over all target names prior to preparing for a 1.0 release.
