### ISSUE TITLE
[tbd]: Remove qspan from compiler

### ISSUE THREAD

**Issue by schweitzpgi** [NVIDIA/cuda-quantum#485]
See #75 . qspan is to be phased out and replaced with qview.

We may want to take two releases with this at minimum. First declare it deprecated. Second remove it.

A subtask here is to convert all tests, examples, and documentation to use the new name as well.

**Comment by bettinaheim** [comment]
Let's first come to a conclusion on 75. I am a bit doubtful about the value of a name change given the amount of docs and samples that people are already familiar with.
