### ISSUE TITLE
Few types in the documentation and files

### ISSUE THREAD

**Issue by Jookare** [NVIDIA/cuda-quantum#496]
### Required prerequisites

- [X] Make sure you've read the [documentation](https://nvidia.github.io/cuda-quantum/latest). Your issue may be addressed there.
- [X] Search the [issue tracker](https://github.com/NVIDIA/cuda-quantum/issues) to verify that this hasn't already been reported. +1 or comment there if it has.
- [ ] If possible, make a PR with a failing test to give us a starting point to work on!

### Describe the bug

In docs/sphinx/using/simulators.rst documentation the multi-GPU target does not match the correct target. 

Current:
`nvidia_mgpu`

Suggestion:
`nvidia-mqpu`

Also in docs/sphinx/examples/cpp/basics/cuquantum_backends.cpp file the comments have the old way of choosing the simulator backend.

Current:
`nvq++ cuquantum_backends.cpp -o dyn.x -qpu cuquantum && ./dyn.x`

Suggestion:
`nvq++ --target nvidia cuquantum_backends.cpp -o dyn.x && ./dyn.x`

### Steps to reproduce the bug

pull the container and run the `nvq++ --list-targets`
```
ubuntu:~$ sudo apptainer pull docker://ghcr.io/nvidia/cuda-quantum:latest
ubuntu:~$ apptainer exec cuda-quantum_latest.sif nvq++ --list-targets
density-matrix-cpu
ionq
nvidia-fp64
nvidia-mqpu-fp64
nvidia-mqpu
nvidia
quantinuum
ubuntu:~$
```

### Expected behavior

Expected the targets to be same as documented targets.

### Is this a regression? If it is, put the last known working version (or commit) here.

Not a regression

### Environment

- **CUDA Quantum version**: latest
- **Python version**: 3.10.6
- **C++ compiler**: 11.3.0
- **Operating system**: Ubuntu 22.04.1

### Suggestions
Rename the old `-qpu cuquantum` to `--target nvidia` in 
docs/sphinx/examples/cpp/basics/cuquantum_backends.cpp

Rename the old `nvidia_mgpu` to `nvidia-mqpu` in
docs/sphinx/using/simulators.rst

**Comment by bettinaheim** [comment]
This has been fixed.
