### ISSUE TITLE
Extend measurement support for submissions to IonQ

### ISSUE THREAD

**Issue by bettinaheim** [NVIDIA/cuda-quantum#512]
### Required prerequisites

- [X] Make sure you've read the [documentation](https://nvidia.github.io/cuda-quantum/latest). Your issue may be addressed there.
- [X] Search the [issue tracker](https://github.com/NVIDIA/cuda-quantum/issues) to verify that this hasn't already been reported. +1 or comment there if it has.
- [ ] If possible, make a PR with a failing test to give us a starting point to work on!

### Describe the bug

The IonQ backends support performing measurements only as a final step in the kernel execution; mid-circuit measurements are not supported. Right now, measuring more than one qubit causes issues when submitting to the IonQ backends, even if these measurements are performed at the end. The CUDA Quantum toolchain should
1) support any measurements that can be moved to the end without using additional qubits, independent on where in the code these measurements occur
2) consider supporting other measurement using the [principle of deferred measurements](https://en.wikipedia.org/wiki/Deferred_measurement_principle#:~:text=The%20deferred%20measurement%20principle%20is,the%20probability%20distribution%20of%20outcomes.); i.e. support them at the cost of using additional qubits, or at least add a configuration to allow this.

### Steps to reproduce the bug

Submit the kernels below to the IonQ simulator.

### Expected behavior

E.g. it should be possible to sample this kernel on IonQ backends:
```
struct ghz {
  // Maximally entangled state between 5 qubits.
  auto operator()() __qpu__ {
    cudaq::qreg q(5);
    h(q[0]);
    for (int i = 0; i < 4; i++) {
      x<cudaq::ctrl>(q[i], q[i + 1]);
    }
    mz(q);
  }
};
```

It should also be possible to sample this kernel (non-sense code to illustrate what I mean):
```
struct ghz {
  // Maximally entangled state between 5 qubits.
  auto operator()() __qpu__ {
    cudaq::qreg reg1(2);
    h(reg1[0]);
    x<cudaq::ctrl>(reg1[0], reg1[1]);
    mz(reg1);

    cudaq::qreg reg1(2);
    x(reg1[0]);
    x<cudaq::ctrl>(reg1[0], reg1[1]);
    mz(reg1);
};
```

It would be nice if this was also something the compiler could compile into a kernel that can be sampled on IonQ by using 4 instead of 2 qubits:

```
struct ghz {
  // Maximally entangled state between 5 qubits.
  auto operator()() __qpu__ {
    cudaq::qreg reg(2);
    h(reg[0]);
    x<cudaq::ctrl>(reg[0], reg[1]);
    mz(reg);

    x<cudaq::ctrl>(reg[0], reg[1]);
    mz(reg);
};
```

### Is this a regression? If it is, put the last known working version (or commit) here.

Not a regression

### Environment

- **CUDA Quantum version**: 0.4.0
- **Python version**: N/A
- **C++ compiler**: N/A
- **Operating system**: N/A

**Comment by bmhowe23** [comment]
PR #571 disabled some nightly integration tests. Once this issue is resolved, the list of supported tests should be reconsidered.

**Comment by bmhowe23** [comment]
Here is another example of a program that fails due to this issue. This program uses `cudaq::observe()`.
```
[root@docker-desktop build (main *)]# nvq++ examples/cpp/basics/expectation_values.cpp --target ionq
[root@docker-desktop build (main *)]# ./a.out
terminate called after throwing an instance of 'std::runtime_error'
  what():  The job failed upon submission. Check the job submission in your IonQ account for more information.
Aborted
```
It fails on the "YY" job, which produces this IR (note the multiple measurements)
```llvm
define void @__nvqpp__mlirgen__ansatz() local_unnamed_addr #1 {
  tail call void @__quantum__qis__x__body(%Qubit* null)
  tail call void @__quantum__qis__ry__body(double 5.900000e-01, %Qubit* nonnull inttoptr (i64 1 to %Qubit*))
  tail call void @__quantum__qis__cnot__body(%Qubit* nonnull inttoptr (i64 1 to %Qubit*), %Qubit* null)
  tail call void @__quantum__qis__ry__body(double 0x3FF921FB54442D18, %Qubit* null)
  tail call void @__quantum__qis__ry__body(double 0x3FF921FB54442D18, %Qubit* nonnull inttoptr (i64 1 to %Qubit*))
  tail call void @__quantum__qis__mz__body(%Qubit* null, %Result* writeonly null)
  tail call void @__quantum__qis__mz__body(%Qubit* nonnull inttoptr (i64 1 to %Qubit*), %Result* nonnull writeonly inttoptr (i64 1 to %Result*))
  tail call void @__quantum__rt__result_record_output(%Result* null, i8* nonnull getelementptr inbounds ([3 x i8], [3 x i8]* @cstr.723200, i64 0, i64 0))
  tail call void @__quantum__rt__result_record_output(%Result* nonnull inttoptr (i64 1 to %Result*), i8* nonnull getelementptr inbounds ([3 x i8], [3 x i8]* @cstr.723300, i64 0, i64 0))
  ret void
}
```
