### ISSUE TITLE
[RFC] Add for loop capability to kernel_builder

### ISSUE THREAD

**Issue by amccaskey** [NVIDIA/cuda-quantum#53]
# Background 

To further enable programmability via the kernel_builder, we should add the ability for one to specify a for loop within the Quake code being constructed. 

# What would this look like 

```cpp
auto [circuit, inSize] = cudaq::make_kernel<std::size_t>();
auto qubits = circuit.qalloc(inSize);
circuit.h(qubits[0]);
circuit.for_loop(0, inSize - 1, [&](auto &index) {
  circuit.x<cudaq::ctrl>(qubits[index], qubits[index + 1]);
});
```
```python
circuit, inSize = cudaq.make_kernel(int)
qubits = circuit.qalloc(inSize)
circuit.h(qubits[0])
circuit.for_loop(0, inSize-1, lambda index : circuit.cx(qubits[index], qubits[index+1]))
counts = cudaq.sample(circuit, 5)
```

**Comment by schweitzpgi** [comment]
Do you want to call it something like `for_range`?

Possibly in C++ have the first argument be either an upper bound (like Python's `range(n)` but without the "range" identifier) or a `std::pair<int,int>` (like `range(lo, hi)` but against without a range identifier. The full 🌯 might be a triple of `{lo, hi, step}` much like `range`'s triple form.

**Comment by schweitzpgi** [comment]
Believe this is complete. @anthony-santana @amccaskey ?

**Comment by schweitzpgi** [comment]
Closing this. It looks like it is already implemented. (Re-open if this is incorrect, please.)
