### ISSUE TITLE
Support for descending for loops in python

### ISSUE THREAD

**Issue by anthony-santana** [NVIDIA/cuda-quantum#551]
### Required prerequisites

- [X] Search the [issue tracker](https://github.com/NVIDIA/cuda-quantum/issues) to check if your feature has already been mentioned or rejected in other issues.

### Describe the feature

The `Kernel.for_loop` only allows for iterators wherein the start < stop index. Example

```
kernel, size = cudaq.make_kernel(int)
qubits = kernel.qalloc(size)
kernel.h(qubits[0])

def foo(index: int):
    """A function that will be applied to `kernel` in a for loop."""
    kernel.cx(qubits[index], qubits[index+1])

# Note: our stop value will be > our start value.
kernel.for_loop(start=0, stop=size-1, function=foo)
print(kernel)

# Execute the kernel, passing along a concrete value (5) for 
# the `size` argument.
counts = cudaq.sample(kernel, 5)
print(counts)
```

We should also support the opposite case -- or at least temporarily throw an explicit error. This currently results in a JIT error.

```
kernel, size = cudaq.make_kernel(int)
qubits = kernel.qalloc(size)
kernel.h(qubits[0])

def foo(index: int):
    """A function that will be applied to `kernel` in a for loop."""
    kernel.cx(qubits[index], qubits[index+1])

# Note: our stop value will be < our start value (descending iteration).
kernel.for_loop(start=size-1, stop=0, function=foo)
print(kernel)

# Execute the kernel, passing along a concrete value (5) for 
# the `size` argument.
counts = cudaq.sample(kernel, 5)
print(counts)
```

**Comment by bettinaheim** [comment]
Tentatively adding this to 0.5 - P2, so tbd if it will make it or be included in the next one.

**Comment by schweitzpgi** [comment]
I think you need an extra bit of information here someplace. As specified, it could be interpreted that
```
kernel.for_loop(start=size-1, stop=0, function=foo)
```
steps from `size-1` to `size` ... up to MAX_INT and does a two-complement wrap in 64 bits (possibly?) then does the entire negative range of integers until incrementing up to `0`.

So perhaps we need a `for_loop_decrement` or something like that?

**Comment by bettinaheim** [comment]
Covered with the new support for python syntax.
