### ISSUE TITLE
Segfault after test completion for linux/arm64 Python wheels

### ISSUE THREAD

**Issue by bettinaheim** [NVIDIA/cuda-quantum#554]
### Required prerequisites

- [X] Make sure you've read the [documentation](https://nvidia.github.io/cuda-quantum/latest). Your issue may be addressed there.
- [X] Search the [issue tracker](https://github.com/NVIDIA/cuda-quantum/issues) to verify that this hasn't already been reported. +1 or comment there if it has.
- [X] If possible, make a PR with a failing test to give us a starting point to work on!

### Describe the bug

The tests in python/tests/backends are currently failing when installing aarch64 python wheels for all (tested) distributions. I haven't looked more closely than that they seem to be segfaulting after completion and pretty independent on what tests are run.

### Steps to reproduce the bug

Search for `# ARM:` comment in the .github folder, and replace the hardcoded `[amd64]` platform id with the commented out code, then run CI.

### Expected behavior

Tests should pass.

### Is this a regression? If it is, put the last known working version (or commit) here.

Not a regression

### Environment

- **CUDA Quantum version**:  See https://github.com/NVIDIA/cuda-quantum/pull/548.
- **Python version**: any
- **C++ compiler**:  n/a
- **Operating system**: all of the tested ones.

### Suggestions

Possibly related: https://github.com/NVIDIA/cuda-quantum/issues/303

**Comment by 1tnguyen** [comment]
This was fixed in https://github.com/NVIDIA/cuda-quantum/pull/557. Closing.
