### ISSUE TITLE
Update C++ standard lib runtime dependency to libstdc++-12

### ISSUE THREAD

**Issue by bettinaheim** [NVIDIA/cuda-quantum#57]
CUDA Quantum has a runtime dependency on the C++ standard library. Right now, this is libstdc++-11-dev. 
Outside the docker image that is distributed, this will cause issues when e.g. a newer gcc 12 is present and the standard library resolves to version 12 on the system. While this isn't fully addressing a broader issue, it would be good to update this dependency to libstdc++-12.

- [x] Update the nvq++ compiler to support  libstdc++-12
- [x] Check in CUDA Quantum Docker image and validate it as part of CI
- [x] Update the runtime dependency in the CUDA Quantum Docker image
- [x] Add gcc12 to the pipeline and remove gcc11

The broader issue to address is that we update CUDA Quantum to use a specific version of the standard library rather than relying on the system setup. This work will be tracked separately and is not covered by this work item.

**Comment by schweitzpgi** [comment]
Do we want to stop testing gcc 11? Could be good to test both gcc 12 and gcc 11 to make sure we don't introduce gcc 12 dependencies.

**Comment by bettinaheim** [comment]
Done with https://github.com/NVIDIA/cuda-quantum/pull/84.
