### ISSUE TITLE
Quantum device kernels for chemistry applications

### ISSUE THREAD

**Issue by zohimchandani** [NVIDIA/cuda-quantum#586]
### Required prerequisites

- [X] Search the [issue tracker](https://github.com/NVIDIA/cuda-quantum/issues) to check if your feature has already been mentioned or rejected in other issues.

### Describe the feature

Can we add support for these gates please: 

Fermionic swap gates
Givens rotation gates
A givens rotation controlled by 2 qubits.

Moreover, is it possible for a user to define a unitary matrix and use that as a quantum operation.

**Comment by zohimchandani** [comment]
Adding gates via cupy would be great too. 

Users are interested in [this](https://www.youtube.com/watch?v=H-xYNjEThr0&ab_channel=GoogleQuantumAI) kind of functionality

**Comment by bettinaheim** [comment]
@zohimchandani I would like to break this apart into two work items: 
1. We can add support for fermionic swap gates and givens rotations (any number of controls would be supported via cudaq::control like it is supported for other gates in CUDA Quantum). 
2. Support of arbitrary unitaries is something we need to flesh out a more extensive RFC for, and I would like to defer that until after 0.5.0.

**Comment by bettinaheim** [comment]
@zohimchandani Closing this as the request in this issue is now supported. If there is a desire to have support for creating a gate/kernel by defining an arbitrary unitary, could you please open a separate issue for it?
