### ISSUE TITLE
Support common compilation flags in nvq++ 

### ISSUE THREAD

**Issue by oryarnitzky-classiq** [NVIDIA/cuda-quantum#601]
### Required prerequisites

- [X] Search the [issue tracker](https://github.com/NVIDIA/cuda-quantum/issues) to check if your feature has already been mentioned or rejected in other issues.

### Describe the feature

The `nvq++` driver ignores arguments it doesn't know how to handle.

Few examples:
1. Warnings flags (`-W*`) such as `-Wall` are ignored by the driver, but are useful when compiling C++ code
2. The `-M*` flags allow build and build generator tools (such as CMake) to maintain a dependency list for `.cpp` files.

If these specific flags will be supported by `cudaq-quake`, `nvq++` should accept them as valid flags and pass them to either `cudaq-quake` or the underlying host compiler.

A more general solution is to allow passing any flag to the host compiler by adding a `--extra-arg` flag (like clang-tidy's: https://clang.llvm.org/extra/clang-tidy/) which will  pass its argument to the underlying C++ compiler.

The relevant code: 

https://github.com/NVIDIA/cuda-quantum/blob/3fe9658a48ad6f2cca85253751367c2433a53d21/tools/nvqpp/nvq%2B%2B.in#L378-L380

The variable `ARGS` is ignored in the rest of the file.

**Comment by schweitzpgi** [comment]
Fixed now. Added a `-Wall` test.
