### ISSUE TITLE
Add python code formatting to CI

### ISSUE THREAD

**Issue by anthony-santana** [NVIDIA/cuda-quantum#61]
Add the command `yapf --style=google -r -i` to our CI to automate formatting of all .py files in the repository. Will work similar to our current clang-format workflow.

**Comment by anthony-santana** [comment]
@bettinaheim I know you mentioned this being captured in a separate PR. Would you prefer me to assign it to you or just close this out?

**Comment by bettinaheim** [comment]
Done and running.
