### ISSUE TITLE
release build fails

### ISSUE THREAD

**Issue by MarcusGDaniels** [NVIDIA/cuda-quantum#611]
### Required prerequisites

- [X] Make sure you've read the [documentation](https://nvidia.github.io/cuda-quantum/latest). Your issue may be addressed there.
- [X] Search the [issue tracker](https://github.com/NVIDIA/cuda-quantum/issues) to verify that this hasn't already been reported. +1 or comment there if it has.
- [X] If possible, make a PR with a failing test to give us a starting point to work on!

### Describe the bug

Building in release mode fails.

### Steps to reproduce the bug

$ cmake ..  -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++  -DCMAKE_BUILD_TYPE=Release

gives.  

/usr/bin/ld: ../../lib/libcudaq-mlirgen.a(ASTBridge.cpp.o): in function `cudaq::ASTBridgeAction::ASTBridgeConsumer::HandleTranslationUnit(clang::ASTContext&)':
ASTBridge.cpp:(.text._ZN5cudaq15ASTBridgeAction17ASTBridgeConsumer21HandleTranslationUnitERN5clang10ASTContextE+0x315): undefined reference to `cudaq::details::QuakeBridgeVisitor::generateFunctionDeclaration(llvm::StringRef, clang::FunctionDecl const*)'
[ 75%] Built target test_qudit

### Expected behavior

completion of build

### Is this a regression? If it is, put the last known working version (or commit) here.

Not a regression

### Environment

- **CUDA Quantum version**:  Today's git 1537660f8adff60edfc047a4be1d0bcd3a8f0021
- **Python version**:  3.10.12
- **C++ compiler**:  clang++ 16.0.0
- **Operating system**:  Ubuntu 22.04

**Comment by schweitzpgi** [comment]
Could not reproduce.

That function is itself defined in the same file, ASTBridge.cpp, near line 355. It's not clear why the linker can't resolve a relocation in an object file to a symbol that should be defined in the same object file. Was the object file somehow truncated?

**Comment by MarcusGDaniels** [comment]
I fooled with the #ifdefs to get it to build.  It wasn't clear why these weren't unconditional.

*** ASTBridge.cpp	2023-09-06 09:00:02.573160754 -0700
--- ASTBridge.cpp-	2023-09-05 20:40:32.799132209 -0700
***************
*** 315,322 ****
  };
  } // namespace
  
- #ifndef NDEBUG
  namespace cudaq::details {
  bool QuakeBridgeVisitor::pushValue(Value v) {
    LLVM_DEBUG(llvm::dbgs() << std::string(valueStack.size(), ' ')
                            << "+push value: ";
--- 315,322 ----
  };
  } // namespace
  
  namespace cudaq::details {
+ #ifndef NDEBUG
  bool QuakeBridgeVisitor::pushValue(Value v) {
    LLVM_DEBUG(llvm::dbgs() << std::string(valueStack.size(), ' ')
                            << "+push value: ";
***************
*** 351,356 ****
--- 351,357 ----
    valueStack.pop_back_n(n);
    return result;
  }
+ #endif
  
  bool QuakeBridgeVisitor::generateFunctionDeclaration(
      StringRef funcName, const clang::FunctionDecl *x) {
***************
*** 369,377 ****
    assert(typeStack.empty() && "expected type stack to be cleared");
    return true;
  }
- 
  } // namespace cudaq::details
! #endif
  
  namespace cudaq {
  bool ASTBridgeAction::ASTBridgeConsumer::isQuantum(
--- 370,377 ----
    assert(typeStack.empty() && "expected type stack to be cleared");
    return true;
  }
  } // namespace cudaq::details
! 
  
  namespace cudaq {
  bool ASTBridgeAction::ASTBridgeConsumer::isQuantum(

**Comment by schweitzpgi** [comment]
I see it now. Thanks.
