### ISSUE TITLE
[RFC] cudaq::observe_n(...), spin_op observe broadcasting

### ISSUE THREAD

**Issue by amccaskey** [NVIDIA/cuda-quantum#62]
# Background 

#25 has brought up a new feature request, specifically to be able to use a single call to `cudaq::observe` on a set of argument data, e.g. given an ansatz that takes as input a list of float parameters, call `observe` on a 2D array of floats, where each row of that data matrix corresponds to the expected value `<psi (row_i) | H | psi (row_i)>`. 

One thing to note is that this introduces more opportunities for "easy" parallelization on multi-GPU architectures.

# Proposal 
I would propose we introduce the `observe_n` function to handle these broadcasted observe calls. Since the `observe` function is variadic and is dependent on the CUDA Quantum ansatz kernel signature, we should think about applying this function on a general `ArgumentSet` type, which encapsulates `N` vectors, one for each argument in the kernel function (`N` being the number of arguments). So the `ith` element of the `ArgumentSet` is the `ith` element of all the vectors holding argument values. Here's how I'd do this (writing it here to get feedback / changes)

```cpp

// ------ Library Code -------
template<typename... Args>
using ArgumentSet = std::tuple<std::vector<Args>...>;

template <typename... Args>
// Use a concept to validate all are vector types.
auto make_argset(Args &&...args) {
  return std::make_tuple(args...);
}

template <typename QuantumKernel, typename... Args>
  requires ObserveCallValid<QuantumKernel, Args...>
std::vector<double> observe_n(QuantumKernel &&kernel, spin_op H,
                                ArgumentSet<Args...> &&params) { ... }
```
Here's how this would look for user code 
```cpp
// ------ User Code -------
cudaq::spin_op h = 5.907 - 2.1433 * x(0) * x(1) - 2.1433 * y(0) * y(1) +
                     .21829 * z(0) - 6.125 * z(1);
auto params = cudaq::linspace(-M_PI, M_PI, 50);

{
  auto ansatz = [](double theta) __qpu__ {
    cudaq::qreg q(2);
    x(q[0]);
    ry(theta, q[1]);
    x<cudaq::ctrl>(q[1], q[0]);
  };

  auto allExpVals = cudaq::observe_n(ansatz, h, cudaq::make_argset(params));
}

{
  // Demo non-trivial kernel signature. 
  auto ansatz = [](double theta, int size) __qpu__ {
    cudaq::qreg q(size);
    x(q[0]);
    ry(theta, q[1]);
    x<cudaq::ctrl>(q[1], q[0]);
  };

  auto allExpVals = cudaq::observe_n(
            ansatz, h, cudaq::make_argset(params, std::vector(params.size(), 2)));
}
```
A possible implementation for `cudaq::observe_n` could look like this 
```cpp
template <typename QuantumKernel, typename... Args>
  requires ObserveCallValid<QuantumKernel, Args...>
std::vector<double> observe_n(QuantumKernel &&kernel, spin_op H,
                                ArgumentSet<Args...> &&params) {
  std::vector<double> expVals;

  // Loop over all sets of arguments, the ith element of each vector 
  // in the ArgumentSet tuple
  for (std::size_t i = 0; i < std::get<0>(params).size(); i++) {
    // Construct the current set of arguments as a new tuple
    // We want a tuple so we can use std::apply with the 
    // existing observe() functions. 
    std::tuple<Args...> currentArgs;
    cudaq::tuple_for_each_with_idx(
        params, [&]<typename IDX_TYPE>(auto &&element, IDX_TYPE &&idx) {
          std::get<IDX_TYPE::value>(currentArgs) = element[i];
        });

    // Call observe with the current set of arguments (provided as a tuple)
    auto expVal = std::apply(
        [&](auto &&...tupleArgs) -> double {
          return observe(kernel, H, tupleArgs...);
        },
        currentArgs);

    // Store the result.
    expVals.push_back(expVal);
  }

  return expVals;
}
```

Note that with that inner expectation value computation, we are free to use `observe_async` and assign these tasks to any available virtual QPUs asynchronously and in parallel. 

In Python, this should look like this 
```python
kernel, params = cudaq.make_kernel(list)
... create the ansatz ... 

params = np.random.uniform(-np.pi, np.pi, size=(50, 20))
expVals = cudaq.observe_n(kernel, H, params) 
```

Also, we could do similar things with `cudaq::sample_n(...)`

**Comment by zohimchandani** [comment]
For a parameterized ansatz, `observe_async` allows one to batch the parameters and parallelize data collection across the devices available. 

The upcoming `observe_n` functionality lets you broadcast the `observe` call across the leading dimension of the parameters.

I propose `observe_n` to also allow users to input `qpu_id` so that it can include the functionality of `observe_async`. This would enable hybrid QGAN and error mitigation workflows.
