### ISSUE TITLE
Gradients example doesn't make progress on the GPU runners

### ISSUE THREAD

**Issue by bettinaheim** [NVIDIA/cuda-quantum#622]
### Required prerequisites

- [X] Make sure you've read the [documentation](https://nvidia.github.io/cuda-quantum/latest). Your issue may be addressed there.
- [X] Search the [issue tracker](https://github.com/NVIDIA/cuda-quantum/issues) to verify that this hasn't already been reported. +1 or comment there if it has.
- [ ] If possible, make a PR with a failing test to give us a starting point to work on!

### Describe the bug

Enabling a basic validation that runs all examples on the GPU backends, the gradients example fails to make progress. Locally, everything works fine, but on the runners the values are odd:
Locally:
```
Optimize with no gradients.
<H>(0.000000, 0.000000) = -0.436286
<H>(1.570796, 0.000000) = 12.250291
<H>(0.000000, 1.570796) = 9.407001
<H>(-1.241051, -0.962909) = 8.691541
<H>(-0.620525, -0.481455) = 6.446059
...
```
On the GH runner:
```
Optimize with no gradients.
<H>(0.000000, 0.000000) = 15.532000
<H>(1.570796, 0.000000) = 15.532000
<H>(0.000000, 1.570796) = 15.532000
<H>(0.107242, 0.000000) = 15.532000
<H>(0.000000, 0.082867) = 15.532000
...
<H>(0.000000, 0.000000) = 15.532000
<H>(0.000000, 0.000000) = 15.532000 (keeps being this)
```
I haven't had a chance to look further.

May be related: 
https://github.com/NVIDIA/cuda-quantum/issues/583
https://github.com/NVIDIA/cuda-quantum/issues/623
https://github.com/NVIDIA/cuda-quantum/issues/399

### Steps to reproduce the bug

In .github/workflows/publishing.yml enable the /home/cudaq/examples/cpp/other/gradients.cpp example in the validation job, then manually run the workflow for a recent deployment. It would be good to find a local repro, but I don't have one right now.

### Expected behavior

The example should succeed.

### Is this a regression? If it is, put the last known working version (or commit) here.

Not a regression

### Environment

- **CUDA Quantum version**: latest main
- **Python version**: N/A
- **C++ compiler**: any
- **Operating system**: N/A

**Comment by zaikunzhang** [comment]
Hi, I guess the optimization is done by Powell's COBYLA here. If yes, this is a known issue of the old version of COBYLA based on the original Fortran 77 implementation, which may get stuck in infinite loops. It is advised to switch to the [PRIMA implementation of COBYLA](https://github.com/libprima/prima). See https://github.com/NVIDIA/cuda-quantum/issues/399. Thanks.

**Comment by schweitzpgi** [comment]
Claims to be fixed.

**Comment by 1tnguyen** [comment]
Gradients example has been readded to the GPU validation test suite. Closing.

![image](https://github.com/NVIDIA/cuda-quantum/assets/58006629/1d06ca11-ea97-4827-950c-4e5c73451671)
