### ISSUE TITLE
QAOA Max-Cut example fails on GPU runners

### ISSUE THREAD

**Issue by bettinaheim** [NVIDIA/cuda-quantum#623]
### Required prerequisites

- [X] Make sure you've read the [documentation](https://nvidia.github.io/cuda-quantum/latest). Your issue may be addressed there.
- [X] Search the [issue tracker](https://github.com/NVIDIA/cuda-quantum/issues) to verify that this hasn't already been reported. +1 or comment there if it has.
- [ ] If possible, make a PR with a failing test to give us a starting point to work on!

### Describe the bug

Enabling a basic validation that runs all examples on the GPU backends, the qaoa_maxcut.cpp example throws a runtime error due to lack of progress. Locally, everything works fine, but on the GH runners I am getting:
```
Validating qaoa_maxcut.cpp:
terminate called after throwing an instance of 'std::runtime_error'
  what():  NLOpt error: round-off errors limited progress (nlopt roundoff-limited). 
Consider changing the stopping criteria (e.g., reducing max_eval or increasing f_tol) and/or increase the number of measurement shots.
Aborted (core dumped)
```

The qaoa_maxcut_builder.cpp example works fine, but that one is using a different optimizer.

### Steps to reproduce the bug

In .github/workflows/publishing.yml enable the /home/cudaq/examples/cpp/other/gradients.cpp example in the validation job, then manually run the workflow for a recent deployment. It would be good to find a local repro, but I don't have one right now.

### Expected behavior

The example should succeed.

### Is this a regression? If it is, put the last known working version (or commit) here.

Not a regression

### Environment

- **CUDA Quantum version**:  current main
- **Python version**: N/A
- **C++ compiler**:  any
- **Operating system**: N/A

**Comment by schweitzpgi** [comment]
Claims to be fixed.

**Comment by 1tnguyen** [comment]
QAOA Maxcut GPU test has been reenabled and passed. Closing.

![image](https://github.com/NVIDIA/cuda-quantum/assets/58006629/ff23cf3b-b49c-477d-829f-c297961a0a1b)
