### ISSUE TITLE
Nightly integration test failures for 4 IonQ tests (empty programs)

### ISSUE THREAD

**Issue by bmhowe23** [NVIDIA/cuda-quantum#637]
### Required prerequisites

- [X] Make sure you've read the [documentation](https://nvidia.github.io/cuda-quantum/latest). Your issue may be addressed there.
- [X] Search the [issue tracker](https://github.com/NVIDIA/cuda-quantum/issues) to verify that this hasn't already been reported. +1 or comment there if it has.
- [ ] If possible, make a PR with a failing test to give us a starting point to work on!

## Description
As a result of a few changes in #546, some IonQ tests are failing in the recent [nightly integration tests](https://github.com/NVIDIA/cuda-quantum/actions/runs/6134745217). These [two](https://github.com/NVIDIA/cuda-quantum/pull/546/files#diff-ca0e8ca969eee4cfb105ff7b346710c47c03f40cfd864bdf121e471cf10ec4dbL214-L216) separate [changes](https://github.com/NVIDIA/cuda-quantum/pull/546/files#diff-ca0e8ca969eee4cfb105ff7b346710c47c03f40cfd864bdf121e471cf10ec4dbL244-L246) (removal of non-compliant functions), when combined with pre-existing issue #512, are the cause.

## More details
The tests are failing because for the 4 problematic tests, the entire program is being optimized out, and we are essentially left with an empty program, like this:
```
; ModuleID = 'LLVMDialectModule'
source_filename = "LLVMDialectModule"
target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-unknown-linux-gnu"

; Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
define void @__nvqpp__mlirgen__function_load_value._Z10load_valuej() local_unnamed_addr #0 {
  ret void
}

attributes #0 = { mustprogress nofree norecurse nosync nounwind willreturn memory(none) "entry_point" "output_labeling_schema"="schema_id" "qir_profiles"="base_profile" "requiredQubits"="4" "requiredResults"="0" }

!llvm.module.flags = !{!0, !1, !2, !3, !4}

!0 = !{i32 2, !"Debug Info Version", i32 3}
!1 = !{i32 1, !"qir_major_version", i32 1}
!2 = !{i32 7, !"qir_minor_version", i32 0}
!3 = !{i32 1, !"dynamic_qubit_management", i1 false}
!4 = !{i32 1, !"dynamic_result_management", i1 false}
```
The reason for the empty program is because the test programs are essentially performing no meaningful operations on the qubits, and the measurements are disabled (due #512), and the IonQ backend is throwing errors on these empty programs.

### Steps to reproduce the bug

The bug can be reproduced locally in the dev image by performing the following steps (after substituting your IonQ key):
```bash
[root@docker-desktop build]# nvq++ -DIONQ_TARGET ../test/NVQPP/integration/load_value.cpp --target ionq
[root@docker-desktop build]# CUDAQ_DUMP_JIT_IR=1 IONQ_API_KEY=*** ./a.out
; ModuleID = 'LLVMDialectModule'
source_filename = "LLVMDialectModule"
target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-unknown-linux-gnu"

; Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
define void @__nvqpp__mlirgen__function_load_value._Z10load_valuej() local_unnamed_addr #0 {
  ret void
}

attributes #0 = { mustprogress nofree norecurse nosync nounwind willreturn memory(none) "entry_point" "output_labeling_schema"="schema_id" "output_names"="[[]]" "qir_profiles"="base_profile" "requiredQubits"="4" "requiredResults"="0" }

!llvm.module.flags = !{!0, !1, !2, !3, !4}

!0 = !{i32 2, !"Debug Info Version", i32 3}
!1 = !{i32 1, !"qir_major_version", i32 1}
!2 = !{i32 7, !"qir_minor_version", i32 0}
!3 = !{i32 1, !"dynamic_qubit_management", i1 false}
!4 = !{i32 1, !"dynamic_result_management", i1 false}
terminate called after throwing an instance of 'std::runtime_error'
  what():  The job failed upon submission. Check the job submission in your IonQ account for more information.
Aborted
```

### Expected behavior

It's not entirely clear what the correct behavior of this empty program should be (again, it is empty due to #512 combined with the fact that everything has been optimized out), but it probably shouldn't throw a runtime error like this.

### Is this a regression? If it is, put the last known working version (or commit) here.

Yes, it is a regression. Last known working version was the version before #546, which was 60a1a9c1466559947172d6ea4feb5f42a689a2bc.

### Environment

- **CUDA Quantum version**: 7e37718bba238cc88aa7b7870d5413012c0e5e6f (and later)
- **Python version**: N/A
- **C++ compiler**: 16.0.0
- **Operating system**: Ubuntu 22.04

**Comment by bettinaheim** [comment]
@bmhowe23 Could you make a suggestion for how to best address this?
There are a couple of cudaq functions that provide a convenient way to express common patters (sample, observe) that involve "adding" measurements. Sounds like we are not properly reflecting these measurements at the time when we optimize. (If we strip them for submission to IonQ, we should only do that right before the submission and after all optimizations have run.)

**Comment by bmhowe23** [comment]
The tests that are failing have no meaningful operations and the compiler is correct to optimize everything out in my opinion. For example, the first iteration of [load_value.cpp](https://github.com/NVIDIA/cuda-quantum/blob/main/test/NVQPP/integration/load_value.cpp) calls `load_value(0)`, which performs no `x` operations (since 0 has no bits set), and since `IONQ_TARGET` is set, no `mz` operations are performed either. No operations remain, and that seems correct to me. The change that #546 introduced was to eliminate the non-compliant `__quantum__rt__array_start_record_output` and `__quantum__rt__array_end_record_output` functions from the resulting bitcode, so nothing is left in the function.

I believe we can choose from the following two options to resolve this issue. (I'm open to other ideas, too)
1. Disable the 4 problematic tests (for IonQ only) until #512 is solved. We already have other tests in this same boat, so there would be some precedence to choose this option.
2. Change the compiler to inject the `__quantum__rt__initialize` function into all of our QIR bitcode. According to the [Base Profile spec](https://github.com/qir-alliance/qir-spec/blob/main/specification/under_development/profiles/Base_Profile.md), this function must be supported by all backends, so there shouldn't be any harm in doing this, but I have not tested it.

**Comment by bmhowe23** [comment]
I prototyped option 2 above, and it appears that both Quantinuum and IonQ backends _do not_ support the `tail call void @__quantum__rt__initialize(i8* null)` instruction that is specified in the Base Profile, so it doesn't seem like that option will work for us. In that case, I'd recommend option 1 above (disabling the tests).
