### ISSUE TITLE
[RFC] CUDA Quantum file extension

### ISSUE THREAD

**Issue by schweitzpgi** [NVIDIA/cuda-quantum#651]
Many third party tools, such as build systems, key off file extensions to help guide their processes. To date, we've overloaded the .cpp extension for CUDA quantum code. While that works well in a simulation environment which can use a stock C++ compiler and link with the runtime, a better solution is needed as the project moves towards compiling all CUDA quantum kernels with the `nvq++` compiler and tools.

At minimum, it is envisioned that CUDA quantum kernels will co-exist with C++ code and Cuda kernels. It will be reasonable to assume multilanguage programming models such as mixing code written in assembly, C, Fortran, OpenACC, OpenMP, etc.

The file extensions proposed are
   - .cuq
   - .cq
   - .cuq and .cq
   - other?
   
 Any suggestions or reservations are welcome. Thanks in advance.

**Comment by amccaskey** [comment]
Personally I like the 3 letter extensions (e.g. cpp). I think we should go with .cuq since CUDA is .cu (we'll just tag on an extra q for quantum).

**Comment by anthony-santana** [comment]
Thoughts on .qu ? The 2 letters keeps it concise like .cu, while getting to toss in a q for added pizzazz. Also, (I think) it's easier to say out loud than .cuq -- either as "dot q u file" or "dot queue file".
