### ISSUE TITLE
Expose general Pauli rotation operation for simulation performance

### ISSUE THREAD

**Issue by amccaskey** [NVIDIA/cuda-quantum#654]
For applications that need to affect a general `exp(i theta PauliTensorProd)`, we typically just decompose into a set of basis change, cnots, and rz operations, and the reverse. If we need to apply a bunch of these then this can be very costly on the backend simulators since these circuits will grow to a very large depth. In addition to this, cuStateVec has a dedicated function for this type of rotation. We should hook this up to the programming language to enable optimal performance on our GPU simulators.

My proposal would be to enable something like this 
```python
import cudaq 
from cudaq import x

@cudaq.kernel
def ansatz(theta):
    qubits = cudaq.qvector(4)
    x(qubits[0])
    x(qubits[1])
    cudaq.exp_pauli(qubits, theta, cudaq.SpinOperator.from_word('XXXY'))

geometry = [('H', (0., 0., 0.)), ('H', (0., 0., .7474))]
molecule, data = cudaq.chemistry.create_molecular_hamiltonian(
    geometry, 'sto-3g', 1, 0)

cudaq.observe(ansatz, molecule, 1.2)
def objectiveFunction(x):
    return cudaq.observe(ansatz, molecule, x[0]).expectation_z()
    
optimizer = cudaq.optimizers.COBYLA()
optimizer.max_iterations = 50
energy, params = optimizer.optimize(
    1, objectiveFunction)
print(energy, params)
```

and connect this up through the `ExecutionManager` to the `CircuitSimulator`, which can be implemented to target the cuStateVec optimal function.

**Comment by amccaskey** [comment]
Started in https://github.com/NVIDIA/cuda-quantum/compare/main...amccaskey:cuda-quantum:applyExpPauli

**Comment by amccaskey** [comment]
@1tnguyen let's override applyExpPauli in QPPCircuitSimulator

**Comment by 1tnguyen** [comment]
This has been implemented. Closing.
