### ISSUE TITLE
Build script doesn't inform of the errors 

### ISSUE THREAD

**Issue by poojarao8** [NVIDIA/cuda-quantum#662]
The build script doesn't tell you if you hit errors. While building, all you see is the message that if there are errors, they'd logged into a file. If you succeed, you get a message. But if the build fails, it just returns.

**Comment by poojarao8** [comment]
Bumping this for visibility.

See below for examples of what happens in both cases.  You can see it is very unintuitive when the build script encounters an error.

when the build fails your terminal shows the following (just exits with no error mesage):
```
$ bash ./scripts/build_cudaq.sh
  ...
  Building CUDA Quantum with configuration Release...
  The progress of the build is being logged to /home/workspaces/cuda-quantum/build/logs/ninja_output.txt.
$
```

when the build succeeds the terminal shows the following (provides a confirmation message that the install succeeded): 
```
$ bash ./scripts/build_cudaq.sh
  ...
  The progress of the build is being logged to /home/workspaces/cuda-quantum/build/logs/ninja_output.txt.
  Installed CUDA Quantum in directory: /home/.cudaq
$
```

**Comment by bettinaheim** [comment]
fixed.
