### ISSUE TITLE
Should clarify that LLVM 16 is required.

### ISSUE THREAD

**Issue by schweitzpgi** [NVIDIA/cuda-quantum#681]
The project cannot be built against newer versions of LLVM and requires version 16. (16.0.6 to be exact.) This does not appear to be called out in the documentation.

**Comment by bmhowe23** [comment]
We currently only describe the build process in [Building.md](https://github.com/NVIDIA/cuda-quantum/blob/main/Building.md), which is _only linked to_ by our [docs](https://nvidia.github.io/cuda-quantum/latest/install.html#build-cuda-quantum-from-source), so I think we only need to update `Building.md` to properly address this issue. @schweitzpgi @bettinaheim please let me know if you disagree.
