### ISSUE TITLE
Cannot execute test/NVQPP/integration/test-observe.cpp with OQC backend

### ISSUE THREAD

**Issue by bmhowe23** [NVIDIA/cuda-quantum#695]
### Required prerequisites

- [X] Make sure you've read the [documentation](https://nvidia.github.io/cuda-quantum/latest). Your issue may be addressed there.
- [X] Search the [issue tracker](https://github.com/NVIDIA/cuda-quantum/issues) to verify that this hasn't already been reported. +1 or comment there if it has.
- [ ] If possible, make a PR with a failing test to give us a starting point to work on!

### Describe the bug

Compiling and running the aforementioned test program w/ `--target oqc` produces a fatal error on the backend. This is currently believed to be an issue related to argument ordering in the rotation instructions. I.e. (qubit, theta) vs (theta, qubit).

### Steps to reproduce the bug

The following example (with email, password, and task_id replaced with dummy values) shows the error:

```bash
[root@docker-desktop build (main)]# pwd
/workspaces/cuda-quantum/build
[root@docker-desktop build (main)]# ninja
ninja: no work to do.
[root@docker-desktop build (main)]# bin/nvq++ ../test/NVQPP/integration/test-observe.cpp --target oqc
[root@docker-desktop build (main)]# OQC_EMAIL=*** OQC_PASSWORD=*** ./a.out 
terminate called after throwing an instance of 'std::runtime_error'
  what():  OQC backend error message: {"task_error":{"error_code":101,"error_message":"'builtins.Constant' object has no attribute 'value'","task_id":"00000000-0000-0000-0000-000000000000"}}
Aborted
```

### Expected behavior

The program should be able to run and produce results without producing a `std::runtime_error`.

### Is this a regression? If it is, put the last known working version (or commit) here.

Not a regression

### Environment

- **CUDA Quantum version**: main (currently 219bc57c)
- **Python version**: N/A
- **C++ compiler**: 16.0.6
- **Operating system**: Ubuntu 22.04

**Comment by bettinaheim** [comment]
Waiting from deployment on the partner side.

**Comment by bmhowe23** [comment]
With recent commits, the test has moved. It can now be tested like this:
```
bin/nvq++ ../test/NVQPP/cudaq_observe.cpp --target oqc
```
