### ISSUE TITLE
Fix the installation line

### ISSUE THREAD

**Issue by poojarao8** [NVIDIA/cuda-quantum#720]
### Required prerequisites

- [X] Make sure you've read the [documentation](https://nvidia.github.io/cuda-quantum/latest). Your issue may be addressed there.
- [X] Search the [issue tracker](https://github.com/NVIDIA/cuda-quantum/issues) to verify that this hasn't already been reported. +1 or comment there if it has.
- [ ] If possible, make a PR with a failing test to give us a starting point to work on!

### Describe the bug

On the Docker image installation page, we have:
`docker pull nvcr.io/nvidia/nightly/cuda-quantum:latest`
which leads to the following error.
`Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?`

### Steps to reproduce the bug

`docker pull nvcr.io/nvidia/nightly/cuda-quantum:latest`

### Expected behavior

Fix is
`docker pull nvcr.io/nvidia/cuda-quantum:latest`

### Is this a regression? If it is, put the last known working version (or commit) here.

Not a regression

### Environment

- **CUDA Quantum version**: 
- **Python version**: 
- **C++ compiler**: 
- **Operating system**:

**Comment by bmhowe23** [comment]
Hi @poojarao8 - I am not able to replicate your `Cannot connect to the Docker daemon` error on my machine, and that looks like a local machine error rather than a server error. Here's what happens when I ran it just now:
```bash
$ docker pull nvcr.io/nvidia/nightly/cuda-quantum:latest
latest: Pulling from nvidia/nightly/cuda-quantum
445a6a12be2b: Already exists
5690ed032a6a: Already exists
<SNIP>
Digest: sha256:ce22b58cb01f26597e26b9606f513eb546756b52e7daad2877919564fe957017
Status: Downloaded newer image for nvcr.io/nvidia/nightly/cuda-quantum:latest
nvcr.io/nvidia/nightly/cuda-quantum:latest

What's Next?
  View a summary of image vulnerabilities and recommendations → docker scout quickview nvcr.io/nvidia/nightly/cuda-quantum:latest
```

The fix that you recommended is to pull the latest released cuda-quantum, which will be older than the nightly build.

Have you been able to replicate this error on more than 1 machine?

**Comment by poojarao8** [comment]
The issue is from a new user who was trying to pull the image on their windows machine. I currently don't have access to one so I couldn't reproduce it. Thanks!

**Comment by schweitzpgi** [comment]
> The issue is from a new user who was trying to pull the image on their windows machine. I currently don't have access to one so I couldn't reproduce it. Thanks!

Windows?

**Comment by poojarao8** [comment]
Yes!

**Comment by bettinaheim** [comment]
@poojarao8 This is not a CUDA Quantum issue, but a using Docker on Windows issue; please install [Docker Desktop](https://docs.docker.com/desktop/install/windows-install/), launch Docker Desktop, and then try again. Note that you need to make sure that Docker Desktop is launched every time the machine reboots; you could add it to the start up applications.
