### ISSUE TITLE
Add Jupyter notebooks to CI

### ISSUE THREAD

**Issue by bettinaheim** [NVIDIA/cuda-quantum#726]
Right now, only the code examples in .cpp and .py files are tested as part of CI as defined here: https://github.com/NVIDIA/cuda-quantum/blob/main/docs/CMakeLists.txt. We have since added Jupyter notebooks that are used in the documentation but not automatically validated. It would be good to set up CI for these notebooks. A good start is CI that just checks that the notebooks run without issue. A fancier check would be to check that the cell output is correct.

**Comment by abhiram6121** [comment]
I'm interested in working on this.

**Comment by bettinaheim** [comment]
@abhiram6121 Wow, that was quick. :) 
That would be awesome! Have you already set up something similar and do you feel comfortable jumping into it with the minimal description I added, or do you need more info? If you feel you are good to go, could you post a quick outline of what you had in mind?

**Comment by abhiram6121** [comment]
Hi, I tried running `jupyter nbconvert --to notebook --execute notebook_name.ipynb` among files with .ipynb extension in the `docs/sphinx/examples/python/tutorials` directory. But getting below errors while converting some files.

```
RuntimeError                              Traceback (most recent call last)
Cell In[1], line 6
      3 qubit_count = 2                                                                              
      5 # Define the simulation target.
----> 6 cudaq.set_target("nvidia")
      8 # Define a quantum kernel function.
      9 kernel = cudaq.make_kernel()
RuntimeError: Invalid target name (nvidia).
```

```
TypeError                                 Traceback (most recent call last)
Cell In[3], line 1
----> 1 cpu_result = ghz_state(n_qubits=2, target="default")
      3 cpu_result.dump()

TypeError: ghz_state() got an unexpected keyword argument 'n_qubits'
```

Am I miss something?

**Comment by abhiram6121** [comment]
> @back-up-git @abhiram6121 (I assume that's the same person) No problem at all. There are a couple of different options for how to approach this. First things first - the goal: I would like to set up the validation in a way that doesn't rely on any unit tests or similar being included in the checked in notebook itself. It is nice if we can write the notebook in a way that is nicest for the documentation without worrying about how they are validated. Given that goal, I think the most straightforward way to set up validate is to simply run the notebook and compare the cell outputs to a checked in reference. More concretely: The notebooks that are on this repository already contain both the cells as well as their output. The [nbconvert](https://github.com/jupyter/nbconvert) tool can (among other things) be used to execute a notebook and save it (including all cell outputs) in a new notebook. If you run the command
> 
> ```shell
> jupyter nbconvert --to notebook --execute notebook_name.ipynb
> ```
> 
> (replacing notebook_name with the name of the notebook to validate), it will produce a new notebook called notebook_name.nbconvert.ipynb. You could write a python script that
> 
> 1. uses nbconvert to execute the notebook (you can either execute the command out of process or use the [Python API](https://nbconvert.readthedocs.io/en/latest/execute_api.html)) and checks that all cells were executed successfully
> 2. compares notebook_name.ipynb to notebook_name.nbconvert.ipynb and checks that they are the same.
> 
> Implementing 1) is a good start, and we can then add that python script to the CI. 2) is a bit of additional work since not all notebooks are deterministic, meaning their output may vary, and we likely need to adjust the notebooks a bit to validate the outputs. Do you want to give 1) a go and post here when you have a python script that runs a notebook and checks that it executes successfully?

Hi, I tried running `jupyter nbconvert --to notebook --execute notebook_name.ipynb` among files with .ipynb extension in the `docs/sphinx/examples/python/tutorials` directory. But getting below errors while converting some files.

```
RuntimeError                              Traceback (most recent call last)
Cell In[1], line 6
      3 qubit_count = 2                                                                              
      5 # Define the simulation target.
----> 6 cudaq.set_target("nvidia")
      8 # Define a quantum kernel function.
      9 kernel = cudaq.make_kernel()
RuntimeError: Invalid target name (nvidia).
```

```
TypeError                                 Traceback (most recent call last)
Cell In[3], line 1
----> 1 cpu_result = ghz_state(n_qubits=2, target="default")
      3 cpu_result.dump()

TypeError: ghz_state() got an unexpected keyword argument 'n_qubits'
```

Am I miss something?

**Comment by bmhowe23** [comment]
Hi @abhiram6121 - I think you've uncovered the first underlying issue that this GitHub issue is trying to prevent. That is - I think the code snippet for this isn't entirely correct. I think `n_qubits` needs to be changed to `qubit_count` to match the `ghz_state` function definition.

You may uncover more issues like this as you're working through it. Don't hesitate to ask questions if you're unsure.

**Comment by abhiram6121** [comment]
> Hi @abhiram6121 - I think you've uncovered the first underlying issue that this GitHub issue is trying to prevent. That is - I think the code snippet for this isn't entirely correct. I think `n_qubits` needs to be changed to `qubit_count` to match the `ghz_state` function definition.
> 
> You may uncover more issues like this as you're working through it. Don't hesitate to ask questions if you're unsure.

It worked, Thanks :+1:

**Comment by abhiram6121** [comment]
> @back-up-git @abhiram6121 (I assume that's the same person) No problem at all. There are a couple of different options for how to approach this. First things first - the goal: I would like to set up the validation in a way that doesn't rely on any unit tests or similar being included in the checked in notebook itself. It is nice if we can write the notebook in a way that is nicest for the documentation without worrying about how they are validated. Given that goal, I think the most straightforward way to set up validate is to simply run the notebook and compare the cell outputs to a checked in reference. More concretely: The notebooks that are on this repository already contain both the cells as well as their output. The [nbconvert](https://github.com/jupyter/nbconvert) tool can (among other things) be used to execute a notebook and save it (including all cell outputs) in a new notebook. If you run the command
> 
> ```shell
> jupyter nbconvert --to notebook --execute notebook_name.ipynb
> ```
> 
> (replacing notebook_name with the name of the notebook to validate), it will produce a new notebook called notebook_name.nbconvert.ipynb. You could write a python script that
> 
>     1. uses nbconvert to execute the notebook (you can either execute the command out of process or use the [Python API](https://nbconvert.readthedocs.io/en/latest/execute_api.html)) and checks that all cells were executed successfully
> 
>     2. compares notebook_name.ipynb to notebook_name.nbconvert.ipynb and checks that they are the same.
> 
> 
> Implementing 1) is a good start, and we can then add that python script to the CI. 2) is a bit of additional work since not all notebooks are deterministic, meaning their output may vary, and we likely need to adjust the notebooks a bit to validate the outputs. Do you want to give 1) a go and post here when you have a python script that runs a notebook and checks that it executes successfully?



````
import glob
import nbformat
from nbconvert.preprocessors import ExecutePreprocessor, CellExecutionError


"""
This script runs the code all the notebooks in the current directory, and catches and reports any raised exceptions.
"""


def execute(notebook_filename, run_path='.'):
    notebook_filename_out = notebook_filename.replace(
        '.ipynb', '.nbconvert.ipynb')

    with open(notebook_filename) as f:
        nb = nbformat.read(f, as_version=4)
    ep = ExecutePreprocessor(timeout=600, kernel_name='python3')

    success = True
    try:
        out = ep.preprocess(nb, {'metadata': {'path': run_path}})
    except CellExecutionError:
        out = None
        msg = 'Error executing the notebook "%s".\n\n' % notebook_filename
        msg += 'See notebook "%s" for the traceback.' % notebook_filename_out
        print(msg)
        success = False
        raise
    finally:
        with open(notebook_filename_out, mode='w', encoding='utf-8') as f:
            nbformat.write(nb, f)
        return success


if __name__ == '__main__':
    # Use glob to find files with the specified extension in the current directory
    notebook_filenames = glob.glob(f"*.ipynb")
    notebook_filenames = [
        fn for fn in notebook_filenames if not fn.endswith('.nbconvert.ipynb')]

    if notebook_filenames:
        notebooks_failed = []
        for notebook_filename in notebook_filenames:
            if not execute(notebook_filename):
                notebooks_failed.append(notebook_filename)

        if len(notebooks_failed) > 0:
            print("Failed! The following notebook(s) raised errors:\n" +
                  " ".join(notebooks_failed))
        else:
            print("Success! All the notebook(s) executed successfully.")
    else:
        print('Failed! No notebook found in the current directory.')
````

Hi @bettinahei, Here is the python script. Can you please have a look into this?

**Comment by bettinaheim** [comment]
@abhiram6121 
Do you want to give it a go adding this to the github pipeline? 
Concretely, I'd suggest the following:
- Fork this repository and create a branch where you make the following changes, then create a PR to this repository.
- Check in your python script under docs/notebook_validation.py
- Right after [this line](https://github.com/NVIDIA/cuda-quantum/blob/3d000678fdc3f93e21ae043817a498f1eeeda9a6/.github/workflows/docker_images.yml#L753), add a similar line that copies the docs/notebook_validation.py script into the container.
- Run your script either as part of the validate_container.sh script (i.e. edit the validate_container.sh script to invoke your script) or separately (i.e. add another line after the one you just added to run your script much like validate_container.sh is run). 

Some of the notebooks require backends that may not be available on all platforms/runners. The validate_container.sh script has a minimal logic that first checks what backends are available. Hence, for the forth bullet, it might be easiest to add the logic to invoke your script to the validate_container.sh script. The changes I would do for the forth bullet are then:
- Edit your python script to take a list of available backends as input
- Before executing a notebook, look for cells that contain a set_target invokation - I suggest to just do a simple regex matching along the lines of `re.search('set_target[\s\(]+"(.+)"',  notebook_content).groups()`, and then for each found group, check if it is in the list of available targets. If not, print a message that the notebook will be skipped, otherwise convert it. The matching is not going to be perfect, and e.g. doesn't catch if a target is set via variable name, but it should be a decent enough heuristic for the CI.
- Create a PR with your changes.

Does that give you some ideas for a next step? Let me know if you have any questions.

**Comment by abhiram6121** [comment]
@bettinaheim Sure, I will give it a try.
