### ISSUE TITLE
exp_pauli operation may only introduce change to global phase

### ISSUE THREAD

**Issue by schweitzpgi** [NVIDIA/cuda-quantum#739]
good point. in this case, the exp_pauli operation can just be erased since exp(III..) will only add global phase and thus not affect the backends we target. I will file an issue for us to come back and update this once we start tracking global phase in the IR.

_Originally posted by @amccaskey in https://github.com/NVIDIA/cuda-quantum/pull/712#discussion_r1344155971_

**Comment by 1tnguyen** [comment]
This is related to https://github.com/NVIDIA/cuda-quantum/issues/483

**Comment by bettinaheim** [comment]
Closing this as duplicate - will be tracked in/with 483
