### ISSUE TITLE
Add Support for Adaptive Profile QIR

### ISSUE THREAD

**Issue by bmhowe23** [NVIDIA/cuda-quantum#745]
### Description:

Adding support for the [Adaptive Profile](https://github.com/qir-alliance/qir-spec/pull/35) requires multiple steps. This issue is meant to capture the steps completed so far and document the remaining steps. The following checklist will be updated as we make progress.

- [x] #724
- [x] #741
- [ ] Work through failed tests added in the prior step that we want to support, and write longer term issues for the ones that are not needed prior to 0.5.0.
- [ ] Create new documentation to describe which types of programs are supported by the Adaptive Profile providers
- [x] #798 

Note that the Adaptive Profile supports many optional capabilities. This issue is meant to capture the _initial_ profile implementation with a minimum set of optional capabilities.

**Comment by bettinaheim** [comment]
Closing this as is for now. We will make further improvements to this when we improve/update the hardware backend support more broadly.
