### ISSUE TITLE
Need to make QuakeAddMetadataPass more robust

### ISSUE THREAD

**Issue by bmhowe23** [NVIDIA/cuda-quantum#749]
There's too much pattern matching on specific trees of IR nodes here. I think we should perform a reaching data-flow analysis over the function to determine what classical operations use the result(s) of a quantum measurement (a transitive closure). That set can then be examined to determine any control operations or control dependent subgraphs of the CFG.

_Originally posted by @schweitzpgi in https://github.com/NVIDIA/cuda-quantum/pull/741#discussion_r1348868118_

**Comment by bmhowe23** [comment]
The long-term plan is that we won't need the QuakeAddMetadataPass. That is - we should be able to update the simulator to not depend on the `qubitMeasurementFeedback` attribute and instead make "on the fly" decisions about path splitting with respect to the state vector.

Also note that this is somewhat related to #782.

**Comment by schweitzpgi** [comment]
Fixed with commit f444e01870e47da618c309d778aa4964410d2a4d
