### ISSUE TITLE
No c<op> defined for the ry gate 

### ISSUE THREAD

**Issue by zohimchandani** [NVIDIA/cuda-quantum#751]
### Required prerequisites

- [X] Search the [issue tracker](https://github.com/NVIDIA/cuda-quantum/issues) to check if your feature has already been mentioned or rejected in other issues.

### Describe the feature

We would like to do a controlled RY rotation. 

Potential syntax for it could be `kernel.cry(np.pi, [control, target])`.

Would appreciate it if we could add it in as it is not currently a[ valid operation in CUDAQ](https://nvidia.github.io/cuda-quantum/latest/api/default_ops.html#adjoint-and-controlled-operations:~:text=%5B1%5D).

**Comment by bettinaheim** [comment]
This issue goes beyond just cry; all unitary default operations listed [here](https://nvidia.github.io/cuda-quantum/latest/api/default_ops.html) should have a controlled (c<opname>) and adjoint version (<opname>dg) defined.
