### ISSUE TITLE
Manipulate quake values during assignment 

### ISSUE THREAD

**Issue by zohimchandani** [NVIDIA/cuda-quantum#754]
### Required prerequisites

- [X] Make sure you've read the [documentation](https://nvidia.github.io/cuda-quantum/latest). Your issue may be addressed there.
- [X] Search the [issue tracker](https://github.com/NVIDIA/cuda-quantum/issues) to verify that this hasn't already been reported. +1 or comment there if it has.
- [X] If possible, make a PR with a failing test to give us a starting point to work on!

### Describe the bug

For a particular application, we would like to do the following: 

```
import cudaq

theta = [3.14]

kernel, theta = cudaq.make_kernel(list)

qubits = kernel.qalloc(2)

kernel.rx(-1.0*(theta[0]) / 8.0, qubits[0])

kernel.ry(theta[0] / 8.0, qubits[1])

kernel.mz(qubits)

cudaq.sample(kernel, theta)

TypeError: unsupported operand type(s) for /: 'cudaq._pycudaq.QuakeValue' and 'float'
```

ie we would like to do `-theta/8` and `theta/8` as a parameter to a gate.

The workarounds for this is to define 2 thetas, perform all the operations outside and pass them in

```
import cudaq
import numpy as np 

kernel, thetas = cudaq.make_kernel(list)

qubits = kernel.qalloc(2)

kernel.rx(thetas[0], qubits[0])
kernel.ry(thetas[1], qubits[1])

kernel.mz(qubits)

theta_vals = [-np.pi/8, np.pi/8]

cudaq.sample(kernel, theta_vals).dump()

```

however for optimisation cases when we want the optimizer to only consider one value and proceed, defining 2 separate values does not work and will stray the intended optimisation procedure. 

The question is how do we manipulate operations at the quake level?

Thanks team  

### Steps to reproduce the bug

see above 

### Expected behavior

NA

### Is this a regression? If it is, put the last known working version (or commit) here.

Not a regression

### Environment

NA

**Comment by amccaskey** [comment]
If the division operator is not implemented in the Python bindings, then it should be added as soon as possible. 

A better workaround for this problem is to just use multiplication - `kernel.rx((1./8.)*theta[0], qubits[0])`

**Comment by zohimchandani** [comment]
Can confirm the above works 

```
import cudaq
import numpy as np 

theta_vals = [np.pi]

kernel, theta = cudaq.make_kernel(list)

qubits = kernel.qalloc(2)

kernel.rx( ((-1/8) * theta[0]) , qubits[0])

kernel.ry((1/8) * theta[0], qubits[1])

kernel.mz(qubits)

cudaq.sample(kernel, theta_vals).dump()
```
