### ISSUE TITLE
Emit error when expectation value on a qubit is out of range for the register of qubits allocated

### ISSUE THREAD

**Issue by zohimchandani** [NVIDIA/cuda-quantum#767]
### Required prerequisites

- [X] Make sure you've read the [documentation](https://nvidia.github.io/cuda-quantum/latest). Your issue may be addressed there.
- [X] Search the [issue tracker](https://github.com/NVIDIA/cuda-quantum/issues) to verify that this hasn't already been reported. +1 or comment there if it has.
- [X] If possible, make a PR with a failing test to give us a starting point to work on!

### Describe the bug

The code snippet below should throw up an error as we are calculating the z expectation value of the 50th qubit in a 2 qubit circuit: 

```

import cudaq 
from cudaq import spin 

n_qubits = 2

kernel = cudaq.make_kernel()

qubits = kernel.qalloc(n_qubits)

kernel.h(qubits)

hamiltonian = [spin.z(50)]

results = cudaq.observe(kernel, hamiltonian)

results[0].expectation_z()

0.9999999999999996
```

### Steps to reproduce the bug

NA

### Expected behavior

NA

### Is this a regression? If it is, put the last known working version (or commit) here.

Not a regression

### Environment

- **CUDA Quantum version**: Latest nightly

**Comment by khalatepradnya** [comment]
Checked this on `main` as of commit b1d7214c3fd360231b895b4a23ad8ac81b1890a5.
The output is -

`RuntimeError: [custatevec] %invalid value in observe (line 705)`

Hence closing this.
