### ISSUE TITLE
Emulation unit test failure: not setting qubitMeasurementFeedback

### ISSUE THREAD

**Issue by bmhowe23** [NVIDIA/cuda-quantum#782]
### Required prerequisites

- [X] Make sure you've read the [documentation](https://nvidia.github.io/cuda-quantum/latest). Your issue may be addressed there.
- [X] Search the [issue tracker](https://github.com/NVIDIA/cuda-quantum/issues) to verify that this hasn't already been reported. +1 or comment there if it has.
- [ ] If possible, make a PR with a failing test to give us a starting point to work on!

### Describe the bug

`test/NVQPP/qir_test_cond_for_loop-4.cpp` and `test/NVQPP/qir_test_cond_for_loop-5.cpp` are not passing because the `quake-add-metadata pass` is not adding the `qubitMeasurementFeedback` attribute.

These tests work correctly on Quantinuum's emulator, so this is just a local emulator issue that occurs when the user is running with `--emulate`.

The test are currently marked as `XFAIL`, but after fixing this issue, the tests should no longer fail.

### Steps to reproduce the bug

Execute the steps at the top of `test/NVQPP/qir_test_cond_for_loop-4.cpp` and `test/NVQPP/qir_test_cond_for_loop-5.cpp`.

### Expected behavior

The unit test should pass.

### Is this a regression? If it is, put the last known working version (or commit) here.

Not a regression

### Environment

- **CUDA Quantum version**: main
- **Python version**: N/A
- **C++ compiler**: 16.0
- **Operating system**: Ubuntu 22.04

**Comment by bmhowe23** [comment]
The long-term plan is that we won't need the QuakeAddMetadataPass. That is - we should be able to update the simulator to not depend on the `qubitMeasurementFeedback` attribute and instead make "on the fly" decisions about path splitting with respect to the state vector.

Also note that this is somewhat related to #749.

**Comment by bettinaheim** [comment]
Related, and containing @schweitzpgi's write op of the algorithm for detection we talked about: https://github.com/NVIDIA/cuda-quantum/issues/309

**Comment by bmhowe23** [comment]
Fixed by #1853 (test was renamed targettests/execution/qir_cond_for_loop-4.cpp since the original issue was posted).
