### ISSUE TITLE
Unit test failure on Quantinuum emulator: qir_test_cond_for_loop-6.cpp

### ISSUE THREAD

**Issue by bmhowe23** [NVIDIA/cuda-quantum#783]
### Required prerequisites

- [X] Make sure you've read the [documentation](https://nvidia.github.io/cuda-quantum/latest). Your issue may be addressed there.
- [X] Search the [issue tracker](https://github.com/NVIDIA/cuda-quantum/issues) to verify that this hasn't already been reported. +1 or comment there if it has.
- [ ] If possible, make a PR with a failing test to give us a starting point to work on!

### Describe the bug

For certain unrolled-loop test cases ([like the one in the title](https://github.com/NVIDIA/cuda-quantum/blob/bf84be434c007199506a034bc16552c6e411bd15/test/NVQPP/qir_test_cond_for_loop-6.cpp#L16)), the compiler is injecting `__quantum__rt__result_record_output` calls even if `if` checks prevent measurements from occurring.

The compiler should not inject those calls for cases like this.

### Steps to reproduce the bug

See [this gist](https://gist.github.com/bmhowe23/9f25fcadf0071abf89407a56c2096acb) for the resulting QIR coming from the compiler at the time of this issue creation.

The QIR can also be generated like this in the dev image like this:
```bash
[root@docker-desktop build (main)]# bin/nvq++ --target quantinuum --emulate ../test/NVQPP/qir_test_cond_for_loop-6.cpp 
[root@docker-desktop build (main)]# CUDAQ_DUMP_JIT_IR=1 ./a.out
```

You can also run it on the provider hardware in order to see a test actually fail:
```bash
[root@docker-desktop build (main)]# bin/nvq++ --target quantinuum --quantinuum-machine H1-1E ../test/NVQPP/qir_test_cond_for_loop-6.cpp 
[root@docker-desktop build (main)]# ./a.out 
{ 
  q0result%03 : { 0:92 1:8 }
   q0result%04 : { 1:2 0:98 }
   q0result%10 : { 0:100 }
   q0result%02 : { 1:12 0:88 }
   q0result%07 : { 1:1 0:99 }
   q0result%14 : { 0:100 }
   q0result%08 : { 0:100 }
   q0result%01 : { 1:29 0:71 }
   q0result%12 : { 0:100 }
   q0result%13 : { 0:100 }
   q0result%09 : { 1:1 0:99 }
   q0result%11 : { 0:100 }
   q0result%00 : { 1:46 0:54 }
   q0result%06 : { 1:1 0:99 }
   q0result%05 : { 0:100 }
   q0result%18 : { 0:100 }
   q0result%17 : { 0:100 }
   __global__ : { 00000010000000000000:1 10000000000000000000:46 01000000000000000000:29 00000001000000000000:1 00100000000000000000:12 00001000000000000000:2 00000000010000000000:1 00010000000000000000:8 }
   q0result%16 : { 0:100 }
   q0result%15 : { 0:100 }
   q0result%19 : { 0:100 }
}
FAILURE: nIterRan (20) >= nIter (20)
```

### Expected behavior

When run on `H1-1E`, the unit test should pass.

### Is this a regression? If it is, put the last known working version (or commit) here.

Not a regression

### Environment

- **CUDA Quantum version**: main
- **Python version**: N/A
- **C++ compiler**: 16.0
- **Operating system**: Ubuntu 22.04

**Comment by schweitzpgi** [comment]
No longer marked XFAIL.
