### ISSUE TITLE
[RFC] CUDA Quantum Support for Different MPI Implementations

### ISSUE THREAD

**Issue by 1tnguyen** [NVIDIA/cuda-quantum#802]
### Required prerequisites

- [X] Search the [issue tracker](https://github.com/NVIDIA/cuda-quantum/issues) to check if your feature has already been mentioned or rejected in other issues.

### Describe the feature

Currently, we build our docker image (`cuda-quantum`) against OpenMPI. 
The MPI support will thus be built and linked against OpenMPI (see `cudaq::mpi` namespace).

HPC centers often require specific MPI implementation (e.g., MPICH). For example, we couldn't use the `cuda-quantum` docker image with full MPI capability if MPICH is required.

There are a couple of solutions to this:

1. Provide Docker images for all MPI flavors (OpenMPI, MPICH, HPC-X, etc.)

2. Decouple MPI dependency via a plugin-like interface.

**Pros and Cons:**

(1) is straighforward and requires the least initial effort. The downside is CI runners's time and container registry storage space.

With (2), `libcudaq` becomes independent from MPI (portability) but requires code changes. 

A plugin-like interface involves:

- Some high-level C-API wrapper of MPI API (as a list of function pointers), e.g., this cuquantum [`MPICommunicator` struct](https://github.com/NVIDIA/cuQuantum/blob/main/samples/custatevec/samples_mpi/mpicomm.c#L100) 

- We could provide the plugins for some commonly used MPI libraries. Otherwise, this plugin code can be compiled natively on the host and injected into cuda-quantum via dynamic library loading.

**Comment by poojarao8** [comment]
If possible, it will be great to have this available before the workshop at nersc next week. Thanks!

**Comment by bettinaheim** [comment]
We are going for Option 2 here, and will specifically provide the plugins for OpenMPI and MPICH (included in cuquantum). We will match/depend on the same plugin interface as is used by cuquantum.
