### ISSUE TITLE
Typo in a tutorial

### ISSUE THREAD

**Issue by silvieillesova** [NVIDIA/cuda-quantum#812]
### Required prerequisites

- [X] Make sure you've read the [documentation](https://nvidia.github.io/cuda-quantum/latest). Your issue may be addressed there.
- [X] Search the [issue tracker](https://github.com/NVIDIA/cuda-quantum/issues) to verify that this hasn't already been reported. +1 or comment there if it has.
- [ ] If possible, make a PR with a failing test to give us a starting point to work on!

### Describe the bug

There is a problem in  tutorial hybrid_qnns.ipynb. Where when I run the code converted to .py file by:
```
jupyter nbconvert --to python hybrid_qnns.ipynb 
python3 hybrid_qnns.py
```
I get the following error:
```
AttributeError: 'cudaq._pycudaq.ObserveResult' object has no attribute 'expectation'. Did you mean: 'expectation_z'?
```
This seems to be caused by a typo on line 126, 

```  
expectation = torch.tensor(cudaq.observe(self.kernel, spin.z(0),
                                            thetas).expectation(),
                              device=device)
```

### Steps to reproduce the bug

To reproduce the bug, try either running the hybrid_qnns.ipynb  example directly.  Or convert it to .py file using the following commands:

```
jupyter nbconvert --to python hybrid_qnns.ipynb 
python3 hybrid_qnns.py
```
And you should get the same error.

### Expected behavior

The expected behavior is that the tutorial executes without errors.

### Is this a regression? If it is, put the last known working version (or commit) here.

682c5bc5a3584e5c5cb18398d47df8cb5b7cca08

### Environment

- **CUDA Quantum version: e9cb24b9**: 
- **Python version: Python 3.11.5**: 
- **Operating system: Red Hat Enterprise Linux 8.4** 

### Suggestions

To fix this error I had to rewrite the line to:

```  
expectation = torch.tensor(cudaq.observe(self.kernel, spin.z(0), thetas).expectation_z(), device=device)
```

with this change the code runs OK.

**Comment by Yaraslaut** [comment]
@silvieillesova  see https://github.com/NVIDIA/cuda-quantum/pull/791 PR changed documentation and introduced `expectation`  function in python module
