### ISSUE TITLE
Defining gates via unitaries 

### ISSUE THREAD

**Issue by zohimchandani** [NVIDIA/cuda-quantum#825]
### Required prerequisites

- [X] Search the [issue tracker](https://github.com/NVIDIA/cuda-quantum/issues) to check if your feature has already been mentioned or rejected in other issues.

### Describe the feature

This is not urgently required but would be nice to have the ability for a user to define an arbitary unitary in numpy which cudaq recognises as a valid quantum operation. 

Users may request many new additional gates in the future so would be nice to give them the functionality to do it themselves rather than it be a blocker in development. 

Thanks team.

**Comment by bettinaheim** [comment]
Addressed by #1475
