### ISSUE TITLE
Unable to use IQM QPU machine name with spaces

### ISSUE THREAD

**Issue by kukushechkin** [NVIDIA/cuda-quantum#866]
### Required prerequisites

- [X] Make sure you've read the [documentation](https://nvidia.github.io/cuda-quantum/latest). Your issue may be addressed there.
- [X] Search the [issue tracker](https://github.com/NVIDIA/cuda-quantum/issues) to verify that this hasn't already been reported. +1 or comment there if it has.
- [ ] If possible, make a PR with a failing test to give us a starting point to work on!

### Describe the bug

IQM machine names are represented by arbitrary strings and can contain spaces. Machine names are interpreted as QPU architectures during compilation and later when running against a particular station. `nvq++` should be able to handle such machine names.

### Steps to reproduce the bug

1. Locate an IQM QC station with a space in the architecture name (unfortunately there is no such station available publicly at the moment), for example let's imagine that `curl https://variant.qc.iqm.fi/cocos/quantum-architecture` returns:
```json
"quantum_architecture": {
	"name": "Adonis Variant",
	...
}
```

2. Compile a program targeting that architecture with `nvq++`:
```sh
nvq++ -g -v -target iqm --iqm-machine "Adonis Variant" -v ./iqm_example.cpp -o example
```

3. Execute the compiles program against `https://variant.qc.iqm.fi`:
```sh
IQM_SERVER_URL=https://variant.qc.iqm.fi ./example
```

4. CUDA Quantum runtime exception `IQM QPU architecture mismatch: Adonis != Adonis Variant` is raised

### Expected behavior

The program is successfully submitted for execution

### Is this a regression? If it is, put the last known working version (or commit) here.

Not a regression

### Environment

- **CUDA Quantum version**: nvq++ Version pre-0.5.0-developer
- **Python version**: Python 3.10.12 (from the dev container)
- **C++ compiler**: clang version 16.0.0 (https://github.com/llvm/llvm-project c0b45fef155fbe3f17f9a6f99074682c69545488) (from the dev container)
- **Operating system**: macOS 13.6

### Suggestions

Most probably this can apply to machine names from other vendors as well, so `--*-machine` CLI arguments for remote rest QPUs should be handled as quoted strings.

**Comment by Yaraslaut** [comment]
@kukushechkin  can you check please if this will resolve this issue? 
```
/w/y/r/cuda-quantum/r/c/p/d/r/h/iqm main• ❱ git diff
diff --git a/runtime/cudaq/platform/default/rest/helpers/iqm/iqm.config b/runtime/cudaq/platform/default/rest/helpers/iqm/iqm.config
index 15d6231..0eff8e5 100644
--- a/runtime/cudaq/platform/default/rest/helpers/iqm/iqm.config
+++ b/runtime/cudaq/platform/default/rest/helpers/iqm/iqm.config
@@ -37,7 +37,7 @@ while [ $# -gt 1 ]; do
                PLATFORM_EXTRA_ARGS="$PLATFORM_EXTRA_ARGS;url;$2"
                ;;
        --iqm-machine)
-               PLATFORM_EXTRA_ARGS="$PLATFORM_EXTRA_ARGS;qpu-architecture;$2"
+               PLATFORM_EXTRA_ARGS="$PLATFORM_EXTRA_ARGS;qpu-architecture;\"$2\""
                ;;
        esac
        shift 2
```
This will wrap argument of `--iqm-machine` with `"` inside `PLATFORM_EXTRA_ARGS`

**Comment by kukushechkin** [comment]
@Yaraslaut no, this doesn't seem to work:

```shell
/workspaces/cuda-quantum# git rev-parse HEAD
6912fe5a75cd98e86db1dc77858dee979c82ba08

/workspaces/cuda-quantum# git diff runtime/cudaq/platform/default/rest/helpers/iqm/iqm.config 
diff --git a/runtime/cudaq/platform/default/rest/helpers/iqm/iqm.config b/runtime/cudaq/platform/default/rest/helpers/iqm/iqm.config
index 15d6231a..0eff8e59 100644
--- a/runtime/cudaq/platform/default/rest/helpers/iqm/iqm.config
+++ b/runtime/cudaq/platform/default/rest/helpers/iqm/iqm.config
@@ -37,7 +37,7 @@ while [ $# -gt 1 ]; do
                PLATFORM_EXTRA_ARGS="$PLATFORM_EXTRA_ARGS;url;$2"
                ;;
        --iqm-machine)
-               PLATFORM_EXTRA_ARGS="$PLATFORM_EXTRA_ARGS;qpu-architecture;$2"
+               PLATFORM_EXTRA_ARGS="$PLATFORM_EXTRA_ARGS;qpu-architecture;\"$2\""
                ;;
        esac
        shift 2

/workspaces/cuda-quantum# nvq++ -g -v -target iqm --iqm-machine "Adonis Variant" -v docs/sphinx/examples/cpp/providers/iqm.cpp -o iqm_example
/opt/llvm/bin/clang++ -std=c++20 -DNVQPP_TARGET_BACKEND_CONFIG="iqm;emulate;false;disable_qubit_mapping;false;qpu-architecture;"Adonis"" -o nvqppGenTargetBackend.wcLzIw.o -c -x c++ /usr/local/cudaq/targets/backendConfig.cpp
In file included from <built-in>:455:
<command line>:1:102: error: invalid suffix on literal; C++11 requires a space between literal and identifier [-Wreserved-user-defined-literal]
#define NVQPP_TARGET_BACKEND_CONFIG "iqm;emulate;false;disable_qubit_mapping;false;qpu-architecture;"Adonis""
                                                                                                     ^
                                                                                                      
/usr/local/cudaq/targets/backendConfig.cpp:15:51: error: expected ';' after top level declarator
constexpr static const char ____targetBackend[] = NVQPP_TARGET_BACKEND_CONFIG;
                                                  ^
<command line>:1:102: note: expanded from macro 'NVQPP_TARGET_BACKEND_CONFIG'
2 errors generated.
failed: "/opt/llvm/bin/clang++ -std=c++20 -DNVQPP_TARGET_BACKEND_CONFIG="iqm;emulate;false;disable_qubit_mapping;false;qpu-architecture;"Adonis"" -o nvqppGenTargetBackend.wcLzIw.o -c -x c++ /usr/local/cudaq/targets/backendConfig.cpp"

```

**Comment by Yaraslaut** [comment]
> ```shell
> iqm;emulate;false;disable_qubit_mapping;false;qpu-architecture;"Adonis"
> ```

Oh, right. So i tested a bit further and it seems that spliting of variables from configuration side is working alright,  see: https://godbolt.org/z/eP6jraz9v
i think you can get some info in runtime with `CUDAQ_LOG_LEVEL=info,debug nvq++ ...`

**Comment by bmhowe23** [comment]
@Yaraslaut @kukushechkin - please take a look at the draft PR #1059 and let us know if it works for you. I'm keeping it as draft for now because I'd like to get your feedback on the proposed solution before we commit to this approach.

**Comment by Yaraslaut** [comment]
Thanks @bmhowe23 for the update, I can not test it unfortunately, @kukushechkin should be able though

**Comment by kukushechkin** [comment]
@bmhowe23 @Yaraslaut I've checked the `pr-machine-name-spaces` branch and it seems to work as expected compiling like this: `nvq++ -g -v -target iqm --iqm-machine "Adonis Variant" -v docs/sphinx/examples/cpp/providers/iqm.cpp -o iqm_example` (machine name should be quoted). Verified cases:
- compiled for "Adonis Variant" (the actual name of the internal machine I was checking against is different), executed against "Adonis" => check failed as expected
- compiled for "Adonis", executed against "Adonis Variant" => check failed as expected
- compiled for "Adonis Variant", executed against "Adonis Variant" => executed successfully.
