### ISSUE TITLE
mpirun prints out results np times 

### ISSUE THREAD

**Issue by zohimchandani** [NVIDIA/cuda-quantum#887]
### Required prerequisites

- [X] Make sure you've read the [documentation](https://nvidia.github.io/cuda-quantum/latest). Your issue may be addressed there.
- [X] Search the [issue tracker](https://github.com/NVIDIA/cuda-quantum/issues) to verify that this hasn't already been reported. +1 or comment there if it has.
- [X] If possible, make a PR with a failing test to give us a starting point to work on!

### Describe the bug

```

import cudaq 

def ghz_state(qubit_count, target):
    """A function that will generate a variable sized GHZ state (`qubit_count`)."""
    cudaq.set_target(target)

    kernel = cudaq.make_kernel()

    qubits = kernel.qalloc(qubit_count)

    kernel.h(qubits[0])

    for i in range(1, qubit_count):
        kernel.cx(qubits[0], qubits[i])

    kernel.mz(qubits)

    result = cudaq.sample(kernel, shots_count=1000)

    return result

gpu_result = ghz_state(qubit_count = 35, target="nvidia-mgpu")

gpu_result.dump()

```

```
cudaq@gorby:~/qgans$ mpirun -np 4 python3 test.py
{ 1111111111111111111111111111111111:505 0000000000000000000000000000000000:495 }
{ 1111111111111111111111111111111111:505 0000000000000000000000000000000000:495 }
{ 1111111111111111111111111111111111:505 0000000000000000000000000000000000:495 }
{ 1111111111111111111111111111111111:505 0000000000000000000000000000000000:495 }
```

The result is printed out 4 times rather than once whilst running on the `mgpu` platform with 4 gpus. Not sure if this is a bug?

### Steps to reproduce the bug

NA

### Expected behavior

NA

### Is this a regression? If it is, put the last known working version (or commit) here.

Not a regression

### Environment

- **CUDA Quantum version**: 
- **Python version**: 
- **C++ compiler**: 
- **Operating system**: 

### Suggestions

NA

**Comment by zohimchandani** [comment]
Even if you have a simple snippet: 

```
print(1)
print(2)

```

and one executes it with `mpirun -n 3 python test.py`, the output is printed out three times: 

```
cudaq@gorby:~/basf/basf$ mpirun -n 3 python test.py
1
2
1
2
1
2

```

**Comment by amccaskey** [comment]
Hey Zohim. This all makes sense. This is how MPI works - there are N concurrent heavy processes running the same code. The MPI API calls within the code orchestrate communication and which process does what subset of the work. Since they all run the same process, any print statements that are hit will be print by all processes. If you'd like to tailor which process prints what (e.g. the master rank is the only one that writes to stdout), then you could do something like 
```python
if cudaq.mpi.rank() == 0:
   print(1)
   print(2)
```
or 
```python
if cudaq.mpi.rank() == 0:
   gpu_result.dump()
```
