### ISSUE TITLE
Error should be thrown when trying to access qubit outside range of allocated qubits 

### ISSUE THREAD

**Issue by zohimchandani** [NVIDIA/cuda-quantum#9]
The code snippet below should raise an error 

```
kernel, features = cudaq.make_kernel(list)

qubits = kernel.qalloc(8)

kernel.rx(features[0], qubits[100])

```

**Comment by amccaskey** [comment]
This was started before the open release. We should be able to provide a PR soon here on Github for this. The plan was to create thin wrapper types the `QuakeValue` at the Python binding level for MLIR values of type `quake.qvec` and `quake.qref`, and let those types keep track of runtime-known QVec size, for instance.

**Comment by khalatepradnya** [comment]
Observed behavior on `main` as of commit ID [9b9124c](https://github.com/NVIDIA/cuda-quantum/commit/9b9124c9747f1c11fdfd587b4c2bb68596db4832) :

If the kernel is used, i.e. invoked directly or via other primitive such as sampling API, like -
```
import cudaq

kernel, features = cudaq.make_kernel(list)

qubits = kernel.qalloc(8)

kernel.rx(features[0], qubits[100])

kernel([3.14])
```

then the following error is thrown -
```
error: 'quake.extract_ref' op invalid index [100] because >= size [8]
RuntimeError: cudaq::builder failed to JIT compile the Quake representation.
```
