### ISSUE TITLE
Combining mgpu and mqpu platforms to work in tandem 

### ISSUE THREAD

**Issue by zohimchandani** [NVIDIA/cuda-quantum#911]
### Required prerequisites

- [X] Search the [issue tracker](https://github.com/NVIDIA/cuda-quantum/issues) to check if your feature has already been mentioned or rejected in other issues.

### Describe the feature

`mgpu` target allows one to scale qubit count by pooling gpu memory together. It is purely designed for simulation mode. 

`mqpu` allows one to parallelize over multiple qpus. For example, to perform gradient batching, one has to set the `mqpu` target and use `observe_async` 

I can imagine workflows where we would like to do 40 qubit simulations and batch gradient calculations. This requires the use of `mgpu` and `mqpu` platforms simultaneously. 

From a usage perspective, `mqpu` is accessed via the `async` functionality explicitly and hence may not require one to set the target if we can offload its functionality to `async`. We can then use `mgpu` to scale qubit counts whilst having access to `mqpu` via `async`. 

Thanks team.

**Comment by bettinaheim** [comment]
Addressed with the introduction of the remote-mqpu platform.
