### ISSUE TITLE
Ship docker container with htop 

### ISSUE THREAD

**Issue by zohimchandani** [NVIDIA/cuda-quantum#912]
### Required prerequisites

- [X] Search the [issue tracker](https://github.com/NVIDIA/cuda-quantum/issues) to check if your feature has already been mentioned or rejected in other issues.

### Describe the feature

One needs `htop` to monitor cpu usage but it is cumbersome to install via sudo. Moreover if one does not have sudo privilage, it makes life hard. Can we ship containers with this installed as default please?

**Comment by Yaraslaut** [comment]
You can use `top` if `htop` is not provided

**Comment by bettinaheim** [comment]
@zohimchandani You have sudo privileges in the container, see also the README in the container. You can install htop with the command `sudo apt-get install htop`.
