### ISSUE TITLE
Cuda-quantum uses too much memory on multi-GPU

### ISSUE THREAD

**Issue by nadbp** [NVIDIA/cuda-quantum#970]
### Required prerequisites

- [X] Make sure you've read the [documentation](https://nvidia.github.io/cuda-quantum/latest). Your issue may be addressed there.
- [X] Search the [issue tracker](https://github.com/NVIDIA/cuda-quantum/issues) to verify that this hasn't already been reported. +1 or comment there if it has.
- [ ] If possible, make a PR with a failing test to give us a starting point to work on!

### Describe the bug

I tried to run the bernstein_vazirani.py example on my two-GPU server but got a "Too few GPUs for too many qubits" runtime error. The command I used is "mpiexec -np 2 python3 -m mpi4py bernstein_vazirani.py --size 31 --target nvidia-mgpu". I tried both the docker and the python-package, and got the same error.
I have two RTX 3090 GPUs (24G*2) on my machine. I successfully ran "python  bernstein_vazirani.py --size 30 --target nvidia", and it used about 17G out of 24G. I also successfully ran "mpiexec -np 2 python3 -m mpi4py bernstein_vazirani.py --size 30 --target nvidia-mgpu", but the program took about 17G on each GPU and 34G totally. Doea this mean cuda-quantum cannot split a large state vector and make use of multiple GPUs? It does not make sense.  

### Steps to reproduce the bug

Just follow the document, start a docker or install the python package locally, and then run "mpiexec -np 2 python3 -m mpi4py bernstein_vazirani.py --size 31 --target nvidia-mgpu". If your GPU has memory larger than 24G, you should use a bigger size. Anyway, you will see the multi-gpu target uses much more memory than the nvidia target. 

### Expected behavior

If I can run 30 qubits on one GPU, I should be able to run 31 qubits on two GPUs.
One more question: How do I debug cuda-quantum after I get such an error?

### Is this a regression? If it is, put the last known working version (or commit) here.

Not a regression

### Environment

- **CUDA Quantum version**:  0.5.0
- **Python version**:  3.10.0
- **C++ compiler**:  g++9.4.0
- **Operating system**:  Ubuntu 20.04

**Comment by 1tnguyen** [comment]
@nadbp The memory usage that you've observed is expected. The `nvidia` target used `fp32` while the `nvidia-mgpu` used `fp64`.
To double check, you can change the target to `nvidia-fp64`. I think you'll get an out-of-memory error on your RTX 3090 setup (requires ~33-34G for 30-qubit `bernstein_vazirani.py`).

**Comment by nadbp** [comment]
> @nadbp The memory usage that you've observed is expected. The `nvidia` target used `fp32` while the `nvidia-mgpu` used `fp64`. To double check, you can change the target to `nvidia-fp64`. I think you'll get an out-of-memory error on your RTX 3090 setup (requires ~33-34G for 30-qubit `bernstein_vazirani.py`).

Thank you for the reply. However, when I run 30-qubit bernstein_vazirani.py with the target nvidia, there is ONE print result consisting of encoded bitstring and measured state; when I run the 30-qubit example with mpiexec -np 2 and the nvidia-mgpu target, there are TWO print results. You can try the example by yourself. It means that mpiexec actually run the program twice. The memory usage is not because of fp64. The reason is two instances are running in parallel. In another words, so called 'nvidia-mgpu' does not simulate a single large state vector on multiple GPUs for this example. 
Could you please give me an example that clearly shows how a single large state vector is simulated on multiple GPUs? Thank you very much.

**Comment by 1tnguyen** [comment]
Hi @nadbp,

Yea, I'm aware of there are duplicates in the final printing. It is just a side-effect of invoking the whole application with MPI, namely, while the simulation is distributed between processes, the pre-processing (e.g., circuit generation) and post-processing (e.g., result printing) are duplicated work.

To understand the detail running of the simulator, you can do `export CUSTATEVEC_LOG_LEVEL=6` as described in the `cuquantum` docs. There, you can compare the `nvidia`/`nvidia-fp64` with `nvidia-mgpu`. For example, with `nvidia-mgpu`, we can see the logs related to `custatevecDistIndexBitSwap`, etc. 
For example, near the beginning, you might see 
```
[2023-11-28 03:22:09][cuStateVec][122927][Api][custatevecDistIndexBitSwapSchedulerCreate] nGlobalIndexBits = 1
[2023-11-28 03:22:09][cuStateVec][122927][Api][custatevecDistIndexBitSwapSchedulerCreate] nLocalIndexBits = 30
```
telling us that the simulator is splitting the state vector between the two GPUs.
Please let us know if that is not the case.

Unfortunately, with only 2 GPUs available, I don't think we could clearly differentiate between `nvidia` (32-bit floats) and `nvidia-mgpu` (64-bit floats) in terms of the number of qubits that they can handle. We'll need at least 4 GPUs.

BTW, when running the `bernstein_vazirani.py` example with MPI, make sure that you also pass the `--seed` to make sure all processes use the same `hidden_bitstring`, e.g., 
```
mpirun -np 2 python3 bernstein_vazirani.py --target nvidia-mgpu --size 30 --seed 1
```

**Comment by nadbp** [comment]
Thank you for the information! I see different data types and other information from the log. How can I avoid the duplicated pre- and post-processing in my program? I guess I cannot use f32 for nvidia-mgpu, right?
BTW, I do not see any log when I use mpirun and the tensornet target. It seems that the program runs on only one GPU. How can I run a tensornet simulation on two GPUs? Thank you again!

**Comment by 1tnguyen** [comment]
> I see different data types and other information from the log. How can I avoid the duplicated pre- and post-processing in my program? 

To filter the log, you can put `print` statements inside a MPI rank check like this

```
if cudaq.mpi.rank() == 0:
        print(f"encoded bitstring = {hidden_bitstring}")
        print(f"measured state = {result.most_probable()}")
        print(f"Were we successful? {hidden_bitstring == result.most_probable()}")
```

> I guess I cannot use f32 for nvidia-mgpu, right?

Yes, that's right. Currently, the `nvidia-mgpu` target only supports fp64 data type.

> How can I run a tensornet simulation on two GPUs?

Since the `tensornet` backend supports both MPI/non-MPI execution, we'll need to _initialize_ MPI to enable MPI distribution.
e.g., you might try something like this to test the backend:

```
import cudaq
cudaq.mpi.initialize()
cudaq.set_target("tensornet")
kernel = cudaq.make_kernel()
qubits = kernel.qalloc(100)
kernel.h(qubits[0])
for i in range(99):
    kernel.cx(qubits[i], qubits[i + 1])
kernel.mz(qubits)
result = cudaq.sample(kernel, shots_count=100)
if cudaq.mpi.rank() == 0:
    print(result)
cudaq.mpi.finalize()
```

Then, run with MPI like usual: `mpirun -np <N> python3 file.py`.

**Note**: currently, only the cuda-quantum _docker images_ (not the wheels) support `tensornet` with MPI.

> I do not see any log when I use mpirun and the tensornet target.

The equivalent environment variable to turn on cuTensorNet logging is `CUTENSORNET_LOG_LEVEL`, e.g., `export CUTENSORNET_LOG_LEVEL=6` to enable detail logging.

Hope that this helps!

**Comment by nadbp** [comment]
Wow, your answer really helps! One more question: How do I run a simulation over multiple nodes, statevec or tensornet, using the cuda-quantum docker image?

**Comment by 1tnguyen** [comment]
> How do I run a simulation over multiple nodes, statevec or tensornet, using the cuda-quantum docker image?

This depends on the configuration of your cluster. I don't have any experience with self-managed clusters.
On HPC systems, they will typically support running Docker containers via Singularity, Podman, or Shifter. 
We can use the `cuda-quantum` docker image with those tools to submit a multi-node simulation job using those backends.
For example, in our docs, we have a [section](https://nvidia.github.io/cuda-quantum/latest/install.html#singularity) about building a singularity `.sif` from the docker image. Podman and Shifter would be able to take the docker image directly.
The user guide of your HPC cluster should mention if it supports Docker containers and how to use it.

**Comment by nadbp** [comment]
Thank you very much. I run a tensornet simulation using the docker image. It seems that the program still runs on a single GPU. I start the docker using 'docker run -it --gpus all --name cuda-quantum nvcr.io/nvidia/nightly/cuda-quantum:latest' and then run the example 'mpiexec -np 2 python3 bernstein_vazirani.py --size 30 --seed 1 --target tensornet'. Anything is wrong?

**Comment by 1tnguyen** [comment]
Did you insert calls to initialize `mpi`? 
Also, there is a bug (soon to be [fixed](https://github.com/NVIDIA/cuda-quantum/pull/974)) affecting the `--target tensornet` option. 

To get it working properly, you'll need to add the `cudaq.set_target("tensornet")` explicitly after `cudaq.mpi.initialize()`

```
cudaq.mpi.initialize()
cudaq.set_target("tensornet")
```

and run with
```
mpiexec -np 2 python3 bernstein_vazirani.py --size 30 --seed 1
```

Please let me know if that works.
To check cutensornet log (`CUTENSORNET_LOG_LEVEL=6`), look for log lines such as "Initializing cuTensorNet distributed communication service interface", "Engaged distributed TN path finder with X processes", etc.

**Comment by nadbp** [comment]
It works now! Thank you for your patience!

**Comment by nadbp** [comment]
I will close this issue. Thank you again.
