### ISSUE TITLE
Semantics of measurement and `cudaq::sample`

### ISSUE THREAD

**Issue by boschmitt** [NVIDIA/cuda-quantum#980]
### Required prerequisites

- [X] Make sure you've read the [documentation](https://nvidia.github.io/cuda-quantum/latest). Your issue may be addressed there.
- [X] Search the [issue tracker](https://github.com/NVIDIA/cuda-quantum/issues) to verify that this hasn't already been reported. +1 or comment there if it has.
- [ ] If possible, make a PR with a failing test to give us a starting point to work on!

### Describe the bug

It is unclear what is the semantics of the measurement operation and how it works with `cudaq::sample`. At first, it seems that a measurement operation only measures the qubit. However, it seems that the operation is not collapsing the quantum state.

## Example 1:
```cpp
#include <cudaq.h>
#include <iostream>

void foo() __qpu__ {
  cudaq::qubit a;
  cudaq::mz(a);
  cudaq::h(a);
  cudaq::mz(a);
}

void bar() __qpu__ {
  cudaq::qubit a;
  cudaq::x(a);
  auto a0 = cudaq::mz(a);
  cudaq::h(a);
  auto a1 = cudaq::mz(a);
}

int main() {
  std::cout << "Foo:\n";
  auto result = cudaq::sample(foo);
  result.dump();

  std::cout << "Bar:\n";
  result = cudaq::sample(bar);
  result.dump();

  return 0;
}
```
Results when compiled in library mode:
```
Foo:
{ 0:1000 }
Bar:
{ 1:1000 }
```
Results when compiled in _without_ library mode:
```
Foo:
{ 0:1000 }
Bar:
{
  a0 : { 1:1000 }
   __global__ : { 1:1000 }
   a1 : { 0:509 1:491 }
}
```

## Example 2 (same as before, but resetting the qubit):
```cpp
#include <cudaq.h>
#include <iostream>

void foo() __qpu__ {
  cudaq::qubit a;
  cudaq::mz(a);
  cudaq::reset(a); // properly reset the qubit!
  cudaq::h(a);
  cudaq::mz(a);
}

void bar() __qpu__ {
  cudaq::qubit a;
  cudaq::x(a);
  auto a0 = cudaq::mz(a);
  cudaq::reset(a); // properly reset the qubit!
  cudaq::h(a)
  auto a1 = cudaq::mz(a);
}

int main() {
  std::cout << "Foo:\n";
  auto result = cudaq::sample(foo);
  result.dump();

  std::cout << "Bar:\n";
  result = cudaq::sample(bar);
  result.dump();

  return 0;
}
```

Results when compiled in library mode:
```
Foo:
{ 0:1000 }
Bar:
{ 0:1000 }
```
Results when compiled in _without_ library mode:
```
Foo:
{ 0:1000 }
Bar:
{
  a0 : { 1:1000 }
   a1 : { 0:529 1:471 }
   __global__ : { 0:529 1:471 }
}
```

## Example 1
EDIT: Thanks Ben from point it out that this is definitely valid. The problem is the results retuned.
~~The runtime (or compiler) should emit an error about the use of a qubit after measurement without a proper reset. (The assumption here is that the semantics of measurement is to only collapse the state, not to reset it.)~~

## Example 2
It seems that when measurements are not put into variables, only the first measurement of a qubit is considered. This creates an inconsistency with `__global__` when there is name---as in this case the last measurement is considered.

### Is this a regression? If it is, put the last known working version (or commit) here.

Not a regression

### Environment

- **CUDA Quantum version**: nvq++ proto-0.6.0 (main branch)
- **C++ compiler**: g++ 13.2.0
- **Operating system**:  Ubuntu 23.10 (Docker container)

**Comment by bmhowe23** [comment]
> The runtime (or compiler) should emit an error about the use of a qubit after measurement without a proper reset.

Why? I believe it is legal to perform quantum operations on a qubit after a measurement even without performing a reset. If the measurement collapsed it to a `|1>`, then that is still a valid quantum state from which to start operating.

**Comment by boschmitt** [comment]
> > The runtime (or compiler) should emit an error about the use of a qubit after measurement without a proper reset.
> 
> Why? I believe it is legal to perform quantum operations on a qubit after a measurement even without performing a reset. If the measurement collapsed it to a `|1>`, then that is still a valid quantum state from which to start operating.

That is correct, thanks for bring it up.
