### ISSUE TITLE
Ghost qubit in library mode

### ISSUE THREAD

**Issue by boschmitt** [NVIDIA/cuda-quantum#981]
### Required prerequisites

- [X] Make sure you've read the [documentation](https://nvidia.github.io/cuda-quantum/latest). Your issue may be addressed there.
- [X] Search the [issue tracker](https://github.com/NVIDIA/cuda-quantum/issues) to verify that this hasn't already been reported. +1 or comment there if it has.
- [ ] If possible, make a PR with a failing test to give us a starting point to work on!

### Describe the bug

The sampling of a circuit with a single qubit returns a result with a bitstring with two bits.  

### Steps to reproduce the bug

Compile the following circuit in library mode:
```cpp
#include <cudaq.h>
#include <iostream>

void bar() __qpu__ {
  cudaq::qubit a;
  cudaq::x(a);
  auto a0 = cudaq::mz(a);
  cudaq::reset(a);
  auto a1 = cudaq::mz(a);
}

int main() {
  std::cout << "Bar:\n";
  auto result = cudaq::sample(bar);
  result.dump();

  return 0;
}
```
It's execution returns:
```
Bar:
{ 00:1000 }
```

_Note_: this problem seems to not happen when we add a quantum operator after the `reset`.

### Expected behavior

It should return:
```
Bar:
{ 0:1000 }
```

### Is this a regression? If it is, put the last known working version (or commit) here.

Not a regression

### Environment

- **CUDA Quantum version**: nvq++ proto-0.6.0 (main branch)
- **C++ compiler**: g++ 13.2.0
- **Operating system**:  Ubuntu 23.10 (Docker container)

**Comment by bmhowe23** [comment]
It seems to me that two separate measurements should return two separate answers, so I would think that the correct answer should be:
```
Bar:
{ 10:1000 }
```

**Comment by bmhowe23** [comment]
> This is not the semantics of `cudaq::sample`. In the bitstrings of its result, each bit correspond to the measure state of a qubit, not a sequence of measurements of the same qubit.

This would mean that `cudaq::sample` would be unable to reuse a qubit and save the measurement from earlier usages. Maybe it's just me, but that seems undesirable to me.

Stepping back a bit, will this issue still be relevant if we consider changes to `cudaq::sample` that allow the user to more clearly specify the return values (i.e. use something other than `void`)?
